### PR TITLE
Update version to 0.960+dev

### PR DESCRIPTION
**Pull request by JukkaL**

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Wait we haven't released 0.950 yet, have we?

**Comment by JelleZijlstra** [comment]
I see, the release branch already exists.

**Comment by YouJiacheng** [comment]
Hi! Could you please let me know when do you plan to release 0.950 (to pypi)?

**Comment by AlexWaygood** [comment]
@YouJiacheng, you can follow along here:

- #12579

**Comment by YouJiacheng** [comment]
Thanks!

**Pull request merged**
