### PR TITLE
Fix crash when annotating callable definition location

### LINKED ISSUE #3362: "INTERNAL ERROR" when an unexpected keyword argument is given to subprocess.Popen
The file `example.py` includes the following:

```
import subprocess
subprocess.Popen(example=True)
```

There is no `mypy` config file.

The following error is given:

```
(e2e) Adam@Adams-MacBook-Pro ~/Desktop> mypy example.py --show-traceback
example.py:2: error: Unexpected keyword argument "example" for "Popen"
example.py:2: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.511
Traceback (most recent call last):
  File "/Users/Adam/.virtualenvs/e2e/bin/mypy", line 6, in <module>
    main(__file__)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/main.py", line 93, in type_check_only
    options=options)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/build.py", line 188, in build
    graph = dispatch(sources, manager)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/build.py", line 1595, in dispatch
    process_graph(graph, manager)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/build.py", line 1838, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/build.py", line 1937, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/build.py", line 1510, in type_check_first_pass
    self.type_checker.check_first_pass()
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/checker.py", line 177, in check_first_pass
    self.accept(d)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/checker.py", line 264, in accept
    stmt.accept(self)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/nodes.py", line 825, in accept
    return visitor.visit_expression_stmt(self)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/checker.py", line 1823, in visit_expression_stmt
    self.expr_checker.accept(s.expr, allow_none_return=True)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/checkexpr.py", line 2054, in accept
    typ = self.visit_call_expr(node, allow_none_return=True)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/checkexpr.py", line 201, in visit_call_expr
    ret_type = self.check_call_expr_with_callee_type(callee_type, e)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/checkexpr.py", line 341, in check_call_expr_with_callee_type
    e.arg_names, callable_node=e.callee)[0]
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/checkexpr.py", line 396, in check_call
    arg_names, formal_to_actual, context, self.msg)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/checkexpr.py", line 759, in check_argument_count
    callee, actual_names[i], context)
  File "/Users/Adam/.virtualenvs/e2e/lib/python3.6/site-packages/mypy/messages.py", line 619, in unexpected_keyword_argument
    path = self.modules[module_name].path
KeyError: 'subprocess.Popen'
example.py:2: note: use --pdb to drop into pdb
```

Further system info:

```
(e2e) Adam@Adams-MacBook-Pro ~/Desktop> mypy --version
mypy 0.511
(e2e) Adam@Adams-MacBook-Pro ~/Desktop> python
Python 3.6.0 (default, Mar  4 2017, 12:32:34)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

### PR DESCRIPTION
**Pull request by miedzinski**
Fixes #3362.

### CODE REVIEW

**Comment by miedzinski** [comment]
I have no idea how to add test case for this.

```python
[case testUnexpectedKwargsDefinedHere]
import m
m.A(x=1)  # E: Unexpected keyword argument "x" for "A"
[file m.py]
class A:
    def __init__(self) -> None:  # N: "A" defined here
        pass
```

doesn't trigger note, because `typ.definition.fullname()` returns `None`.

**Comment by ilevkivskyi** [comment]
@miedzinski 
I have found what is the problem. The ``_fulname`` attribute of function definition is not set in first pass for _methods_, since methods are not visited during the first pass. I added this code:
```python
            if not defn._fullname:
                defn._fullname = self.qualified_name(defn.name())
```
in ``visit_func_def`` of second pass on line 330 and it works:
```
tst22.py:21: error: Unexpected keyword argument "example" for "Popen"
/usr/local/lib/mypy/typeshed/stdlib/3/subprocess.pyi:276: note: "Popen" defined here
```
(also works with your test example above).

**Comment by miedzinski** [comment]
Do you want me to include it with this patch or would you like to submit it yourself?

**Comment by ilevkivskyi** [comment]
> Do you want me to include it with this patch

Yes.

**Comment by ilevkivskyi** [comment]
And tests

**Comment by gvanrossum** [comment]
I just received a spurious message of the form
```
/Users/guido/src/mypy/typeshed/stdlib/3/builtins.pyi:594: note: "sort" of "list" defined here
```
The code to issue this message was modified by this PR.

I have not been able to repro this "in the lab" yet (the above was part of a huge run on internal code), but I suspect that this might be related to an error in another file that was ignored by `# type: ignore` in some other file. The fix would be to somehow check whether the fail() call actually caused an error to be generated or not. (That would require some surgery to get the error machinery to return that information -- several methods would have to pass this info back reliably.)

**Comment by pkch** [comment]
I don't have a specific solution proposal yet, but a very similar issue came up in my discussions with @ilinum about how to do #3141 more reliably: it would have helped if the error engine was more knowledgeable.

**Comment by gvanrossum** [comment]
I also noticed that the spurious note seems to only appear with a cold `-i` cache. This may be a different problem with the same code -- finding the module may fail if the module was read from the cache.

**Comment by ilevkivskyi** [comment]
I would propose an alternative solution. We could report the note on the same line as error, but report the source in the note itself, something like:
```
test.py: 16: error: Incompatible something ...
test.py: 16: note: "something" defined in /some/other/file on line 144
```
Adding ``# type: ignore`` will silence both the error and the note. This solution will have one important additional benefit: there is an issue to sort errors by file, and after sorting all errors, the error and the note may be far apart from each other, which would be weird. With this solution they will be always together.

(TBH, this wording also seems nicer to me than the current one.)

**Comment by gvanrossum** [comment]
Finally it *may* be the case that what I saw was due to some filtering script we have that black-lists certain files.

**Comment by miedzinski** [comment]
Already said that on gitter: this is might have been introduced in this patch, mainly thanks to fix @il

**Comment by gvanrossum** [comment]
A downside to @ilevkivskyi's solution is that I can't hit Enter in the Emacs `*compilation*` window to go to the definition.

**Pull request merged**
