### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by AlexWaygood**
Source commit: https://github.com/python/typeshed/commit/257e287fec930db1f42ddf0ca1f53e33c9a9398b.

The automated PR by the bot failed again due to merge conflicts with the cherry-picked commits: https://github.com/python/mypy/actions/runs/4298562919/jobs/7492803753#step:5:53.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Most of the hits here are from https://github.com/python/typeshed/pull/6670. That typeshed commit solves a lot of issues for pyright, but it seems like it currently only causes false positives for mypy. Until mypy improves its support for `ParamSpec`, I'd be in favour of adding it to the typeshed changes we manually revert in our typeshed syncs. Thoughts on that?

**Comment by AlexWaygood** [comment]
- The `pip` hit is from https://github.com/python/typeshed/pull/9734
- Both other hits are from https://github.com/python/typeshed/pull/9811

**Comment by tmke8** [comment]
4 of the errors from the typeshed `@wraps` PR seem to just be due to the fact that `_Wrapped` doesn't define `__name__`:

- the pandas error
- the 2 spark errors
- the streamlit error

Looking at the implementation of `update_wrapper` (which is the function that returns `_Wrapped`), I see that by default it will set `('__module__', '__name__', '__qualname__', '__doc__',  '__annotations__')` on the object it returns, which maybe implies that `_Wrapped` should have these attributes, though this can be customized with a parameter to `update_wrapper`...

**Comment by AlexWaygood** [comment]
> 4 of the errors from the typeshed `@wraps` PR seem to just be due to the fact that `_Wrapped` doesn't define `__name__`:
> 
> * the pandas error
> * the 2 spark errors
> * the streamlit error
> 
> Looking at the implementation of `update_wrapper` (which is the function that returns `_Wrapped`), I see that by default it will set `('__module__', '__name__', '__qualname__', '__doc__', '__annotations__')` on the object it returns, which maybe implies that `_Wrapped` should have these attributes, though this can be customized with a parameter to `update_wrapper`...

Want to try making a typeshed PR?

**Comment by tmke8** [comment]
Sure.

**Comment by AlexWaygood** [comment]
You can obviously cook up theoretical situations where adding `__name__` to `_Wrapped` would cause false negatives:

```pycon
>>> class Foo:
...     def __call__(self): ...
...
>>> class Bar:
...     def __call__(self): ...
...
>>> from functools import update_wrapper
>>> wrapped = Foo()
>>> wrapper = Bar()
>>> update_wrapper(wrapper, wrapped)
<__main__.Bar object at 0x000002CB493C9C50>
>>> _.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Bar' object has no attribute '__name__'. Did you mean: '__ne__'?
```

But these seem pretty rare, and not worth worrying about. Adding `__name__` (and friends) to `_Wrapped` sounds like a promising idea to me.

**Comment by AlexWaygood** [comment]
FWIW though, even if we make that change, I think I'd still want the changes to `functools.wraps` reverted in mypy's vendored version of typeshed. There's still too many other errors imo.

**Comment by hauntsaninja** [comment]
Thanks, this looks good but we should probably resync with https://github.com/python/typeshed/pull/9835 since that'll be another merge conflict

**Comment by AlexWaygood** [comment]
https://github.com/python/typeshed/pull/9815 will also cause merge conflicts for the next sync — any interest in taking a quick look at that one before I resync?

**Comment by hauntsaninja** [comment]
Thanks!

**Pull request merged**
