### PR TITLE
Disable cache in non-incremental tests

### LINKED ISSUE #3253: Performance regression in pytest tests due to always writing cache
Commit 264715e1fdcc9e8df2bbdff1168b68725864c01b slowed down pytest tests by about 50% when I run them locally. I'd rather not write cache files by default when running locally -- maybe we can only do it on CI builds. Alternatively, I'd like a documented option to skip writing cache to speed up tests.

### PR DESCRIPTION
**Pull request by gvanrossum**
Fixes #3253

### CODE REVIEW

**Comment by gvanrossum** [comment]
Before, pytest took a minute, now it takes 45 sec.

**Comment by gvanrossum** [comment]
Another solution might be to set self.cache_dir to os.devnull (or '') in options.py and to change the default to defaults.CACHE_DIR only in main(). Then all tests that bypass main() and instead use build.build() will skip writing the cache, but "real" usage will still write the cache.

**Comment by JukkaL** [comment]
We should also disable writing the cache for fine-grained incremental checking test cases (`diff.test`, `fine-grained.test`, `deps.test` and `merge.test`).

**Comment by gvanrossum** [comment]
OK, how about now?

**Pull request merged**
