### PR TITLE
Push correct enclosing class while deferring a method

### LINKED ISSUE #4069: Class level __getattr__ causes error: __getattr__ is not valid at the module level outside a stub file
After updating to mypy 0.530, I am getting an error on a `__getattr__()` method defined on a class:

```
$ mypy --version
mypy 0.530
$ python3 --version
Python 3.6.3
[~/cretonne/lib/cretonne/meta]
$ cat mypy.ini 
[mypy]
disallow_untyped_defs = True
warn_unused_ignores = True
warn_return_any = True
[~/cretonne/lib/cretonne/meta]
$ mypy cdsl/formats.py
cdsl/formats.py:143: error: __getattr__ is not valid at the module level outside a stub file
```

I don't have any module level `__getattr__()` functions.

This didn't reproduce with a smaller test case, but you can check out the [Cretonne repo](https://github.com/stoklund/cretonne) to reproduce.

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fixes #4069 

This pushes the correct enclosing class while deferring a method instead of just the top class.

A related comment: the name ``active_class`` is a bit misleading, it returns ``None`` from within methods, I think it would be more consistent if ``active_class`` behave the same way as ``self.type`` in semantic analysis, but it is too late to change this, it is already used in several other places with this semantics.

### CODE REVIEW

**Comment by elazarg** [comment]
I think I am to blame for the name `active_class`,  and I agree it's not the best. But the intention is that `active` is  `active scope`, and inside a method there is no active class scope. I don't think it's the same as "the current type".

Can't the issue be resolved by freezing the entire scope, as hinted by the `TODO`?

Anyway, if you are leaving the method `active_class()`, and assigning `enclosing_scope()` to a variable, I think it can't be called `active_class`; it will be confusing.

**Comment by ilevkivskyi** [comment]
> Can't the issue be resolved by freezing the entire scope, as suggested by the ``TODO``?

It is unnecessary, and will only make solution more complex.

> Anyway, if you are leaving the method ``active_class()``, and assigning ``enclosing_scope()`` to a variable, I think it can't be called ``active_class``; it will be confusing.

OK, I renamed this variable, I keep however the named tuple attribute name, ``active_typeinfo``, it makes sense, since the enclosing class for a method becomes the active class when the deferred node rechecking starts.

**Comment by JukkaL** [comment]
Can you fix the merge conflict?

**Comment by ilevkivskyi** [comment]
@JukkaL 
> Can you fix the merge conflict?

Fixed.

**Comment by JukkaL** [comment]
This generates unexpected errors when run against an internal Dropbox codebase. Here is a simplified example:

```py
class A:
    def f(self) -> None:
        def g(x: int) -> int:  # Self argument missing for a non-static method 
                               # (or an invalid type for self)
            return y

y = int()
```

**Comment by ilevkivskyi** [comment]
> This generates unexpected errors when run against an internal Dropbox codebase. Here is a simplified example: ...

Indeed, since the ``active_typeinfo`` is only used by ``bind_self`` and friends, we should only push the _immediate_ enclosing class. Will push a fix in a second.

**Comment by ilevkivskyi** [comment]
@JukkaL Fixed.

**Pull request merged**
