### PR TITLE
Fix generic inheritance for attrs init methods

### PR DESCRIPTION
**Pull request by natemcmaster**
### Description

Fixes https://github.com/python/mypy/issues/5744

Updates the attrs plugin. Instead of directly copying attribute type along the MRO, this first resolves typevar in the context of the subtype.

## Test Plan
Added 4 new test cases to cover various generic inheritance scenarios.

### CODE REVIEW

**Comment by natemcmaster** [comment]
It seems CI is currently broken on this project. There errors in windows builds appear to be a problem with the C++ toolchain, and on Travis, something is broken with setuptools. Not sure how to resolve those errors as they appear unrelated to my proposed changes.

**Comment by gvanrossum** [comment]
Maybe this message on python-dev provides a clue?

https://mail.python.org/archives/list/python-dev@python.org/message/TJE5XWLKRC3EQUXKSHCJNA25H3WGVP5B/

**Comment by JelleZijlstra** [comment]
Looks like pypa/setuptools#2350 (or similar), I'll try to submit a PR using the env var workaround.

**Comment by natemcmaster** [comment]
CI is passing now on this PR. :)

**Comment by natemcmaster** [comment]
Friendly bump for review :)

**Comment by natemcmaster** [comment]
Hello there, checking in again. I merged from master and pushed to my branch to ensure this PR is still merge-conflict free and passing tests. Any chance I can get a review? Thanks!

**Comment by hauntsaninja** [comment]
Thank you again! :-)

**Pull request merged**
