### PR TITLE
Use Furo theme for documentation

### PR DESCRIPTION
**Pull request by 97littleleaf11**
Current readthedoc theme cannot fully utilize the width of browser especially when you are using a wide screen. I am choosing `Furo` since it's quite popular in python community (`pip`, `black`, etc).

Other changes:
* Use `mypy` instead of `Mypy`
* Move introduction to index page, which makes better impression for newcome users.

Closes https://github.com/python/mypy/issues/12374

### CODE REVIEW

**Comment by TH3CHARLie** [comment]
Some screenshots?

**Comment by 97littleleaf11** [comment]
截屏2022-03-14 下午7 23 39

**Comment by jhance** [comment]
I think it looks nice.

**Comment by 97littleleaf11** [comment]
ping @JukkaL

**Comment by 97littleleaf11** [comment]
> Current readthedoc theme cannot fully utilize the width of browser
hmm, actually it's configurable. Anyway I still vote for furo.

**Pull request merged**
