### PR TITLE
stubtest: emit error if a stub defines a public type alias that doesn't exist at runtime

### PR DESCRIPTION
**Pull request by AlexWaygood**
### Description

A followup to https://github.com/python/typeshed/pull/7634#discussion_r851603664

Stubtest currently declines to error if a stub defines a public type alias that doesn't exist at runtime. But it should!

These are the new error reported from running stubtest on the typeshed stdlib, with this patch applied:

```
error: _threading_local.localdict is not present at runtime
Stub: at line 6
Type alias for: builtins.dict
Runtime:
MISSING

error: audioop.AdpcmState is not present at runtime
Stub: at line 3
Type alias for: Tuple[builtins.int, builtins.int]
Runtime:
MISSING

error: audioop.RatecvState is not present at runtime
Stub: at line 4
Type alias for: Tuple[builtins.int, builtins.tuple[Tuple[builtins.int, builtins.int], ...]]
Runtime:
MISSING

error: itertools.Predicate is not present at runtime
Stub: at line 14
Type alias for: def (_T?) -> builtins.object
Runtime:
MISSING

error: sqlite3.dbapi2.OptimizedUnicode is not present at runtime
Stub: at line 413
Type alias for: builtins.str
Runtime:
MISSING
```

They all look like true positives to me (or at least should be allowlisted in typeshed, rather than being ignored by stubtest altogether).

## Test Plan

Two test cases added

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Thanks! I think it can be easier to preserve line numbers... I took the liberty of pushing changes directly to the branch, let me know what you think!

**Comment by AlexWaygood** [comment]
> I think it can be easier to preserve line numbers... I took the liberty of pushing changes directly to the branch, let me know what you think!

Nice, thank you!! That's... much simpler than my method 🤦‍♂️

Just one nit about error messages -- we currently have:

```
Stub: at line 4
Type alias for Tuple[builtins.int, builtins.tuple[Tuple[builtins.int, builtins.int], ...]]
```

I'd much prefer either this, separating the English from the code using a colon:

```
Stub: at line 4
Type alias for: Tuple[builtins.int, builtins.tuple[Tuple[builtins.int, builtins.int], ...]]
```

or this, separating the English from the code using quotation marks:

```
Stub: at line 4
Type alias for "Tuple[builtins.int, builtins.tuple[Tuple[builtins.int, builtins.int], ...]]"
```

What do you think?

**Review by AlexWaygood — COMMENTED** [review]
I approve my own PR

**Comment by AlexWaygood** [comment]
Thanks @hauntsaninja :)

**Pull request merged**
