### PR TITLE
Fix type context for cast()

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
I think this is right, let's see if mypy-primer agrees.

**Comment by hauntsaninja** [comment]
Unit tests agree!

**Comment by JelleZijlstra** [comment]
(#12612 for context)

**Comment by hauntsaninja** [comment]
:-( There's at least some issue involving typeddicts that's genuine. Not immediately obvious to me how to fix. I don't think this is particularly important and it's very annoying for mypy to get things wrong here (since cast is a "please shut up")

**Comment by JelleZijlstra** [comment]
Which one was that? In `kopf` it looked like it found a real issue that was previously hidden by the `Any`  type context.

**Pull request closed without merging**
