### PR TITLE
Now overloads with ambiguous `self` are handled properly

### LINKED ISSUE #11347: Overload ambiguity is ignored in `self`-annotated methods
**Bug Report**

Per the title: mypy does not check for overload ambiguity in `self`-annotated methods.
Mypy will instead, effectively, ignore `self` and then return the first matching overload, 
thus circumventing the usual `Any` that is returned when overload ambiguity is involved.
This has lead to a number of false positives in https://github.com/numpy/numpy/issues/20099 and (in part) https://github.com/numpy/numpy/issues/20072. 

The conditions for triggering this bug are as following:

* The callable is a method (things work fine for functions).
* The method is overloaded.
* `self` must be annotated with a parametrized generic.

**To Reproduce**

``` python
from typing import Any, Generic, overload, TypeVar, TYPE_CHECKING
import numpy as np

_CharType = TypeVar("_CharType", np.str_, np.bytes_)


class CharArray(Generic[_CharType]):
    @overload
    def strip(self: CharArray[np.str_], chars: str = ...) -> CharArray[np.str_]: ...
    @overload
    def strip(self: CharArray[np.bytes_], chars: bytes = ...) -> CharArray[np.bytes_]: ...


ar_any: CharArray[Any]
ar_str: CharArray[np.str_]
ar_bytes: CharArray[np.bytes_]

if TYPE_CHECKING:
    # The good
    reveal_type(ar_str.strip())  # E: Revealed type is "__main__.CharArray[numpy.str_]"
    reveal_type(ar_bytes.strip())  # E: Revealed type is "__main__.CharArray[numpy.bytes_]"

    # The bad
    # "__main__.CharArray[Any]" would be expected here due to overload ambiguity
    reveal_type(ar_any.strip())  # E: Revealed type is "__main__.CharArray[numpy.str_]"

    # Calling the method directly from the class does do the trick
    reveal_type(CharArray.strip(ar_any))  # E: Revealed type is "test.CharArray[Any]"
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: n.a.
- Mypy configuration options from `mypy.ini` (and other config files): n.a.
- Python version used: 3.9.6
- Operating system and version: macOS 11.4

### PR DESCRIPTION
**Pull request by sobolevn**
Closes #11347

### CODE REVIEW

**Comment by BvB93** [comment]
Nice! It seems this PR fixes most of the issues.
One case that does still seem to fail is when `Foo[Any]` subclasses are involved:
``` python
from typing import Generic, TypeVar, overload, Any

T = TypeVar('T')

class Some(Generic[T]):
    @overload
    def method(self: Some[int]) -> bool: ...
    @overload
    def method(self: Some[str]) -> float: ...
    def method(self): pass

class SomeSubtype(Some[Any]):
    pass

s3: Some[Any]
reveal_type(s3.method()) # N: Revealed type is "Any"

s4: SomeSubtype
reveal_type(s4.method())  # N: Revealed type is "builtins.bool"
# Should also be: Revealed type is "Any"
```

**Comment by BvB93** [comment]
Out of curiosity, is there a particular reason why this PR stalled?

**Comment by sobolevn** [comment]
Thanks for re-opening, but since I nuked my fork, I cannot edit or rebase this PR.
I need to do it by hand via CLI. I will at some point!

**Comment by flaeppe** [comment]
> Thanks for re-opening, but since I nuked my fork, I cannot edit or rebase this PR.
I need to do it by hand via CLI. I will at some point!

@sobolevn just wanted to hint that it's quite quickly to get hold the contents here in order to e.g. rebase. Should only be a few lines:

e.g.

```
git fetch origin pull/11366/head:issue-11347
git switch issue-11347
git rebase --onto origin/master 4d0ab445514e0f9795306c0bc88a202be209df6b issue-11347
...
```

Make sure to just swap out to your correct remote name and what branch name you'd like

Taken from: [Modifying an inactive pull request locally](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally)

**Comment by sobolevn** [comment]
@flaeppe feel free to take over this PR. I lost context of it :)

**Pull request closed without merging**
