### PR TITLE
multi-platform mypy

### PR DESCRIPTION
**Pull request by KotlinIsland**
### Have you read the [Contributing Guidelines](https://github.com/python/mypy/blob/master/CONTRIBUTING.md)?

(Once you have, delete this section. If you leave it in, your PR may be closed without action.)

### Description

(Explain how this PR changes mypy.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

relates: #12286

### CODE REVIEW

**Comment by jhance** [comment]
Are you missing a git add?

**Comment by KotlinIsland** [comment]
Nah, I just wanted to steal #12345 and then work on it later 😁

**Comment by 97littleleaf11** [comment]
FYI Jukka wrote some notes long time ago https://github.com/python/mypy/issues/933

**Comment by KotlinIsland** [comment]
Yeah, sorry, this is regarding #12286

**Comment by jhance** [comment]
I don't think #933 is as related, it seems to be about having multiple processes processing a single configuration using some sort of queue to communicate.

**Comment by hauntsaninja** [comment]
It's a nice PR number, so feel free to re-open if there's something you'd like to do with it :-)

**Pull request closed without merging**
