### PR TITLE
Allow isinstance checks of TypedDict from the typing module

### PR DESCRIPTION
**Pull request by rowillia**
This fixes https://github.com/python/mypy/issues/2614

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
I think this is the right way to fix this for now. If ``TypedDict`` will become a part of ``typing`` at some point, then ``Union`` constructor could be updated with an additional guard for ``issubclass`` check.

Only one small comment, I would add more tests:
```python
        self.assertEqual(typing.Optional[Emp], typing.Union[None, Emp])
        self.assertEqual(typing.ClassVar[Emp], typing.ClassVar[Emp])
        self.assertNotEqual(typing.List[Emp], typing.Tuple[Emp, ...])
```
to be sure that other special ``typing`` constructs work nice with ``TypedDict``.

**Comment by rowillia** [comment]
Thanks for the feedback @ilevkivskyi .  Added more test cases.

**Comment by gvanrossum** [comment]
Thanks! (Though did you want to add the `ClassVar` test case?)

**Comment by ilevkivskyi** [comment]
My experience with ``typing`` is that there are never to many tests. ``ClassVar`` is a bit different from other types (for example ``List[ClassVar[T]]`` is invalid), this is why I initially proposed to add it. But this is not critical, if more bugs will be discovered, then we could add more tests.

**Pull request merged**
