### PR TITLE
Add a note on variable annotation within unchecked function

### LINKED ISSUE #3948: Give an error if there is a variable annotation within a function but no signature
Mypy should perhaps give an error about a variable annotation in an otherwise unanotated function. Example:

```py
def f():
    a: int = 'x'   # Maybe this annotation should be an error?
```

The rationale is that mypy will ignore the type annotation since the function is still considered unannotated, but this is confusing because there is an annotation *within* the function so it can appear to be annotated.

If `--check-untyped-defs` is being used this error shouldn't be generated.

Originally reported in #3945.

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Closes #3948

This however gives a note instead of an error, so that type checking result will be success. I also added an error code for the note so that people can opt-out if they want to.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
The fallout is quite big, but it is expected (also this will not break CI). I went through some of the notes, they all look correct.

**Review by AlexWaygood — APPROVED** [review]
This looks great. I think it's going to help a lot of people. Haven't checked through mypy_primer, but I trust you've done a thorough review :)

**Review by JelleZijlstra — APPROVED** [review]

**Comment by cdce8p** [comment]
> The fallout is quite big, but it is expected (also this will not break CI).

Just so you're aware, this **`will`** break CI. With just a note, mypy will exit with code `1`.
https://github.com/python/mypy/blob/1eaf4c70c0b83c3f0f639e3c53daaf3872bea5b0/mypy/main.py#L112-L114

```py
def func():
    var: list[str] = []
```

```bash
$ mypy test.py
test.py:2: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs
Success: no issues found in 1 source file

$ echo $?
1
```

**Comment by ilevkivskyi** [comment]
Hm, I think we may need to change this. Returning 1 after showing `Success` message is especially weird.

**Comment by ilevkivskyi** [comment]
@cdce8p FYI https://github.com/python/mypy/pull/13879

**Pull request merged**
