### PR TITLE
Remove deprecated options

### PR DESCRIPTION
**Pull request by gvanrossum**
These will now all fail with `unrecognized arguments: <flag>`
```
--disallow-any (message points to options replacing it)
-f/--dirty-stubs (ignored)
--use-python-path (exited with error message)
-s/--silent-imports (set ignore_missing_imports=True and follow_imports=skip)
--almost-silent (ses follow_imports=error)
--[no-]fast-parser (ignored)
--strict-boolean (actually did something, though questionable)
```
I've put the removal of `--strict-boolean` in a separate commit since it's more controversial -- some people might still be using it, even though it's been deprecated since May 2017.  See discussion in https://github.com/python/mypy/issues/3195.

### CODE REVIEW

**Comment by Michael0x2a** [comment]
Regarding the strict-boolean flag -- maybe one idea might be to move that sort of logic into a separate plugin that's independent from mypy.

I've been vaguely thinking about doing this myself, actually -- I can never remember what's supposed to be truthy or falsey from language to language, so most of my personal code is written in a style where this sort of plugin would actually be mildly useful/not very noisy. I'm not sure if our plugin system would support these kinds of extensions yet though.

**Comment by gvanrossum** [comment]
I don't think the plugin system could do that unless there was a way to
request being called for every expression.

**Comment by ethanhs** [comment]
Hm, it seems I did the wrong thing trying to make flake8 happy. Sorry!

**Comment by gvanrossum** [comment]
No worries, I'll fix it.

**Pull request merged**
