### PR TITLE
infer types from explicitly-typed base if not explicitly typed

### LINKED ISSUE #12268: Incorrect type inference in Derived class that was explicitly typed in Base
I think this might be best explained with an example.

```py
from typing import Union, List

class A: pass
class B: pass

class Base:
    variable1 : List[Union[A, B]] = []
    variable2 : List[Union[A, B]] = []

class Derived(Base):
    variable1 = [A()]
    variable2 = variable1
```

Here is the output of `mypy test.py`: 

```
test.py:12: error: Incompatible types in assignment (expression has type "List[A]", base class "Base" defined the type as "List[Union[A, B]]")
test.py:12: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
test.py:12: note: Consider using "Sequence" instead, which is covariant
Found 1 error in 1 file (checked 1 source file)
```

The error is on the last line. The complaint is that `variable1` is of type `List[A]`, and so it cannot be assigned to `variable2`. At first, this seems reasonable, but notice that the type of `variable1` is explicitly defined to be `List[Union[A, B]]` in the superclass. More interesting still is that the previous line, line 11, is accepted just fine.

I believe Derived types should inherit their superclass types if possible before resorting to a type inference.

Debug information:

```
MyPy Version: 0.931
Python Version: 3.9.2
Operating System: Debian 11
Linux Version: 5.14
```

And also a [real world example](https://github.com/DMOJ/judge-server/pull/1009) of this.

### PR DESCRIPTION
**Pull request by Riolku**
Fixes #12268. If the type of an lvalue is not given at definition time, attempt to infer it from the type of a base member.

### CODE REVIEW

**Comment by Riolku** [comment]
Obviously it's clear from the diff that I've modified the output for one of the tests. I looked into when it was created: #5670. This references partial types. However, (and please forgive me if I'm wrong, as it's my first time contributing) I believe Partial types are those that have something to do with `None`, not `[]`. Since this PR uses parent types as a fallback if forced to infer, that test necessarily fails. But what does it test?

**Comment by Riolku** [comment]
After looking at the sheer volume of the mypy_primer diff, I think I should take a different approach. For instance, consider the following:

```py
class A:
  x = SuperType()

class B(A):
  x = DerivedType()
```
I think it's more reasonable to expect that `B.x` is of type `DerivedType`, rather than `SuperType`. I think an ideal PR would look more like "If the base class is explicitly typed, use it", rather than the current, which always takes it if it has to infer.

**Comment by Riolku** [comment]
Hopefully this will do it. This also means I reverted the change to the test I mentioned.

**Comment by Riolku** [comment]
```py
class Storage:
  PATH_BACKEND: Type[pathlib.Path] = pathlib.Path

class SwiftStorage:
  PATH_BACKEND = SwiftPath
  ```
  
This is very reasonable code, and I want this to be reasonable. Something else needs to change.

**Comment by JelleZijlstra** [comment]
In the freqtrade case, is `Column` a descriptor that returns `str` on access? Perhaps that's something we can handle better.

And the SwiftPath case seems like a real error if SwiftPath is not a subclass of Path.

**Comment by Riolku** [comment]
I think that's sqlalchemy code, but that accessing that property only returns a string when `self` is defined, because it's a Model (I think). `SwiftPath` is a subclass of Path.

**Comment by Riolku** [comment]
By which I mean it only returns a string in the context of a non-static method or the like. That's what I recall from that library anyway,

**Comment by Riolku** [comment]
I think the `freqtrade` case should throw, and honestly I'm rather confused as to why it doesn't, but I don't think this is the right way to fix it.

**Comment by JelleZijlstra** [comment]
mypy isn't very strict about class/instance attributes working the same way in base and child classes I believe.

**Comment by JelleZijlstra** [comment]
I'm not excited about it; it will technically fix some type safety issues but in practice I suspect it will likely mostly generate busywork. We'd probably have to come up with a generic way to say "instance-only attribute", which currently doesn't exist.

**Pull request closed without merging**
