### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by hauntsaninja**
Source commit:
https://github.com/python/typeshed/commit/91d6383d9d1ca38157ce46bb498a11347658db1d

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
@hauntsaninja We want to use this sync for internal mypy release. Could you please check the output of `mypy_primer`, are the new errors correct/reasonable? Especially the one with `AnyStr` (I wanted to check myself, but may not have time today).

**Comment by hauntsaninja** [comment]
The ones in aiohttp / homeassistant (core) are false positives:
https://github.com/python/typeshed/pull/7725#issuecomment-1141166900
Pretty sure this is also what's causing the porcupine examples (although weirdly it doesn't show up in primer on the typeshed PR and porcupine hasn't made any recent changes)

boostedblob change looks intentional:
https://github.com/python/typeshed/pull/7844

manticore is also a false positive, but hard to fix:
https://github.com/python/typeshed/pull/7939#issuecomment-1136752189

streamlit is just a change in diagnostics

The one in optuna is intentional (although not sure that I'd have made the same change):
https://github.com/python/typeshed/pull/7938

**Comment by hauntsaninja** [comment]
Since we don't have proper support for LiteralString, https://github.com/python/typeshed/pull/7725 doesn't get us anything. If it's blocking a release, you could temporarily revert that.

Here are minimal reproducers:
```
from typing import Any, AnyStr

def escape(pattern: AnyStr) -> AnyStr: ...
CHAR: set[str] = {"x"}
"".join(map(escape, CHAR))

def sonos(channel: str | None, radio_show: Any):
    " • ".join(filter(None, [channel, radio_show]))
```

**Comment by AlexWaygood** [comment]
FYI you might want to cherry-pick https://github.com/python/typeshed/pull/8137 after merging this, since this sync contains the following regression: https://github.com/python/typeshed/issues/8136.

**Comment by ilevkivskyi** [comment]
I am going to merge this PR as is, and will separately fix small issues/regressions in separate PRs.

**Pull request merged**
