### PR TITLE
Use attrs and @attrs.define in tests

### PR DESCRIPTION
**Pull request by ikonst**
"attrs" namespace, "attrs.define" and "attrs.field" are the recommended new namespace and API of the attrs library (see https://www.attrs.org/en/stable/names.html) so we should modernize the bulk of our tests to use the current API.

### CODE REVIEW

**Comment by ikonst** [comment]
👋 @JelleZijlstra

**Comment by JelleZijlstra** [comment]
Are there any tests that specifically check that we still support the old names?

**Comment by ikonst** [comment]
Good call @JelleZijlstra, I meant to do it and forgot 😅 

e5d8da067c5f8599938a84ffd39725167e1fb564 replaces `testAttrsNewPackage` with `testAttrsOldPackage`.

**Review by JelleZijlstra — APPROVED** [review]
Thanks! Will merge when CI passes, feel free to ping me if I forget.

**Pull request merged**
