### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Source commit:
https://github.com/python/typeshed/commit/5397d430ea306787fe46903123aa24ef2838c37b

This version doesn't have Python 2 anymore.

Ref #12237 

cc @hauntsaninja @sobolevn

### CODE REVIEW

**Comment by hauntsaninja** [comment]
You'll probably need to cherry pick https://github.com/python/mypy/pull/13093 again

**Comment by ilevkivskyi** [comment]
@hauntsaninja Oh, right. I will CP now.

**Comment by AlexWaygood** [comment]
N.B. This version of typeshed also drops support for 3.6, so you may also have to reapply https://github.com/python/mypy/commit/d22899f2166c1adeb9daf0326cc068beca4f7bb9 to fix the CI

**Comment by ilevkivskyi** [comment]
@AlexWaygood Oh, great, I thought I would need top fix it myself :-)

**Comment by AlexWaygood** [comment]
Also FYI the main culprits for the primer diff are:

- https://github.com/python/typeshed/pull/8293 (this one also causes a few mypy tests to fail, but I personally think it's for the best :-)
- https://github.com/python/typeshed/pull/8057
- https://github.com/python/typeshed/pull/8386

**Review by hauntsaninja — APPROVED** [review]

**Comment by ilevkivskyi** [comment]
@AlexWaygood do you understand the couple new `Cannot determine type of "__add__"` errors in the primer? This looks like some kind of a bug to me.

**Comment by AlexWaygood** [comment]
> @AlexWaygood do you understand the couple new `Cannot determine type of "__add__"` errors in the primer? This looks like some kind of a bug to me.

Yeah, it's a regression, caused by the fact that `list.__add__` is now an overloaded function. We discussed it a bit in https://github.com/python/typeshed/pull/8293#issuecomment-1183744049 — our judgement was that the typeshed change fixed enough bugs that it was worth paying the price of the regression. But obviously the best of all worlds would be if we could find a fix for the regression on the mypy side as well :)

**Pull request merged**
