### PR TITLE
Update typeshed

### PR DESCRIPTION
**Pull request by sixolet**

### CODE REVIEW

**Comment by gvanrossum** [comment]
I have no idea what you did here, but it doesn't sound right. Normally when you do "git submodule update" the diff comes out as a one-line change to a commit hash in a "file" named typeshed. See every other diff with commit message "sync typeshed".

**Comment by JukkaL** [comment]
I wonder if this is just a new github UI feature that shows changes in the typeshed repo?

**Comment by gvanrossum** [comment]
OK, I'll see if this works with our internal codebases and if so merge it.

**Comment by gvanrossum** [comment]
There's one problem due to #726, otherwise it's clean. I'm looking into it.

**Comment by gvanrossum** [comment]
It's because FrozenSet should be covariant. I'm doing that in https://github.com/python/typeshed/pull/769.

**Comment by gvanrossum** [comment]
I'm going to make a new PR to sync to the latest typeshed and merge that.

**Pull request closed without merging**
