### PR TITLE
Add MegaLinter in list of integrations

### PR DESCRIPTION
**Pull request by nvuillam**
Add [MegaLinter](https://megalinter.github.io/latest/) in the list of integrations :)

https://megalinter.github.io/latest/descriptors/python_mypy/

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Thank you, but I prefer not merging these kinds of self-advertising-y PRs. MegaLinter is not an IDE, which is what this section is primarily about. Also fwiw, in my experience tools that wrap mypy usually just end up causing headaches for mypy maintainers.

**Comment by nvuillam** [comment]
MegaLinter is not an IDE but a growing CI tool, and I don't see how it could cause you headaches, but indeed your rep = your choice, thanks for the reply :)

**Comment by JelleZijlstra** [comment]
You did put it in a section labeled "popular IDEs" :)

**Comment by nvuillam** [comment]
> You did put it in a section labeled "popular IDEs" :)

Under pre-commit which is not an IDE, my bad ^^

**Pull request closed without merging**
