### PR TITLE
Fixes RTD

### LINKED ISSUE #11412: mypy ReadTheDocs build is failing
See https://readthedocs.org/projects/mypy/builds/

It looks like this is related to https://github.com/sphinx-doc/sphinx/issues/9777 , in which case the quickest resolution is probably just pinning some package versions.

However, it looks like the ReadTheDocs build its own instructions that are unrelated to `tox -e docs` / the versions specified in the mypy repo. I'm not really familiar with RTD — where are its build steps coming from and who has permission to change it?

### PR DESCRIPTION
**Pull request by sobolevn**
It passes locally:

```
» make html         
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v4.2.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://six.readthedocs.io/objects.inv...
loading intersphinx inventory from http://www.attrs.org/en/stable/objects.inv...
loading intersphinx inventory from http://docs.cython.org/en/latest/objects.inv...
loading intersphinx inventory from https://monkeytype.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://setuptools.readthedocs.io/en/latest/objects.inv...
intersphinx inventory has moved: http://www.attrs.org/en/stable/objects.inv -> https://www.attrs.org/en/stable/objects.inv
intersphinx inventory has moved: https://setuptools.readthedocs.io/en/latest/objects.inv -> https://setuptools.pypa.io/en/latest/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 37 source files that are out of date
updating environment: [new config] 37 added, 0 changed, 0 removed
reading sources... [100%] type_narrowing                                              
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] type_narrowing                                               
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.
```

Closes #11412

We can also enable "build PR branches" on RTD, if it is not enabled right now.

Checkbox:
Снимок экрана 2021-10-31 в 21 08 55

Docs: https://docs.readthedocs.io/en/stable/pull-requests.html and https://docs.readthedocs.io/en/stable/development/design/pr-builder.html

I cannot do that myself 🙂

### CODE REVIEW

**Review by hauntsaninja — CHANGES_REQUESTED** [review]
Thanks, can we make switch this to use `docs/requirements-docs.txt`? I don't have the permission to change the RTD to run on PR, but that should be fine since we ensure docs build with https://github.com/python/mypy/blob/3f43c830f37489045ef8fd8e21d232aef42b28ef/.github/workflows/docs.yml#L19

**Comment by sobolevn** [comment]
@hauntsaninja oh, I was not aware of this file. Done!

By the way, thanks a lot for reviewing / merging so many PRs! It made me happy 👏

**Review by hauntsaninja — APPROVED** [review]
Thanks! I suspect the command that gets run will be slightly different from `tox -e docs` and whatever RTD does right now, but maybe we just try this and see what happens

**Comment by sobolevn** [comment]
Looks like it worked! https://readthedocs.org/projects/mypy/builds/15143406/

**Pull request merged**
