### PR TITLE
stubgen: Allow aliases below the top level

### PR DESCRIPTION
**Pull request by chadrik**
(Explain how this PR changes mypy.)

stubgen currently allows a variable to be an alias to another, but only at the module level.

For example: 

```python
def func() -> int:
    return 2

aliased_func = func

class Foo:
    def meth() -> int:
        return 2
    
    aliased_meth = meth
```

produces:

```python
def func() -> int: ...
aliased_func = func

class Foo:
    def meth() -> int: ...
    aliased_meth: Incomplete   # <--- should be  `aliased_meth = meth`
```

At the class level, these aliased variables are marked as `Incomplete`.   

In my experience, enabling aliases below the top level produces better stubs.  

I'm not sure what the original reservations were around use of these aliases.  If the concerns about class-level aliases are still valid, I can add an option to enable them.

### CODE REVIEW

**Comment by chadrik** [comment]
@hauntsaninja do you mind giving this a review?

**Comment by chadrik** [comment]
Anyone have a minute for this PR?

**Review by hauntsaninja — COMMENTED** [review]
Thanks, this looks reasonable.

Can we just make this the default and not have it be configurable? Could you also add some assignment statements inside methods in the test case to prove that they don't get included.

**Comment by chadrik** [comment]
> Can we just make this the default and not have it be configurable?

I was inclined to do that, but I don't know why it was specifically limited to module aliases in the first place.  I can't see the scenario where that's preferable.  I'm happy to delegate that decision to you or anyone else in the mypy crew. 

> Could you also add some assignment statements inside methods in the test case to prove that they don't get included.

sure.

**Comment by hauntsaninja** [comment]
Let's make it the default

**Comment by chadrik** [comment]
ready to go!

**Review by hauntsaninja — APPROVED** [review]
Thanks!

**Pull request merged**
