### PR TITLE
[docs]: fix the edit page buttton link in docs

### PR DESCRIPTION
**Pull request by Mr-Sunglasses**
(Explain how this PR changes mypy.)

fix: #17870 

# Issue
The current docs `edit` the page button gives a 404.

# What changes this PR does
This PR edits the sphinx `config.py` and configures the edit button url to the `master` branch of this repository.

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Hm, I couldn't find a reference for these options. Is there one?

**Comment by Mr-Sunglasses** [comment]
> Hm, I couldn't find a reference for these options. Is there one?

Yeah, I take the reference from cpython devguide repo [here](https://github.com/python/devguide/blob/6a2a0227e1681ae3510c05b351664e3f64767624/conf.py#L39)

**Review by hauntsaninja — APPROVED** [review]
Thanks for the fix and the link! :-)

**Comment by Mr-Sunglasses** [comment]
@hauntsaninja Quick question about how the docs are currently working after the recent PR merge. The current behavior of the docs site is as follows:

When we view the latest branch, the "Edit" button is visible. This happens because Sphinx uses the GitHub repository link combined with the branch name to allow editing the specific source file of the documentation.

Screenshot 2024-10-15 at 2 24 58 AM

However, when we switch to the stable branch, the "Edit" button disappears. This is expected behavior with Sphinx since the stable docs are released using tags, and tagged releases aren't associated with branches that can be directly edited.


Screenshot 2024-10-15 at 2 25 06 AM

IMO, we need to further discuss whether this is the behavior we want or if we need to consider changing how we deploy our docs.

**Comment by hauntsaninja** [comment]
Feel free to open an issue or more PRs if you have some improvements you'd like to make! :-)
I'm not particularly knowledgeable about sphinx / rtd, so don't have any opinions

**Pull request merged**
