### PR TITLE
Add support for additional type aliases from collections

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This implements https://github.com/python/typing/pull/366 in mypy. 

I didn't add detailed tests for these since there's little specific
to these classes in mypy's code. I can add more detailed tests
like those for defaultdict if that is preferred.

This PR depends on these two typeshed PRs **[Update: both merged]**:
- https://github.com/python/typeshed/pull/929
- https://github.com/python/typeshed/pull/928

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
@JelleZijlstra Thanks! I don't think many additional test are needed, maybe just few tests showing errors (like ``Counter[int]()['a']``) plus maybe a separate test showing that ``ChainMap[int, str]`` errors if it was not imported.

**Comment by gvanrossum** [comment]
I guess I'll have to sync typeshed first, then you can merge that into this PR, and *then* the tests ought to pass and it can be merged.

**Comment by gvanrossum** [comment]
Done. Can you merge from master and re-push?

**Comment by JelleZijlstra** [comment]
Done. Thanks for taking care of the sync!

**Comment by ilevkivskyi** [comment]
@JukkaL @ddfisher This PR is no more blocked (typeshed id synced and all tests pass). I believe it could be merged now.

**Comment by rhettinger** [comment]
I've tested this patch on my own code and it works fine.  I think it is ready to apply.

**Comment by gvanrossum** [comment]
OK, merged. Sorry for the delay, I'm still dealing with health issues and not my usual responsive self.

**Comment by JelleZijlstra** [comment]
Thanks! No hurry.

**Pull request merged**
