### PR TITLE
Use polymorphic inference in unification

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Moving towards https://github.com/python/mypy/issues/15907
Fixes https://github.com/python/mypy/issues/17206

This PR enables polymorphic inference during unification. This will allow us to handle even more tricky situations involving generic higher-order functions (see a random example I added in tests). Implementation is mostly straightforward, few notes:
* This uncovered another issue with unions in solver, unfortunately current constraint inference algorithm can sometimes infer weird constraints like `T <: Union[T, int]`, that later confuse the solver.
* This uncovered another possible type variable clash scenario that was not handled properly. In overloaded generic function, each overload should have a different namespace for type variables (currently they all just get function name). I use `module.some_func#0` etc. for overloads namespaces instead.
* Another thing with overloads is that the switch caused unsafe overlap check to change: after some back and forth I am keeping it mostly the same to avoid possible regressions (unfortunately this requires some extra refreshing of type variables).
* This makes another `ParamSpec` crash to happen more often so I fix it in this same PR.
* Finally this uncovered a bug in handling of overloaded `__init__()` that I am fixing here as well.

Let's see `mypy_primer` will show us.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
Hm, it looks like this makes https://github.com/python/mypy/issues/17206 (`RuntimeError: Parameters cannot be constrained to` during unification) to occur much more often. I will take a look (and probably at the original report as well).

**Comment by ilevkivskyi** [comment]
I also spot-checked new errors and it looks like these are false positives. It looks like they are all caused by the same pattern. I think I know how to fix it, but it is non-trivial, so will do it tomorrow.

**Comment by ilevkivskyi** [comment]
@JukkaL @hauntsaninja I am now happy with mypy_primer output, this is ready for review.

**Review by JukkaL — APPROVED** [review]
Looks good. This makes type inference more powerful and consistent, and it's nice that you were able to fix a bunch of other issues along the way.

**Pull request merged**
