### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by JukkaL**
Source commit:
https://github.com/python/typeshed/commit/fbb89f9fd54566e292a63b80cb32053bd6eb1bb4

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by hauntsaninja** [comment]
Test failures aside, this also includes https://github.com/python/typeshed/pull/6221 which as things currently stand would be a bit of a regression for mypy users

**Comment by JukkaL** [comment]
> which as things currently stand would be a bit of a regression for mypy users

I'd rather avoid the regression. We could work around this using a plugin, but that's not very principled.

 I'm going to instead look at adding support for `ParamSpec` (at least at a basic level) before we do the typeshed sync. It doesn't look *too* difficult to support.

**Comment by JukkaL** [comment]
> I'm going to instead look at adding support for ParamSpec (at least at a basic level) before we do the typeshed sync. 

I did some prototyping and real `ParamSpec` support looks fairly easy so far. cc @hauntsaninja

**Comment by hauntsaninja** [comment]
Nice! Yeah, in particular the basic "change the callable return type" needed for this PR should be quite easy to knock out. I think I have a version of that on a branch, and then I got distracted and started refactoring type variables and fixing generic leakage.

**Comment by JukkaL** [comment]
Cool! I'll try to prepare a PR that implements basic `ParamSpec` functionality in a "rough and ready" manner soon to unblock `ParamSpec` usage in typeshed.

**Comment by JukkaL** [comment]
I'm going to create another PR based on a more recent typeshed commit.

**Pull request closed without merging**
