### PR TITLE
Delete sametypes.py

### LINKED ISSUE #7924: Should we remove sametypes.py?
There are two ways we can compare types for being the same:
* Semantic identity, this is what is done by `is_equivalent()` that just checks `A <: B and B <: A`. This affects semantics of types in the user code being checked.
* Representation identity, this is what is currently done by `Type.__eq__()` and `Type.__hash__()`. This affects internal bookkeeping, caching, etc.

Currently, `is_same_types()` stays somewhere in the middle, it doesn't take into account some subtype relationships (including protocols and recursive type aliases), but it also "takes into account" `make_simplified_union()`.

I could see how this can be a minor performance optimization for equivalence with respect to proper subtyping, but IMO this kind of middle ground position increases chance for confusion and bugs. I would propose to remove it and instead use `==` and `is_equivalent()`.

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fixes #7924

So this is not 100% refactor, I make several semantic changes. As discussed in the issue, current implementation is not very principled, so I replace old complex logic with two options:
* New `is_same_types()` is now located in `subtypes.py` and is doing two-way proper subtyping check.
* Type equality with `==` can be used when we are checking for representation equality (used rarely, mostly for internal things)

Btw this uncovered two actual bugs, one of which I fix here (two-line change), and leave a TODO for the second. Let's keep fingers crossed for `mypy_primer`.

cc @JukkaL

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
@hauntsaninja @JelleZijlstra could one of you (or both) please take a look at this one as well?

**Comment by ilevkivskyi** [comment]
OK, so `mypy_primer` us expected, I effectively slightly relaxed rules for `--warn-redundant-casts`, and slightly enforced them them for `assert_type()`. I used this as a rule of thumb when deciding whether to switch to `==`: do I want `int` and `int64` be different under this check? (They are proper subtypes of each other, but have different runtime representation.)

**Review by hauntsaninja — APPROVED** [review]

**Comment by ilevkivskyi** [comment]
@JukkaL After some thinking, I decided to use `ignore_promotions=True` for the new implementation of `is_same_type()`, so e.g. `int` and `int64` will be different and `Union[int, bool]` (if not simplified) will be different from `int`. This is somewhat closer to old behavior, although there is no difference in tests and in `mypy_primer`.

I went again through all call sites (there is just a dozen or so), and I think the semantics introduced by this PR makes sense there.
I remember you was quite cautious about this change few years ago. But with `mypy_primer` I am more confident now. If you are still against, please let me know, otherwise I will merge this soon.

**Comment by ilevkivskyi** [comment]
After working a bit on cleaning `get_proper_type()` usage, I think I will use `is_same_type()` in `assert_type()` (like it was before). Having `==` there will be a big pain for users if type is recursive alias.

**Pull request merged**
