### PR TITLE
Use level "note" for reveal_type and reveal_locals

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/python/mypy/issues/6901.

TODO:

- [x] indentation with `reveal_locals`

### CODE REVIEW

**Comment by blueyed** [comment]
Great.

> so I think this requires approval from most of core team members.

Ok, no hurry - I can see that this might cause trouble with pending PRs etc.

**Comment by blueyed** [comment]
> * indentation with `reveal_locals`

As for this: do you think prepending " - " is good here?

**Comment by ilevkivskyi** [comment]
> As for this: do you think prepending " - " is good here?

I think just four spaces offset is enough (like in protocol error message notes)

**Comment by blueyed** [comment]
Ok, updated and rebased.

**Comment by msullivan** [comment]
Sure! If you rebase it again I'll merge it.

**Comment by blueyed** [comment]
@msullivan 
Ok, hope it stays green.

**Pull request merged**
