### PR TITLE
[mypyc] Add bytes primitive type

### PR DESCRIPTION
**Pull request by JukkaL**
This adds minimal support for the `bytes` primitive type. This won't 
improve performance until we implement some more primitives.
Actually, this will likely degrade performance a bit, since we now add 
type checks for `bytes` values.

Unfortunately, most of the `bytes` operations we'd need are private in 
CPython, so we'll need to either depend on implementation details or
reimplement (or copy+paste) a bunch of code.

Work on mypyc/mypyc#644.

### CODE REVIEW

**Review by msullivan — APPROVED** [review]

**Comment by JukkaL** [comment]
There were various test failures because of a bad annotation in `typed_ast` stubs. It should be fixed now.

**Comment by hauntsaninja** [comment]
The match group thing keeps coming up, I'm in favour of a Union Any return (with maybe some overloads for when we don't need it): https://github.com/python/typeshed/issues/3902#issuecomment-628332769

**Comment by TH3CHARLie** [comment]
What's the status quo of the match group thing? Is it still a blocker of this?

**Comment by JukkaL** [comment]
I think that it's still an issue. I kind of forgot about this PR. The typeshed fix should be fairly straightforward (but it needs to be synced back to mypy).

**Comment by JelleZijlstra** [comment]
`group` was already changed to return `AnyStr | Any`: https://github.com/python/typeshed/blob/master/stdlib/typing.pyi#L568

**Comment by 97littleleaf11** [comment]
Hi! @hauntsaninja, I'm working on bytes primitives, shall we sync the typeshed to fix current match.group issue?

**Comment by hauntsaninja** [comment]
Sure, I opened https://github.com/python/mypy/pull/10862
If you're planning on building upon this PR, it'll need a merge

**Comment by JukkaL** [comment]
Closing in favor of #10881.

**Pull request closed without merging**
