### PR TITLE
Rename --disallow-untyped-defs to --disallow-any=unannotated

### PR DESCRIPTION
**Pull request by ilinum**
Previously, we were talking about naming this flag was `--disallow-any=untyped`. However, I think it's not clear without knowing the old name of the flag (`--disallow-untyped-defs`). 

Naming suggestions are very welcome!

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Honestly I prefer the old name; I find it much easier to understand what it does, because I don't have to think about the fact that unannotated defs implicitly use Any.

**Comment by gvanrossum** [comment]
I'm with Jelle. I know Stas wants to use the new flag style. Let's have the old and the new name together for a while -- personally I expect that we haven't come up with the best API for these checks.

**Comment by ilinum** [comment]
I definitely see your point: `--disallow-untyped-defs` is more understandable than `--disallow-any=unannotated`

However, the idea behind `--disallow-any` option is to have one way to control all `Any`s in your code and we should have some way of disallowing untyped defs with the new flag. 

That being said, I'm okay with the idea of having both of them co-exist.

**Comment by gvanrossum** [comment]
OK, please do that.

**Comment by ilinum** [comment]
@ddfisher this PR is ready for review.

**Pull request merged**
