### PR TITLE
Allow using __getitem__ defined in metaclasses of non-generic classes

### LINKED ISSUE #1771: Mypy doesn't recognize metaclass implementing __getitem__
Suppose we have an `Enum` called `MyEnum`, and we try something like `MyEnum["foo"]`, mypy will give us an error `Value of type "MyEnum" is not indexable`. We believe this is because mypy has trouble recognizing when a metaclass implements `__getitem__`.

A workaround is to do `getattr(MyEnum, "foo")`, but it'd be nice to have an actual fix.

### PR DESCRIPTION
**Pull request by elazarg**
Fix #1771. (Seems to be much simpler than I thought)

In particular, this will allow removing some special-casing for enum (#2812).

Related to #1381.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Nice. Can you also add the removal of those parts of #2812 that are no longer needed? (But keep the tests, obviously.)

**Comment by elazarg** [comment]
The problematic part in this PR is the reduced clarity in error messages, as can be seen in the (currently failing) tests. What do you think about it?

**Comment by elazarg** [comment]
Perhaps it'd be better to do it in another PR.

**Comment by gvanrossum** [comment]
Seeing all that, it may be better to split this out:

1. Reduce PR to *just* your initial commit
2. Update typeshed with an `EnumMeta` metaclass that supports `__getitem__` (it won't be activated yet because the code from #2812 overrides it)
3. Roll back #2812 (but keeping its tests)

You should be able to co-develop (2) and (3) and submit them concurrently, with a dependency on merging so that (2) gets merged first but only once you know that the tests for (3) pass with that included. The PR for (3) should be updated at the last moment with a typeshed sync that incorporates (2).

Does that make sense?

**Comment by gvanrossum** [comment]
Regarding the poorer error message: it would be so much better if the way types are rendered distinguished between `Type[X]` and `X`. Currently it seems `Type[int]` and `int` are both rendered as `Value of type "int"`.

**Comment by elazarg** [comment]
(Sorry I rewrote history. Another git accident there)

**Comment by gvanrossum** [comment]
What if the indexed class is e.g. Type[...], Or a type var bounded by such a thing? Or has a bound that is a metaclass?

**Comment by elazarg** [comment]
`Type[...]` will be printed as "A value of type Type[...]".
The `TypeVar` case seems not to be handled at all - it evaluated to `Any` silently. Currently it is ignored in `semanal.py`, but handling it there does not fix the problem.

I am a bit hesitant about changing the pretty-printing since it might affect many tests.

(I am sorry but I do not have enough time right now, and I will not be available at all in the upcoming week).

**Comment by gvanrossum** [comment]
OK, will merge as-is.

**Pull request merged**
