### PR TITLE
Removal of section regarding comparison between mypy and PyPy

### PR DESCRIPTION
**Pull request by a4ff7810**
(Hopefully) clarified and corrected the section on how mypy differs from PyPy.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Honestly I think we should just delete the question about PyPy. It probably stems from the time when mypy actually transpiled your code and ran it. I've never heard from anyone who was confused between the two in the past 2-3 years.

**Comment by JukkaL** [comment]
Yes, the comparison really makes no sense any more and can be deleted.

**Comment by gvanrossum** [comment]
Thanks!

**Comment by a4ff7810** [comment]
Not at all :). Happy to help, even if it's just with the smallest bits and bobs. Thank _you_ and everybody else for your amazing and continued efforts.

**Pull request merged**
