### PR TITLE
MyPy Exception Type Error Message Update

### LINKED ISSUE #5349: except handler type error should admit the possibility of tuples
```
$ mypy --version
mypy 0.610
$ cat exception.py
def f() -> None:
    excs = [IOError, LookupError]
    try:
        pass
    except excs:
        pass
$ mypy exception.py 
exception.py:5: error: Exception type must be derived from BaseException
```
While it's true that this code is incorrect, I probably want to fix it by writing `excs = (IOError, LookupError)` rather than somehow making my list a subclass of `BaseException`.

### PR DESCRIPTION
**Pull request by ajrpeggio**
Fixes #5349 - Updating Error Messaging for Invalid Exception Type

### CODE REVIEW

**Comment by JukkaL** [comment]
Thanks for the PR! Can you update the failing tests to use the new error message?

**Comment by ajrpeggio** [comment]
> Thanks for the PR! Can you update the failing tests to use the new error message?

Absolutely! I just updated the test cases :)

**Review by hauntsaninja — APPROVED** [review]
This looks great, thank you! 

One possible nit: maybe "or be a tuple of exception classes"? I think the additional "be" makes it clearer in the presence of "derived"

**Comment by ajrpeggio** [comment]
> This looks great, thank you!
> 
> One possible nit: maybe "or be a tuple of exception classes"? I think the additional "be" makes it clearer in the presence of "derived"

That's an easy adjustment. I'll do that now.

**Review by hauntsaninja — APPROVED** [review]
Thanks again! :-)

**Comment by hauntsaninja** [comment]
(We're experimenting with reporting CI time differences, the performance numbers here are just noise)

**Pull request merged**
