### PR TITLE
Allow new-style self-types in classmethods

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fixes https://github.com/python/mypy/issues/16547
Fixes https://github.com/python/mypy/issues/16410
Fixes https://github.com/python/mypy/issues/5570

From the upvotes on the issue it looks like an important use case. From what I see this is an omission in the original implementation, I don't see any additional unsafety (except for the same that exists for instance methods/variables). I also incorporate a small refactoring and remove couple unused `get_proper_type()` calls.

The fix uncovered an unrelated issue with unions in descriptors, so I fix that one as well.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
Hm, interestingly the last commit also fixed the primer somehow. Although this may seem good, it is actually suspicious, it may be that we handle access to self-type on unions incorrectly. Let me check this.

**Comment by ilevkivskyi** [comment]
Oh, yup, we incorrectly use `mx.original_type` instead of `mx.self_type` in two places: in new-style self-types, and in descriptor access logic. Why it is always a can of worms...

**Comment by ilevkivskyi** [comment]
> Why it is always a can of worms...

In fairness it looks like this time I contributed to both issues, LOL. In any case I am now happy with `mypy_primer`, so I am going to merge this soon, unless there are objections.

**Review by JukkaL — APPROVED** [review]
Nice to see some many bugs fixed!

**Pull request merged**
