### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by hauntsaninja**
Source commit:
https://github.com/python/typeshed/commit/9116b2928d63632cb9c9526b18d1ffafaf5bafa4

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Primer is from fixing the PathLike regression

**Comment by hauntsaninja** [comment]
This error is a little less friendly, but seems fine
```
-_testDictWithStarStarSpecialCase.py:4: error: Argument 1 to "update" of "dict" has incompatible type "Dict[int, int]"; expected "Mapping[int, str]"
+_testDictWithStarStarSpecialCase.py:4: error: Argument 1 to "update" of "MutableMapping" has incompatible type "Dict[int, int]"; expected "SupportsKeysAndGetItem[int, str]"
```

**Comment by hauntsaninja** [comment]
I propose removing stdlib samples altogether in #11906

**Comment by hauntsaninja** [comment]
The asyncio ones are interesting.
`testAsyncioGatherPreciseType` seems unfortunate, seems like maybe type inference is different now that `asyncio.sleep` is a coroutine.
However, `testErrorUsingDifferentFutureTypeAndSetFutureDifferentInternalType` I think it catches a bug in the test: asyncio.coroutine is missing the @ so it doesn't decorate. cc @sobolevn since you might be amused by this :-)

**Comment by sobolevn** [comment]
Thanks for the ping: I've updated this test [here](https://github.com/python/mypy/pull/11908)

> This error is a little less friendly, but seems fine
> -_testDictWithStarStarSpecialCase.py:4: error: Argument 1 to "update" of "dict" has incompatible type "Dict[int, int]"; expected "Mapping[int, str]"
> +_testDictWithStarStarSpecialCase.py:4: error: Argument 1 to "update" of "MutableMapping" has incompatible type "Dict[int, int]"; expected "SupportsKeysAndGetItem[int, str]"

I've also partially covered this problem in https://github.com/python/mypy/pull/11693
(It depends whether this is a real `.update()` call or `**` which mimics `.update()`)

**Comment by hauntsaninja** [comment]
Okay, just got the `asyncio.gather` regression left. I don't fully understand what's going on, the relevant change is probably to `asyncio.sleep`: https://github.com/python/mypy/pull/11905/files#diff-04a6e8e72f5ccf748662e8786571059eccb8154c46a42135c26127862e756870R244

**Comment by sobolevn** [comment]
@hauntsaninja `asyncio.sleep` was changed by me. 

I did it so it will match its definition in: https://github.com/python/cpython/blob/7357ac94f84ae768c39a6bccf1a3f5c4e8dc8c75/Lib/asyncio/tasks.py#L593

**Comment by hauntsaninja** [comment]
@sobolevn the typeshed change itself makes sense and I'm fine with.

The part I'm missing is why mypy's type inference is worse with the new definition of `asyncio.sleep`. If this is exposing a bug in mypy, I don't want to just change the test so that things are green. Does the change in type inference makes sense to you?

In fact, I just found something really weird.

So the test expects the following to reveal `Future[list[Any]]`, with this PR, the test reveals `Future[Any]`
```
reveal_type(asyncio.gather(*[asyncio.sleep(1), asyncio.sleep(1)]))
```

But really weirdly, if you add another `reveal_type`, mypy is once again able to infer the better `Future[list[Any]]` type. That is, the following shows `Future[list[Any]]` for the outer `reveal_type`.
```
reveal_type(asyncio.gather(*[reveal_type(asyncio.sleep(1)), asyncio.sleep(1)]))
```

**Comment by sobolevn** [comment]
> Does the change in type inference makes sense to you?

No, it looks like a bug 😞

**Comment by hauntsaninja** [comment]
Just marking that test as xfail for now, we can file an issue

**Comment by hauntsaninja** [comment]
Filed an issue for the regression in https://github.com/python/mypy/issues/12089

**Pull request merged**
