### PR TITLE
Check `Enum` definition for invalid base classes

### PR DESCRIPTION
**Pull request by sobolevn**
Checks in Python's source:
- No classes after `Enum` base: https://github.com/python/cpython/blob/d05a66339b5e07d72d96e4c30a34cc3821bb61a2/Lib/enum.py#L971-L974
- Only a single data type: https://github.com/python/cpython/blob/d05a66339b5e07d72d96e4c30a34cc3821bb61a2/Lib/enum.py#L1011-L1012

Closes https://github.com/python/mypy/issues/11948

### CODE REVIEW

**Comment by 97littleleaf11** [comment]
Something off-topic: the `checker.py` is somehow quite large, do you have any idea on split it into several submodules? cc @JukkaL

**Comment by sobolevn** [comment]
There are quite a lot of stateless methods that we can extract like new `check_enum_bases`. We only need `fail` callback there 🤔

**Review by JukkaL — APPROVED** [review]
Thanks, looks good! Sorry for the slow response, I'm slowly getting back to mypy code reviews.

**Comment by JukkaL** [comment]
We can split `checker.py` by defining a trait/interface that contains commonly used helper methods such as `fail` and passing the checker instance to another module using this new trait type to avoid an import cycle. We've already split `semanal.py` in this way (using `SemanticAnalyzerInterface`), though it's still very big.

The key would be to identify groups of related functionality that make sense to be moved away to a new module. Just moving random bits and pieces to another module doesn't improve the situation much. The `semanal_foo` modules can perhaps act as some inspiration.

**Pull request merged**
