### PR TITLE
[WIP] Fix bug with exception variable reuse in deferred node.

### PR DESCRIPTION
**Pull request by gvanrossum**
See https://github.com/python/mypy/pull/1748#issuecomment-254927514

### CODE REVIEW

**Comment by gvanrossum** [comment]
@JukkaL Can you think of a way to make the test fail if somehow the function no longer makes it into the deferred_nodes queue? If not I think this fine to merge.

**Comment by JukkaL** [comment]
What about having a test option to print out the names of deferred functions at the end of a test case? Deferred type checking has some pretty tricky potential failure modes so good tests are important. Otherwise, some of our tests that are supposedly testing deferred nodes might actually only require a single pass.

**Comment by gvanrossum** [comment]
Continued discussion in #1748 indicates this fix is wrong!

**Comment by JukkaL** [comment]
This looks reasonable to me. It's probably not the cleanest fix for this issue but we can live with it. Add a TODO comment about a potentially cleaner approach and this is ready to merge. (Also discussed this offline.)

**Comment by gvanrossum** [comment]
OK, with @JukkaL's approval, merged @ecprice's solution. It works!

**Pull request merged**
