### PR TITLE
Add support for specifying multiple packages on the command line alongside modules

### LINKED ISSUE #4732: Repeated --package arguments are ignored
<s>Running `mypy -m module1 -p package1 -p package2` results in only `module1` being checked.</s>

Running `mypy -p package1 -p package2` results in only `package2` being checked.

Ideally this would check all of them, but it should at least error, rather than silently passing and tricking me into thinking my annotations are valid in `package1`<s> and `package2`</s>

### PR DESCRIPTION
**Pull request by eric-wieser**
Fixes #4732

Let me know how best to add tests for this, if you think they're needed.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Are you going to fix the error?

**Comment by eric-wieser** [comment]
CI output wasn't showing up when I looked before. I'll take a look later today

**Comment by eric-wieser** [comment]
Alright fixed.

**Comment by gvanrossum** [comment]
Hm, we don't seem to have tests for -m and -p at all... Could you add some? They would go in test-data/unit/cmdline.test.

**Comment by eric-wieser** [comment]
Tests don't run at all locally for my machine, so I'm gonna hijack the CI to do my testing...

(fails with `AssertionError: De-serialization failure: TypeInfo not fixed` when I run `python setup.py test`)

**Comment by eric-wieser** [comment]
Ok, test added

**Comment by gvanrossum** [comment]
Don't use setup.py for tests, see README for instructions.

**Comment by eric-wieser** [comment]
Are you happy with the test I've added here? Seems to pass locally and on travis

**Pull request merged**
