### PR TITLE
Merge subtype visitors

### LINKED ISSUE #3297: is_subtype vs is_proper_subtype
Currently, we have two functions ``is_subtype`` and ``is_proper_subtype``. There are two corresponding visitors: ``SubtypeVisitor`` and ``ProperSubtypeVisitor``, both of them implement some complex logic.
I think that _ideally_ there should be only one visitor, ``ProperSubtypeVisitor``, and ``is_subtype`` should be simply:
```python
def is_subtype(left, right):
    if isinstance(left, AnyType) or isinstance(right, AnyType):
        return True
    return is_proper_subtype(left, right)
```
Are there any reasons why it is not possible now? Maybe this question already exists in a roadmap mentioned in https://github.com/python/mypy/issues/3194 (btw @JukkaL @ddfisher is it possible to make it public?)

(I have found this issue https://github.com/python/mypy/issues/2038, but I am not sure it is up to date.)

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fixes #3297

This removes a significant chunk of code duplication. This is not a pure refactor, there were some cases when one of the visitors (mostly non-proper one) was more correct and/or complete. In few corner cases, where it was hard to decide, I merged behavior with `if` checks.

cc @JukkaL

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
The `pandas` errors are correct, `isort` is kind of expected as subtyping with `Type[...]` is a mess, but should be easy to fix, `xarray` is a mystery (and most likely a bug in the PR).

**Comment by ilevkivskyi** [comment]
@hauntsaninja @JelleZijlstra could one of you (or both) please take a look at this?

**Comment by JelleZijlstra** [comment]
The starlette error (https://github.com/encode/starlette/blob/0b5b9c45ed281135f5d23d45041a12824d232260/starlette/config.py#L77) seems correct: the last overload is covered by the previous one.

**Review by JelleZijlstra — APPROVED** [review]
Looks reasonable but I'm not really familiar with this area of the code.

**Comment by ilevkivskyi** [comment]
Thanks for review! Note I now also make it impossible to call `is_subtype()` with `proper_subtype` flag, by moving split point one call lower, at `_is_subtype()`, which is internal. The motivation is that such a big semantic change as being proper shouldn't be controlled by a flag (otherwise this would invite bugs in future).

**Comment by hauntsaninja** [comment]
This PR has actually caused new errors on 3.11's typeshed which seem incorrect to me. Again to do with `Type[...]` subtyping.

You can repro with `mypy -c '' --python-version 3.11 --no-silence-site-packages` on master

**Comment by ilevkivskyi** [comment]
Should be fixed by https://github.com/python/mypy/pull/13461

**Pull request merged**
