### PR TITLE
Make operations on None fall back on object

### PR DESCRIPTION
**Pull request by ddfisher**
Fix for the first error in #1766.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks for the fix! Should we close the issue?

**Comment by gvanrossum** [comment]
(Also, this gives me an idea for how to fix #1810?)

**Comment by ddfisher** [comment]
Not yet!  The second error in the issue is actually a separate bug, which I'm about to put up a PR for.

**Comment by ddfisher** [comment]
1810 is a PR -- did you mean a different issue?

**Pull request merged**
