### PR TITLE
Refactor error messages into a single file

### LINKED ISSUE #10843: Exact error codes for mypy errors
**Feature**

Pylint / Flake8 style, unique error codes to be shown with every error that mypy raises.

**Pitch**

Mypy currently has ~40 general error names, that are shown next to the error if you pass the `--show-error-code` flag to `mypy`. For eg:

```console
$ cat sample.py
def foo(a: str) -> str:
    return '(' + a.split() + ')'

$ mypy sample.py --show-error-codes
sample.py:2: error: Unsupported operand types for + ("str" and "List[str]")  [operator]
Found 1 error in 1 file (checked 1 source file)
```

But in total there's at least ~80 unique error messages, each for a different kind of error.

#### The idea
- Create a proper list of numeric error codes, say `001` though `080` for eg., identifying each error uniquely.
- Have the error code shown directly before the error message in mypy output, just like `pylint`, `flake8`, and others.

```console
$ cat mytest.py      
def a():
    print(foo)

$ pylint mytest.py
************* Module mytest
mytest.py:1:0: C0114: Missing module docstring (missing-module-docstring)
mytest.py:1:0: C0103: Function name "a" doesn't conform to snake_case naming style (invalid-name)
mytest.py:2:10: E0602: Undefined variable 'foo' (undefined-variable)
[...]

$ flake8 mytest.py
mytest.py:1:1: D100 Missing docstring in public module
mytest.py:1:1: D103 Missing docstring in public function
mytest.py:2:11: F821 undefined name 'foo'
```

I've run the idea past @ethanhs and I'm told that this would be a great-to-have in mypy. I'm willing to contribute this, once I've run it past the mypy team :smile: 

cc @srijan-deepsource

### PR DESCRIPTION
**Pull request by tushar-deepsource**
### Description

This PR moves all errors thrown by mypy into the already-exsting `message_registry.py`, while also wrapping every error message into an `ErrorMessage` class.

This is an effort to be able to add unique codes to every error that mypy throws, to resolve #10843.

### Changes

- Almost all of mypy's error messages are either static strings, or are templates which are filled using `str.format`. So, instead of having them scattered around all of the files, this puts every single error raised into `message_registry.py`.
- Instead of passing a separate `msg` string and `code` value into every `fail()` method call, now error messages being raised are `ErrorMessage` objects, which puts the error message and error code together.

### Progress

This tracks how many files have been migrated from strings to the central `ErrorMessage` approach.

- [x] Migrate `checkers.py`
- [x] Migrate other checker files
- [x] Migrate `typeanal.py`
- [x] Migrate smaller semantic analyzers
- [x] Migrate enums, typeddict and namedtuple analyzers
- [x] Migrate `checkerstrformat.py`
- [x] Migrate `messages.py`
- [x] Migrate `semanal.py`
- [x] Fix abstract classes in `plugins.py`
- [x] Migrate plugins

There are also a few instances of `ErrorMessage` objects being created outside `message_registry.py` for supporting dynamic behaviour. Most of those can be removed as well, which is work in progress.

### Future plans

I would also like to properly categorize all of the error messages, and then eventually assign unique identifiers: either numeric (eg. `E0163`), or readable (eg. `unreachable-right-operand`) to every single message. This would allow much easier identification of error messages by people, or by other tools.

### Suggestions

I'd like to know about any suggestions, changes you'd want to make, or things I have overlooked. Do let me know! I'd be happy to make changes accordingly.

### CODE REVIEW

**Comment by TH3CHARLie** [comment]
Thanks for working on this. This really is a nice refactoring though its own complexity may be too much to pack into a single PR. I feel it's completely OK to open separate ones to do the refactoring.

**Comment by tushar-deepsource** [comment]
@TH3CHARLie Okay, how do I go about breaking this down. Maybe break it into checkers/semanal/messages and so on? each with 300 or so lines changed?

**Comment by TH3CHARLie** [comment]
That would be a decent approach, you can use your bullet list to break up the PR. I think that provides a very nice plan.

**Comment by tushar-deepsource** [comment]
> you can use your bullet list to break up the PR

@TH3CHARLie Alright, I'll do that.

The only issue seems to be that mypyc doesn't compile with the `ErrorMessage` class I introduced. Something about not being able to determine types. Every other test passes. Some bug?

**Comment by ethanhs** [comment]
This change will also affect several plugins I expect, so if you want to go ahead with a split up version of this, we should notify plugin maintainers in https://github.com/python/mypy/issues/6617

**Comment by JukkaL** [comment]
I'm not sure if this is the right direction (see https://github.com/python/mypy/issues/10843#issuecomment-896215007). This could break backward compatibility or regress usability of `# type: ignore[...]` comments, in particular.

**Comment by tushar-deepsource** [comment]
@JukkaL This PR at least, i believe doesn't change any usability at all.

Regarding the introduction if fine-grained error codes, it can be implemented along with the already existing error codes, see https://github.com/python/mypy/issues/10843#issuecomment-896227458 for an example. I'd be happy to clarify if it's unclear.

**Pull request closed without merging**
