### PR TITLE
Add a py.typed marker, per PEP 561

### PR DESCRIPTION
**Pull request by gvanrossum**
(Might want to wait merging this until PEP 561 is accepted.)

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
Does this mean that PEP 561 will not go into 3.7?

**Comment by gvanrossum** [comment]
Must have been a side-effect of prematurely cleaning out the branch.

FWIW I don't believe that there is any effect of PEP 561 on CPython, so I don't consider this urgent.

IIUC @ethanhs is still working on his implementation -- I'd like to play around with that before finalizing acceptance of his PEP (I believe he revised the PEP at least once as a result of something he encountered during implementation).

**Comment by ethanhs** [comment]
>FWIW I don't believe that there is any effect of PEP 561 on CPython, so I don't consider this urgent.

Agreed, it doesn't need to be accepted before 3.7 lands.

>IIUC @ethanhs is still working on his implementation -- I'd like to play around with that before finalizing acceptance of his PEP (I believe he revised the PEP at least once as a result of something he encountered during implementation).

Yes I am afraid I haven't had much time in the last month to work on it (or much of anything), but I hope to get back to it more this weekend.

**Comment by ethanhs** [comment]
Now that #4693 is merged, I believe this can be merged too? (I will go ahead and fix the merge conflict).

**Comment by gvanrossum** [comment]
Whoops pilot error. Will fix.

**Comment by gvanrossum** [comment]
Actually I was very thorough in my misguided scrubbing of this branch. @ethanhs do you still have a copy?

**Comment by ethanhs** [comment]
No I don't think so, I fixed the merge conflict online, so I don't have my own copy.

**Comment by gvanrossum** [comment]
OK, new one is in $4879. Is there a reason not to merge this in 0.590?

**Comment by ethanhs** [comment]
I don't think so, no.

**Comment by gvanrossum** [comment]
Hm, then why did you say previously "This should wait for the PEP to be accepted"? (IIUC you even edited your comment to strike through "I believe this can be merged too?" and add that.)

**Comment by ethanhs** [comment]
You had said it should wait for the PEP to be accepted in the original comment. I have no reason to wait, so it's up to you. Apologies for the confusion.

**Pull request closed without merging**
