### PR TITLE
Don't error on raising from None

### PR DESCRIPTION
**Pull request by kirbyfan64**
I was too lazy to wait for the specs to run on my not-too-fast computer, so we'll see what Travis has to think about this...

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Ugh...so, in *one* test, I put `flags: --strict-optional`, but it seems to have somehow screwed with `fixtures/ops.pyi`. The failing tests all run perfectly on my computer, so I have NO clue what the heck is going on...

**Comment by gvanrossum** [comment]
All the strict optional tests are supposed to be together in check-optional.test. The strict-optional flag sets a global that never gets reset, that's why. I don't know why it doesn't fail for you; I get the same failures when I run pytest.

**Comment by ddfisher** [comment]
Looks good, thanks!

**Comment by gvanrossum** [comment]
Thanks!! PS, please let us do the squashing. It's easier to understand what went on in a code review when you don't squash locally. :-)

**Pull request merged**
