### PR TITLE
Fix setuptools CI issue

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by gvanrossum** [comment]
If this works, maybe combine with my idea and try "setuptools!=50.0" in both places?

**Comment by hauntsaninja** [comment]
Great, this seems to work.

Errors like `cl : Command line warning D9002 : ignoring unknown option '/O0'` smelt like we weren't using the right compiler. In mypyc/build.py, we gets the C compiler from `from distutils import sysconfig, ccompiler`, which is close enough that I continued to be suspicious.

**Review by gvanrossum — APPROVED** [review]
Okay to land.

But we should eventually support newer setuptools versions too, otherwise we'll just break in a different way in the future, and it'll be another wild goose change.

**Comment by hauntsaninja** [comment]
Sure, I'll file an issue. So continues the packaging treadmill...

**Pull request merged**
