### PR TITLE
add add_method_to_class() function for plugins.common

### PR DESCRIPTION
**Pull request by mkurnikov**
* move `mypy.plugins.common.add_method()` to `SemanticAnalyzerPluginInterface` and to `SemanticAnalyzer`
* change old implementation to call new one, to preserve backwards compatibility
* replace first `ctx` parameter with `cls: ClassDef`

Fixes https://github.com/python/mypy/issues/8244

### CODE REVIEW

**Comment by mkurnikov** [comment]
The only reason was to make the fact that it could only be used for `SemanticAnalyzer` phase clearer. Does it need to be another function, or could I change a signature?

**Comment by msullivan** [comment]
I'd prefer to add a new function, I think, to avoid breaking compatibility unnecessarily. It is kind of unfortunate, though, since it was a mistake really.

**Comment by mkurnikov** [comment]
I've updated, not sure about naming, let me know what you think

**Comment by msullivan** [comment]
Thanks!

**Pull request merged**
