### PR TITLE
unbreak CI

### PR DESCRIPTION
**Pull request by JelleZijlstra**

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
For some reason Travis didn't pick up this PR at all.

**Comment by JelleZijlstra** [comment]
Now I successfully triggered GitHub Actions, but still no luck with Travis.

**Comment by gvanrossum** [comment]
How about this suggestion instead? https://github.com/pypa/setuptools/issues/2352#issuecomment-683734196

**Comment by TH3CHARLie** [comment]
Rasing this to high priority as new PRs are all failing.

**Comment by hauntsaninja** [comment]
Closing since we merged #9400

**Pull request closed without merging**
