### PR TITLE
PEP 655: Support Required[] inside TypedDict

### PR DESCRIPTION
**Pull request by davidfstr**
### Description

Adds support for the `Required[]` syntax inside TypedDicts as specified by [PEP 655](https://www.python.org/dev/peps/pep-0655/). Note that the `NotRequired[]` syntax from that PEP is **not** in this initial draft, because I want to see first if there is any feedback on how I'm implementing `Required[]`.

A separate PR will be made to the `typing_extensions` module to enable runtime support for `Required[]`.

CC sponsor @gvanrossum

## Test Plan

New tests exist in `test-data/unit/check-typeddict.test` after the `-- Required[]` line, and can be run individually with lines like:
* `pytest -n0 mypy/test/testcheck.py::TypeCheckSuite::testRequiredOnlyAllowsOneItem`

### CODE REVIEW

**Comment by davidfstr** [comment]
Looks like I have a CI failure to investigate...

**Comment by davidfstr** [comment]
CI has passed. Ready for folks to take a look.

**Comment by davidfstr** [comment]
Outline of changes, to hopefully make the review easier:

* There are two kinds of TypedDict declarations mypy recognizes, a **class-based form** and an **assignment-based form**:

```
class Movie(TypedDict, total=False):  # class-based
    title: Required[str]
    year: int

Movie = TypedDict('Movie', {  # assignment-based
    'title': Required[str],
    'year': int,
}, total=False)
```

* Those declarations are parsed by, respectively:
    * TypedDictAnalyzer.analyze_typeddict_classdef @ mypy/semanal_typeddict.py
    * SemanticAnalyzer.analyze_typeddict_assign @ mypy/semanal.py
* This commit alters both of these functions to recognize `Required[...]` as valid wrapper around each key's type, and to treat such-marked keys as required.
* Both of these functions obtain a `Type` for each key in the TypedDict by calling `SemanticAnalyser.anal_type()` on the key type.
* `anal_type()` is changed by this commit to recognize `Required[...]` as a `RequiredType` in:
    * try_analyze_special_unbound_type @ mypy/typeanal.py
* We only want to allow the `Required[...]` syntax in the very narrow situation of a TypedDict key definition. So the top call of `SemanticAnalyser.anal_type()` takes an `allow_required=True` parameter that can be used to enable recogition of `Required[...]` by the two TypedDict-parsing methods, but to disable recognition by default in other contexts.

**Comment by JukkaL** [comment]
I did a quick review pass and overall looks good. It's okay to move forward with supporting `NotRequired` as an extension.

**Comment by davidfstr** [comment]
Thanks for the review @JukkaL ! 

I'll convert this PR to draft for now and add additional commits for the `NotRequired` case. Separately, I'll make a PR for the `typing_extensions` module.

**Comment by davidfstr** [comment]
PR is extended with support for `NotRequired[]` and is ready for another round of review.

**Comment by JukkaL** [comment]
Would you be able to fix the merge conflict -- I can review this now. Apologies for the very slow response!

**Comment by davidfstr** [comment]
I’ve been disconnected from open source for several months to take care of some life issues. I’m hoping I’ll have enough energy to reengage here in a month or so.

In the meantime I welcome any rebase/deconflict support from any observers who’d like this branch to be merged faster.

**Comment by JukkaL** [comment]
No problem!

**Review by JukkaL — APPROVED** [review]
Looks good now. Thank you @davidfstr and @97littleleaf11! This has been a frequently requested feature.

**Comment by 97littleleaf11** [comment]
@JukkaL Thanks for your review! And this PR also looks good to me.

**Comment by davidfstr** [comment]
Thanks @97littleleaf11 for getting this branch finished while I've had to step back for a while.

**Pull request merged**
