### PR TITLE
Mention pip in Quick start.

### PR DESCRIPTION
**Pull request by lrem**
It would be beneficial to mention ease of installation in the README.

### CODE REVIEW

**Comment by Dedoig** [comment]
This does not work correctly if the imported file in turn imports another. Here is a test program:

```
import numpy as np
print("Hello")
```

Runs fine with python, fails with numpy as follows:
```
In module imported in foo.py, line 1:
/.../lib/python3.4/site-packages/numpy/__init__.py, line 202: No module named '__builtin__'
```

Would love to start using this on my code ...

**Comment by spkersten** [comment]
@dedoig I've looked into the error you've found. In `numpy/__init__.py` there is Python 2 specific code behind a check on the Python version. mypy only works on Python 3 code and doesn't recognise that the code guarded by `not sys.version_info[0] >= 3` is Python 2 specific.

**Comment by Dedoig** [comment]
Thanks, @spkersten. Is there a way to skip mypy type-checking (or whatever processing it is trying to do and when it dies) of the numpy import (transitively) and still type check my remaining code?

**Comment by gvanrossum** [comment]
Maybe # type: ignore on the import line?

On Tuesday, April 28, 2015, Dedoig <notifications@github.com> wrote:

> Thanks, @spkersten <https://github.com/spkersten>. Is there a way to skip
> mypy type-checking (or whatever processing it is trying to do and when it
> dies) of the numpy import (transitively) and still type check my remaining
> code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/pull/492#issuecomment-97300378>.
>


-- 
--Guido van Rossum (on iPad)

**Comment by Dedoig** [comment]
import numpy as np # type: ignore ## seemed to help. But then I get this (regardless of # type: ignore):

from functools import partial

==> check-mypy.py, line 2: Module has no attribute 'partial'

**Comment by spkersten** [comment]
@Dedoig I think that your last message is because the stub that mypy uses for `functools` is really limited at the moment (it contains just two functions). You can try adding `partial` to it yourself. The stub is in `mypy/stubs/3.2/functools.py`.

**Pull request merged**
