### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by gvanrossum**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Still blocked until this run cleanly against our internal codebase. The biggest issue may be sqlalchemy.

**Comment by gvanrossum** [comment]
This is no longer blocked -- our internal codebase passes cleanly now. @JelleZijlstra mind merging or approving? (it's fine to wait for AppVeyor. :-)

**Comment by JelleZijlstra** [comment]
I don't have write access to mypy, so I can't merge. The changes look good to me though.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
