### PR TITLE
Add a batch file

### LINKED ISSUE #1226: No console entry point for Windows
On Windows 10 x64 using Python 3.5.1:

``` bat
>pip -V
pip 8.0.2
>pip install mypy-lang
>pip list
...
mypy-lang (0.3.1)
...
>mypy
'mypy' is not recognized as an internal or external command,
operable program or batch file.
```

I think what would be helpful for Windows users would be a `console_scripts` [`entry_point`](https://pythonhosted.org/setuptools/setuptools.html#new-and-changed-setup-keywords):

``` python
setuptools.setup(
    ...
    entry_points={
            'console_scripts': [
                'mypy = (INSERT MAIN MODULE):main',
            ],
```

This will work on Linux and Windows.

### PR DESCRIPTION
**Pull request by kirbyfan64**
Closes #1226. @johnthegen Can you try this out?

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Whoops, meant @johnthagen.

**Comment by gvanrossum** [comment]
I'll hold off until someone confirms it works.

Some questions in the mean time:
- Does it require that Python 3 is installed as "python" ?
- IIRC there's a default binding of *.py files to be executed by the (most recently installed?) Python interpreter. Maybe installing scripts/mypy as scripts/mypy.py would be an alternative?
- Don't newer Python versions for Windows have some kind of "py" program that launches Python scripts?

**Comment by kirbyfan64** [comment]
@gvanrossum 

1: Doesn't the Python 3 installer *always* install it as `<install_directory>/python.exe`?
2 and 3: That will invoke hell if you have two Python versions installed. Using `scripts/mypy.py` will use the default Python interpreter instead of the one mypy was installed in. For instance, if I have Python 3.4 and 3.5 installed, and 3.5 is my default, but I install mypy into 3.4, then running `scripts/mypy.py` would run it under Python 3.5 instead. I believe the `py` scripts would result with the same thing.

**Comment by gvanrossum** [comment]
As I said, I haven't followed the development of the Windows installer at all. So someone who can actually play with it on Windows will have to answer. Remaining question: how does your script end up invoking the correct Python binary?

**Comment by kirbyfan64** [comment]
@gvanrossum `%dp0` will get the location of the Python directory in which the script was installed.

**Comment by gvanrossum** [comment]
Ah, makes sense!

**Comment by johnthagen** [comment]
@kirbyfan64 Seems to have worked, thanks!

```bash
C:\Users\John Hagen>pip install git+https://github.com/kirbyfan64/mypy@bat_file
Collecting git+https://github.com/kirbyfan64/mypy@bat_file
  Cloning https://github.com/kirbyfan64/mypy (to bat_file) to c:\users\johnha~1\appdata\local\temp\pip-6v6s7ej5-build
Installing collected packages: mypy-lang
  Running setup.py install for mypy-lang ... done
Successfully installed mypy-lang-0.3.1

C:\Users\John Hagen>mypy
usage: mypy [-h] [-v] [-V] [--python-version x.y] [--py2] [-s]
            [--disallow-untyped-calls] [--disallow-untyped-defs]
            [--check-untyped-defs] [--fast-parser] [-f] [--pdb]
            [--use-python-path] [--stats] [--inferstats]
            [--custom-typing MODULE] [--html-report DIR]
            [--old-html-report DIR] [--xslt-html-report DIR]
            [--xml-report DIR] [--txt-report DIR] [--xslt-txt-report DIR]
            [--linecount-report DIR] [-m MODULES] [-c COMMAND] [-p PACKAGE]
            [files [files ...]]
mypy: error: Missing target module, package, files, or command.
```

Tested on:
- Windows 10 x64
- Python 3.5.1
- `pip` 8.1.1

**Comment by gvanrossum** [comment]
Thanks! Merged now.

**Pull request merged**
