### PR TITLE
Fix + test for string format with %% and keys

### LINKED ISSUE #1717: Incorrect check on string interpolation
When sending this type-correct code

```python
d = {"greeting": "hello", "count": 10}
print("%(greeting)s World. %(count)d%% tests failing" % d)
```

through mypy, I get the following:
```
error: String interpolation mixes specifier with and without mapping keys
```

Which should be accepted; the only interpolator I'm using withot keys is "%%" which is just an escape and can not cause problems

### PR DESCRIPTION
**Pull request by dmoisset**
This fixes #1717 and adds the corresponding test

### CODE REVIEW

**Comment by ddfisher** [comment]
Thanks!  This looks pretty good, but I think it would be a little cleaner to instead not create `ConversionSpecifiers` if they'd have type `%`  (see `parse_conversion_specifiers`).  Would you mind making that change?

**Comment by dmoisset** [comment]
I made the change and I think its slightly cleaner. I expected it to be better and also allow me to remove the '%' check from replacement_checkers(), but the parser still needs to produce the `ConversionSpecifier` for the `"%*%"` check

**Comment by ddfisher** [comment]
Oh yikes -- I wasn't aware of "%*%" and similar.  In the presence of those, I actually like your initial commit more: "%%" _really is_ a full-on conversion specifier (and not merely an escape sequence as I'd initially thought), but it just doesn't need a value.

Sorry for the flip-flopping!

**Comment by fabianhjr** [comment]
Woops, also took a swing at it with PR: #1905

What I did was store each result in result and if it was the `%%` literal just skip it.

ref: #1717

**Comment by dmoisset** [comment]
@ddfisher I created a PR with the old version of the fix, #1907 , feel free to apply to the one you prefer (I still think this one is the smallest and cleaner, but at this point I think it's just time to choose one of them (or the one from @fabianhjr ).

**Comment by fabianhjr** [comment]
Hello @dmoisset, I think you got an off by one error; The  PR is #1908

**Comment by gvanrossum** [comment]
@ddfisher I'll let you choose the PR to merge!

**Comment by ddfisher** [comment]
Closing in favor of #1908.  Thanks!

**Pull request closed without merging**
