### PR TITLE
move mypyc to console_scripts

### PR DESCRIPTION
**Pull request by imba-tjd**
### Description

See https://github.com/mypyc/mypyc/issues/893

## Test Plan

Works for me on Windows.

### CODE REVIEW

**Review by TH3CHARLie — APPROVED** [review]
Looks good! @ethanhs would you please verify this on Windows as well? Thanks!

**Comment by pranavrajpal** [comment]
I can confirm that this works correctly on my Windows computer.

**Comment by TH3CHARLie** [comment]
@imba-tjd Are you interested in improving mypyc's overall command line functionality? I think it will be a great follow-up issue to work on after this PR. I have a (long stuck) PR that I haven't found time to finish trying to address the problem: https://github.com/python/mypy/pull/10395. If you are interested, I can guide you to work on that.

**Comment by imba-tjd** [comment]
no, I'm working on 考研😂

**Comment by TH3CHARLie** [comment]
I see, good luck to your graduate school entrance exam.

**Pull request merged**
