### PR TITLE
Handle symlinks correctly in Appveyor

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Attempting fixes to python/typeshed#1175. Not intended to be merged.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
It worked! Going to clean up the hacks and make this into a PR that can actually be merged.

**Comment by gvanrossum** [comment]
Thanks! Do those "git reset --hard" calls slow things down at all?

**Comment by JelleZijlstra** [comment]
Thanks! Comparing https://ci.appveyor.com/project/gvanrossum/mypy/build/1.0.1233 and https://ci.appveyor.com/project/gvanrossum/mypy/build/1.0.1223, it doesn't look like it makes a big difference.

**Comment by gvanrossum** [comment]
OK, merged. I guess we can now restore some of the symlinks.

**Comment by JelleZijlstra** [comment]
Are there any other ones than the ntpath/macpath ones you removed recently? I can submit a typeshed PR to make them back into symlinks.

**Comment by gvanrossum** [comment]
Those are probably the only ones -- none of the others apparently were ever exercised by various tests.

Here's a list of all current symlinks in the mypy and typeshed repos:
```
./test-data/.flake8@ -> ../typeshed/.flake8
./typeshed/stdlib/2/SocketServer.pyi@ -> ../3/socketserver.pyi
./typeshed/stdlib/2/builtins.pyi@ -> __builtin__.pyi
./typeshed/stdlib/2/macpath.pyi@ -> posixpath.pyi
./typeshed/stdlib/2/ntpath.pyi@ -> posixpath.pyi
./typeshed/stdlib/2/os2emxpath.pyi@ -> posixpath.pyi
./typeshed/third_party/3/enum.pyi@ -> ../../stdlib/3.4/enum.pyi
```

**Comment by gvanrossum** [comment]
We may have to roll this back and try one of the other solutions; the Windows development experience is pretty bad currently (you have to be Administrator for many git commands). See e.g. https://github.com/python/mypy/issues/3222#issuecomment-298162675

**Pull request merged**
