### PR TITLE
sync typeshed

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Prepare for merging python/typeshed#3371 and the accompanying mypy PR.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
A bunch of errors of the form `  __init__.pyi:116: error: Name 'DefaultEventLoopPolicy' already defined (possibly by an import) (diff)` appeared.

**Comment by JelleZijlstra** [comment]
Right, I'm working on a typeshed PR now to fix it.

**Comment by jlaine** [comment]
The error is now `test-data\samples\crawl.py:838: error: Incompatible types in assignment (expression has type "AbstractEventLoop", variable has type "ProactorEventLoop")`, any chance of getting this fixed so typeshed can be resynced?

**Comment by msullivan** [comment]
I merged #7948, syncing typeshed

**Pull request closed without merging**
