### PR TITLE
Update pythoneval-asyncio.test

### PR DESCRIPTION
**Pull request by sobolevn**
Refs https://github.com/python/mypy/pull/11905
CC @hauntsaninja

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Thanks, you're right that this one doesn't need to be done in the sync PR since it'll pass on master

**Comment by sobolevn** [comment]
@hauntsaninja is there anything else I should do? 🙂

**Comment by hauntsaninja** [comment]
Nope, this one was straightforward and I had covered. If you want, you could look into what's going on with type inference in `testAsyncioGatherPreciseType` in the "Sync typeshed" PR, but feel free not to!

**Comment by sobolevn** [comment]
@hauntsaninja it looks like this happens because `gather` uses `tuple` and `list` as return types. `Overload` logic does not like this, here: https://github.com/python/mypy/blob/e0a89b75fbefc48bb82c924979a8e1c52d65818e/mypy/checkexpr.py#L1620

**Comment by hauntsaninja** [comment]
@sobolevn but the type of gather has not changed in #11905 , only the type of `asyncio.sleep` has

https://github.com/python/mypy/pull/11905/files#diff-04a6e8e72f5ccf748662e8786571059eccb8154c46a42135c26127862e756870

**Pull request merged**
