### PR TITLE
Show more information in incompatible types in indexes

### LINKED ISSUE #1617: "Incompatible types in assignment" for value of dict does not display the types involved
Repro:
```python
a = {1: 1}
a[2] = ''  # E: Incompatible types in assignment
```
Compare to this simpler program:
```python
a = 1
a = ''  # E: Incompatible types in assignment (expression has type "str", variable has type "int")
```

### PR DESCRIPTION
**Pull request by kirbyfan64**
Fixes #1617. Had to update a *lot* of test cases...

### CODE REVIEW

**Comment by gvanrossum** [comment]
Can you fix the CI failure? One line and one test you apparently missed...

**Comment by gvanrossum** [comment]
Othewise LG!

**Comment by kirbyfan64** [comment]
It seems that the build is technically passing; 3.5 just seems to have [errored out while downloading [CPython](https://travis-ci.org/python/mypy/jobs/135050049).

**Comment by gvanrossum** [comment]
I've restarted the job.

--Guido (mobile)

**Comment by gvanrossum** [comment]
Wee!

**Pull request merged**
