### PR TITLE
Improve stubgen

### PR DESCRIPTION
**Pull request by tharvik**
Add some type defaults to generated stubs.

For example
```python
CONST = 1

class A:
    B = ''
    def __init__(self):
        self.c = None
```
get typed as
```python
from typing import Any, Optional

CONST = ...  # type: int

class A:
    B = ...  # type: str
    c = ...  # type: Optional[Any]
    def __init__(self) -> None: ...
```

Do not support ~complex cases like
```
a, b = 1, 2
```

### CODE REVIEW

**Comment by JukkaL** [comment]
Looks good! One thing might need some tweaking. We probably shouldn't infer `Optional[...]` for `x` in the example below, since `None` is sometimes used as the default value for mutable instance variables, as `x = []` would not be right in the class body. In this example we should probably infer `Any` as the type of `x`, at least if `x` is also assigned to in `__init__`:

```
class A:
    x = None
    def __init__(self):
        self.x = []
```

`None` initializers in `__init__` can result in `Optional[Any]`, since there is no reason not to initialize with `[]`, for example. This is only relevant for class bodies.

**Comment by tharvik** [comment]
I've gone the easy way and simply infer `Any` for the `None` cases.

**Comment by JukkaL** [comment]
It would still be nice to infer `Optional[Any]` for functions arguments with a default `None` value. Would it be difficult to special case function arguments this way?

**Comment by tharvik** [comment]
Okay, added, not very pretty but a nicer way (not special case) would require some structural changes.

**Comment by tharvik** [comment]
Also added a test case about it.

**Comment by JukkaL** [comment]
Thanks!

**Comment by gvanrossum** [comment]
Thanks! I'm confused though -- it seems to generate type annotations only
for arguments that have defaults?

**Comment by JukkaL** [comment]
Yeah, it would be nice to generate `: Any` annotations for arguments without defaults.

**Comment by gvanrossum** [comment]
But what if the code is already annotated? Shouldn't that annotation just
be copied into the stub? We've been discussing use cases for such behavior.

**Comment by JukkaL** [comment]
That would be nice as well, but stubgen can't do that yet. I can create an issue for that. Also, for type checked code stubgen could run type checking to infer types, but it wouldn't be desirable for unannotated modules as this could result in type errors or even crashes.

**Pull request merged**
