### PR TITLE
Enable support for decorated properties where possible

### LINKED ISSUE #1362: Decorated property not supported
``` python
class Foo(object):
    @property
    @some_decorator
    def foo(self):
        ...
```

is valid in Python 2, but MyPy complains `Decorated property not supported`.
Adding `type: ignore` does not ignore the error.

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fixes #1362

This is based on the original idea by @graingert. I delete the old cryptic error message and instead:
* Enable the situations that we can already handle (cover 95% of what was discussed in the issue)
* For the rest give more precise error messages

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
`mypy_primer` looks great, also I think this is a low-risk PR, so I will go ahead and just merge it.

**Comment by graingert** [comment]
It wasn't actually my idea, I got like 10% of the way in before seeing someone else tried first

**Comment by yashk2810** [comment]
When will mypy release so that we can use this fix?

**Comment by ilevkivskyi** [comment]
I am not sure, if it will be included in 0.980, then in few days, otherwise it will be in 0.990 around end of September.

**Pull request merged**
