### PR TITLE
Allows to use `type[T]` in stubs

### PR DESCRIPTION
**Pull request by sobolevn**
Refs https://github.com/python/mypy/issues/10303

CC @JelleZijlstra @AlexWaygood

### CODE REVIEW

**Comment by AlexWaygood** [comment]
I don't know my way around the mypy code base very well, but it looks like this solves using `type[T]` in annotations, but not in other uses such as type aliases and subclasses — is that correct? 🙂 (Totally understand if you want to leave those use cases to another PR!)

**Comment by sobolevn** [comment]
Yes, other cases are not covered yet 🙂 
Only the one case I've tested.

Example:
Снимок экрана 2021-12-29 в 17 00 09


(I prefer to make a lot of small PRs instead of one big one, because they are a lot harder to get merged)

**Comment by AlexWaygood** [comment]
> (I prefer to make a lot of small PRs instead of one big one, because they are a lot harder to get merged)

Of course! Just wanted to clarify 🙂

**Review by hauntsaninja — CHANGES_REQUESTED** [review]
Thanks, this is great.

I think the names here could use some cleaning up, if you're willing to do a little more refactoring.
`self.allow_new_syntax` is misleading, since it seems to be exactly the same as `is_stub_file`.
It would be great if we could set `self.always_allow_new_syntax = self.is_stub_file or self.api.is_future_flag_set('annotations')`.
We could then get rid of the new method and have checks like `if self.always_allow_new_syntax or self.options.python_version >= (3, 9)`, which seems the most readable to me.

**Comment by sobolevn** [comment]
Sounds like a good idea! I was confused with `allow_new_syntax` as well. Will do tomorrow.

**Comment by sobolevn** [comment]
@hauntsaninja done!

**Comment by hauntsaninja** [comment]
Hooray!

**Pull request merged**
