### PR TITLE
propertize Callable attributes before freezing dataclasses

### PR DESCRIPTION
**Pull request by uSpike**
### Description

Fixes: #12312 

Related: #10292

`Callable` attributes of a `frozen=True` dataclass were not being handled correctly: `Callable` attributes were being propertized if the dataclass was *not* frozen.

This change will always propertize `Callable` attributes before optionally freezing attributes in the dataclass plugin.

## Test Plan

Added a test for Callable types in a frozen dataclass to `test-data/unit/check-dataclasses.test`

### CODE REVIEW

**Comment by uSpike** [comment]
I need to rethink this because this does not raise an error when a frozen dataclass Callable method is mutated.

**Comment by uSpike** [comment]
OK I think I've fixed it so that propertized callables are not writable when frozen.  This PR should be ready for review

**Comment by uSpike** [comment]
Fixed linting error

**Comment by jhance** [comment]
Needs a rebase then I will merge.

**Comment by JelleZijlstra** [comment]
I fixed the merge conflict

**Pull request merged**
