### PR TITLE
Refactor checker error messages

### PR DESCRIPTION
**Pull request by tushar-deepsource**
### Description

Migrates `checker.py` to use the `ErrorMessage` class.

This is a continuation from the discussion over at #10947

#### Some notes:

- Since the type signature of `fail` cannot be changed altogether, it has been overloaded using a `Union` to support `ErrorMessage` objects as well.
- Some `fail` calls are still using strings instead of `ErrorMessage` objects. This is because some of the strings were re-used in other modules, which will be refactored in later PRs.
- Other PRs will be smaller than this one :)

### CODE REVIEW

**Comment by TH3CHARLie** [comment]
Can you fix the style error (and also in the other PR)? Then I can review both PRs once all builds are passed.

**Comment by tusharsadhwani** [comment]
@TH3CHARLie I'm unsure why the mypyc build is failing. For some reason it fails to determine the type of `ErrorCode` objects being passed inside `message_registry.py` and I don't know how to fix it. Any clues?

**Comment by TH3CHARLie** [comment]
How about providing explicit type like `Final[ErrorMessage]`?

**Comment by tushar-deepsource** [comment]
Oh wow, so that didn't work but setting the `ErrorCode` objects as `Final[ErrorCode]` worked. What?

Anyway, thanks for that.

**Review by TH3CHARLie — APPROVED** [review]
Generally LGTM. I notice that some `ErrorMessage`s have no associated codes at this moment, will you plan to provide them later?

**Comment by tushar-deepsource** [comment]
> I notice that some `ErrorMessages` have no associated codes at this moment, will you plan to provide them later?

Yup. Current set of PRs are pure refactors. After this is done, I'll be adding unique error codes for each and every error, like most other linters have.

**Comment by TH3CHARLie** [comment]
Cool, looking forward to that

**Review by ethanhs — APPROVED** [review]

**Comment by ethanhs** [comment]
Could you please resolve the merge conflict?

**Comment by tushar-deepsource** [comment]
Done :)

**Comment by tushar-deepsource** [comment]
I have run mypy_primer locally, and there are no differences in the latest version of this branch :)

**Comment by tusharsadhwani** [comment]
@ethanhs @TH3CHARLie Please take another look, anything left for me to do?

**Comment by ethanhs** [comment]
The mypy primer output doesn't seem right if this is just a refactor, especially since `graphql-core ` seems to have a bunch of type ignores become valid again...

**Comment by tusharsadhwani** [comment]
@ethanhs I added a few more commits which I believe fixes the output, checked by running mypy-primer locally. is there some way to re trigger the action?

**Comment by tushar-deepsource** [comment]
Alright, tidied up the final few bits.
@ethanhs hopefully this is the last time you'll have to trigger the workflows again

**Comment by tusharsadhwani** [comment]
@ethanhs PTAL?

**Review by ethanhs — APPROVED** [review]

**Pull request merged**
