### PR TITLE
Fix overload overlap check for UninhabitedType

### PR DESCRIPTION
**Pull request by ilevkivskyi**
The issue was exposed by merge of subtype visitors. Fix is actually trivial, but the diff is big because I need to add and pass the new flag everywhere (`is_subtype()`, `is_proper_subtype()`, `is_equivalent()`, `is_same_type()` can call each other).

cc @Michael0x2a

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
`mypy_primer` output is technically correct. We (intentionally?) use `is_subtype_no_promote()` everywhere for overload checks. And this PR passes subtype flags to nested subtype checks. So people need to write e.g. `Union[Iterable[int], Iterable[float]]` in the implementation signature.

I am not sure why do we require this? If it looks to strict, I think it is easy to go back to using just `is_subtype()`. @Michael0x2a what was the motivation to ignore promotions during overload implementation signature check?

**Comment by ilevkivskyi** [comment]
Well, FWIW I switched to `is_subtype()` and all tests passed. So I guess it was not really an intentional decision. Let's see what it will do here.

**Comment by ilevkivskyi** [comment]
Yeah, `mypy_primer` looks better now.

**Review by hauntsaninja — APPROVED** [review]

**Comment by hauntsaninja** [comment]
Looks great!

**Pull request merged**
