### PR TITLE
Flip the default for recursive aliases flag

### PR DESCRIPTION
**Pull request by ilevkivskyi**
I don't think we need to wait long time for this. As soon as next release goes out, I think we can flip the default. Otherwise, this feature may degrade, because there are just several dozen tests with this flag on.

(Also I am curious to see `mypy_primer` on this.)

I manually checked each of couple dozen tests where I currently disable recursive aliases (they essentially just test that there is no crash and emit various errors like `Cannot resolve name`).

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
This actually looks really good. The first big bunch from `canonical/operator` is all due to things like this:
```python
        app_state = self._run('goal-state', return_output=True, use_json=True)
        app_state = typing.cast(Dict[str, List[str]], app_state)
```
Mypy obviously rejects such casts, causing massive fallout. (Btw it will probably accept at least some of such casts with `--allow-redefintion`). Anyway, I still think this is weird, why do you need the extra line?

Btw a week ago I decided to check how easy it would be to dog-food recursive aliases in mypy, since we have a good candidate: types/nodes (de-)serialization. And it turns out it was quite hard, it looks like we will need a lot of `assert isinstance()`.

**Review by hauntsaninja — APPROVED** [review]

**Comment by hauntsaninja** [comment]
@ilevkivskyi hmm, mypy_primer has a crash now, probably because that project changed some code.

**Comment by ilevkivskyi** [comment]
Oh, the `steam` thing is tricky. There is a one-line fix
```diff
--- a/mypy/semanal.py
+++ b/mypy/semanal.py
@@ -3022,6 +3022,7 @@ class SemanticAnalyzer(
             analyzed = self.anal_type(s.type, allow_tuple_literal=allow_tuple_literal)
             # Don't store not ready types (including placeholders).
             if analyzed is None or has_placeholder(analyzed):
+                # self.defer()
                 return
```
and this is actually something where I was looking for a long time. Logically that defer should be there, but before I couldn't find any situation where it is needed. And even now I still can't find a minimal repro, there is an import cycle, and the crash depends on very specific order of processing.

**Comment by ilevkivskyi** [comment]
The `sublime_debugger` is also a one line fix, essentially I just tweak some special-casing that currently explicitly blocks forward references at class scope.
```diff
--- a/mypy/semanal.py
+++ b/mypy/semanal.py
@@ -5097,7 +5097,7 @@ class SemanticAnalyzer(
             node is None
             or self.is_textually_before_statement(node)
             or not self.is_defined_in_current_module(node.fullname)
-            or isinstance(node, TypeInfo)
+            or isinstance(node, (TypeInfo, TypeAlias))
             or (isinstance(node, PlaceholderNode) and node.becomes_typeinfo)
         )
```

**Pull request merged**
