### PR TITLE
Update `stubinfo.py` for recent typeshed changes

### PR DESCRIPTION
**Pull request by AlexWaygood**
Removals from `stubinfo.py`:
- `atomicwrites` is archived and deprecated at runtime; stubs were removed from typeshed in https://github.com/python/typeshed/pull/8925
- `attrs` has had inline types for a very long time now
- `chardet` recently cut a release with inline types; typeshed's stubs were marked obsolete in https://github.com/python/typeshed/pull/9318
- `cryptography` has had inline types for a very long time now; the only reason why it's still in typeshed is because other typeshed packages need `types-cryptography` as a dependency, and our testing infrastructure therefore can't currently cope with it being removed from typeshed.
- `emoji` recently cut a release bundling stubs with the runtime package; typeshed's stubs were marked obsolete in https://github.com/python/typeshed/pull/9051
- `termcolor` recently cut a release with inline types; typeshed's stubs were marked obsolete in https://github.com/python/typeshed/pull/8746
- `prettytable` recently cut a release with inline types; typeshed's stubs were marked obsolete in https://github.com/python/typeshed/pull/9023

Additions:
- Stubs for `Xlib` were added in https://github.com/python/typeshed/pull/9279
- Stubs for `consolemenu` were added in https://github.com/python/typeshed/pull/8820
- Stubs for `dockerfile_parse` were added in https://github.com/python/typeshed/pull/9305
- Stubs for `flask_migrate` were added in https://github.com/python/typeshed/pull/8967
- Stubs for `paho.mqtt` were added in https://github.com/python/typeshed/pull/8853
- Stubs for `pycocotools` were added in https://github.com/python/typeshed/pull/9086
- Stubs for many `pywin32` modules were added in https://github.com/python/typeshed/pull/8825, and multiple follow-up PRs
- Stubs for `pyscreeze` were added in https://github.com/python/typeshed/pull/8823

### CODE REVIEW

**Comment by AlexWaygood** [comment]
`pywin32` makes an _insane_ number of modules available if you `pip install pywin32`:

<details>

```pycon
>>> import isapi
>>> import pythonwin
>>> import win32
>>> import win32com
>>> import win32comext
>>> import afxres
>>> import commctrl
>>> import win32ui
>>> import dde
>>> import mmapfile
>>> import mmsystem
>>> import ntsecuritycon
>>> import odbc
>>> import perfmon
>>> import pythoncom
>>> import pywintypes
>>> import regutil
>>> import servicemanager
>>> import sspicon
>>> import timer
>>> import win2kras
>>> import win32api
>>> import win32clipboard
>>> import win32con
>>> import win32console
>>> import win32cred
>>> import win32crypt
>>> import win32cryptcon
>>> import win32event
>>> import win32evtlog
>>> import win32evtlogutil
>>> import win32file
>>> import win32gui
>>> import win32gui_struct
>>> import win32help
>>> import win32inet
>>> import win32inetcon
>>> import win32job
>>> import win32lz
>>> import win32net
>>> import win32netcon
>>> import win32pdh
>>> import win32pdhquery
>>> import win32pipe
>>> import win32print
>>> import win32process
>>> import win32profile
>>> import win32ras
>>> import win32security
>>> import win32service
>>> import win32serviceutil
>>> import win32timezone
>>> import win32trace
>>> import win32transaction
>>> import win32ts
>>> import win32uiole
>>> import winerror
>>> import winioctlcon
>>> import winnt
>>> import winperf
>>> import winxpgui
>>> import winxptheme
```

</details>

I haven't added them all, as it seemed like overkill, but also there's not a particularly principled reason to leave them out.

**Comment by thomkeh** [comment]
Do the suggested type stubs have to live in the typeshed repository? If not, there would also be the pandas stubs: https://github.com/pandas-dev/pandas-stubs

**Comment by hauntsaninja** [comment]
They don't necessarily, but because `--install-types` installs things automatically, there needs to be a high trust bar for stubs mentioned here.
I think pandas-stubs would meet that bar, since it's first party / under the same Github org. But up to @JukkaL, don't think we've outlined criteria before.

**Review by hauntsaninja — APPROVED** [review]
Thanks for doing this!

I guess I have some vague concerns, but they all sort of boil down to "we should improve --install-types"

**Pull request merged**
