### PR TITLE
Add an option to choose tests based on the data file name

### PR DESCRIPTION
**Pull request by pkch**
Also fix an unrelated minor bug in the test runtime cache (I was deleting the newest instead of the oldest logs).

### CODE REVIEW

**Comment by pkch** [comment]
Currently, tests that don't rely on the data files simply ignore the newly added option (`--casefile`); lmk if it's better to change this semantics.

**Comment by gvanrossum** [comment]
Would you mind writing a longer summary of what the problem is you're addressing here and the nature of your solution?

**Comment by pkch** [comment]
Occsaionally, I wanted to run only the tests collected from specific .test file, for example just the tests from `check-namedtuple.test`. The pytest `-k` option only allows to choose based on the original file as seen by pytest (e.g., `testcheck.py`), or class name (e.g., `TypeCheckSuite`), or function/method name (in our case it's actually a specific case, like `testNamedTupleSubtyping`). But since a lot of bug fixing is related to a single .test file, it seems useful to be able to specify just the .test file.

After I asked on gitter whether that option exists, @elazarg suggested that:
> No, since there's a custom plugin for collecting tests. Maybe you can edit it. We can add an argument to pytest and use it in the collection phase. (which is much slower than it can be)

This PR adds `--casefile` option to pytest that limits the case files just to the ones that match the specified regex. However, I do *not* exclude tests that simply don't know anything about .test files; they still run unless excluded by other options. If desired, I can make the `--casefile` option stricter.

**Comment by elazarg** [comment]
If you do this, perhaps you can extract the `cases` logic to the plugin along the way, leaving only the `files` class property. It'll make it easier to perform the next optimization step (parsing and creating files lazily instead of eagerly) more local.

It's just a suggestion. It will make this PR harder to review, so maybe it should be done later.

**Comment by gvanrossum** [comment]
Hm, I had hoped that maybe our custom collector can add the interesting part of the filename into the test name, so we can just use -k?

**Comment by elazarg** [comment]
@gvanrossum I assume it will work, but won't be any faster until the tests will be lazy. I guess this PR does  make it faster already.

**Comment by elazarg** [comment]
(By "faster" I talk about the collection phase)

**Comment by gnprice** [comment]
@pkch and I chatted just now about how to do this -- as Guido suggests above, I think we can reasonably straightforwardly insert the data-file name into the pytest "node ID". The way I'd go about that is to adjust the tree of pytest nodes that we build up, inserting into the hierarchy another layer of internal nodes corresponding to the data files.

The logic that builds up this tree is in `mypy/test/data.py`. Here's a quick, incomplete sketch (an upload of what I live-coded just now sitting next to @pkch) of what that'd look like:
```
diff --git a/mypy/test/data.py b/mypy/test/data.py
index b72d9c5e..c2d30f88 100644
--- a/mypy/test/data.py
+++ b/mypy/test/data.py
@@ -464,20 +464,26 @@ def pytest_addoption(parser: Any) -> None:
 # This function name is special to pytest.  See
 # http://doc.pytest.org/en/latest/writing_plugins.html#collection-hooks
 def pytest_pycollect_makeitem(collector: Any, name: str, obj: Any) -> Any:
     if not isinstance(obj, type) or not issubclass(obj, DataSuite):
         return None
     return MypyDataSuite(name, parent=collector)
 
 
 class MypyDataSuite(pytest.Class):  # type: ignore  # inheriting from Any
+    def collect(self) -> Iterator['MypyDataCaseFile']:
+        for case_file in self.obj.case_files:
+            yield MypyDataCaseFile(case_file, self, case_file)
+
+
+class MypyDataCaseFile(pytest.Class):
     def collect(self) -> Iterator['MypyDataCase']:
         for case in self.obj.cases():
             yield MypyDataCase(case.name, self, case)
 
 
 class MypyDataCase(pytest.Item):  # type: ignore  # inheriting from Any
```

In the tree that pytest builds up in the collection phase, the internal nodes are "collectors"; their `collect` method is called to yield a list of their children; those children may in turn be collectors or leaf nodes. (This is all by my recollection from studying this about a year ago, not recently fact-checked.)

The built-in support for testing Python walks the file tree, produces a collector for each promising-looking module; then looks for classes and functions there, and produces a corresponding node for each one that looks like a test; for classes that node is itself a collector and it looks through the methods. We insert ourselves into that process, and for `DataSuite` subclasses add our own behavior: make a `MypyDataSuite` collector corresponding to that class, which produces a child `MypyDataCase` node for each test case.

So the change would be to have `MypyDataSuite` instead produce a child node for each test data file, which would itself be a collector of a new type, which in turn would produce a child `MypyDataCase` node for each test case in the file.

**Comment by pkch** [comment]
Yes, this is perfect. I'm going a open new PR on this since it's cleaner than reverting a lot of stuff from this one.

**Pull request closed without merging**
