### PR TITLE
Make ClassDef.metaclass an Expression

### LINKED ISSUE #3847: Make ClassDef.metaclass an Expression instead of str
Currently the metaclass node is assumed to be a string. This is inconsistent, requires workarounds such as passing `'<error>'` from the parser to the semantic analysis phase, and makes it awkward to handle metaclasses that come from different contexts (as in python2).

Making it an Expression works cleanly as far as I can tell, and reduces code duplication.

### PR DESCRIPTION
**Pull request by elazarg**
Fix #3847.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
You have another PR https://github.com/python/mypy/pull/3842 that will have conflicts with this one, which one should be considered first?

**Comment by elazarg** [comment]
This one. #3847 should be easier and cleaner afterwards. Should I close it for now?

**Comment by ilevkivskyi** [comment]
> Should I close it for now?

No, it can be left open, but please don't rebase it afterwards, merge master instead.

**Comment by ilevkivskyi** [comment]
I will take a look at this later, sorry, don't have time now.

**Comment by gvanrossum** [comment]
No time to review but the stated goal seems right and the diff looks simple enough, so no objection to Ivan merging this.

**Pull request merged**
