### PR TITLE
[mypyc] Dict true test

### PR DESCRIPTION
**Pull request by 97littleleaf11**
### Description

Closes https://github.com/mypyc/mypyc/issues/768

* Modify `builtin_len(dict)`.
    * In `cpython/dictobject.h`
      ```c
       /* Get the number of items of a dictionary. */
      #define PyDict_GET_SIZE(mp)  (assert(PyDict_Check(mp)),((PyDictObject *)mp)->ma_used)
      ```
    * Thus replace `call_c` with `LoadMem` and add `PyDictObject`. Related issue: https://github.com/mypyc/mypyc/issues/835

## Test Plan

An IR test and a functional test.
Similar to https://github.com/python/mypy/commit/1e96f1df48a6e06ba598fa8230b96671b206cba0

### CODE REVIEW

**Review by JukkaL — COMMENTED** [review]
Hmm the original implementation may actually be buggy. We should allow subclasses to override `__len__`, for consistency with other dict operations, and this means that we should have a type guard. This probably makes it too complex to be done directly in IR, and instead we could use a C helper that uses `PyDict_GET_SIZE` behind a type guard. Sorry about that!

This should work similar to CPython and print 'here':

```py
class D(dict):
    def __len__(self) -> int:
        return 1

if D():
    print('here') 
```

**Comment by 97littleleaf11** [comment]
Got it. I will start a new branch from beginning later.

**Comment by 97littleleaf11** [comment]
I tried adding this:

```py
Py_ssize_t CPyDict_Size(PyObject *dict) {
    if (PyDict_CheckExact(dict)) {
        return PyDict_Size(dict);
    }
    return PyObject_Size(dict);
}
```

```py
class MyDict(dict):
    def __init__(self, *args, **kwargs):
        self.update(*args, **kwargs)

    def __len__(self):
        return 1


def test_dict_subclass_to_bool() -> None:
    d = MyDict()
    if d:
        print("true")
```

However `PyObject_Size` won't call the overrided `__len__`. 
Does the `cast` operation cause that?

```
L0:
    r0 = tmp5.MyDict :: type
    r1 = PyObject_CallFunctionObjArgs(r0, 0)
    if is_error(r1) goto L7 (error at test_dict_subclass_to_bool:45) else goto L1
L1:
    r2 = cast(dict, r1)
    if is_error(r2) goto L7 (error at test_dict_subclass_to_bool:45) else goto L2
L2:
    d = r2
    r3 = CPyDict_Size(d)
    dec_ref d
    r4 = r3 >= 0 :: signed
    if not r4 goto L7 (error at test_dict_subclass_to_bool:45) else goto L3 :: bool
```

**Comment by JukkaL** [comment]
> However PyObject_Size won't call the overrided __len__.

Hmm I wonder if this is a bug in `PyObject_Size`. Anyway, it's already broken for `len(d)`, so not supporting it for boolean checks seems okay. So let's drop the `__len__` override test case and use the original implementation for now. Sorry about the back and forth -- there are some gray areas with respect to CPython compatibility where it's often unclear what's the best course of action.

But can you add a new issue to track the issue of overriding `__len__`? To properly fix it, we should fix it for `len()` as well.

> Does the cast operation cause that?

No, the cast does not modify the operand.

**Review by JukkaL — APPROVED** [review]
Thanks for the updates! This looks good, and it made a quick benchmark I wrote about 50% faster, which is a nice speedup.

**Pull request merged**
