### PR TITLE
Simplify Union Math

### PR DESCRIPTION
**Pull request by davidhalter**
While trying to understand how union matching works in Mypy, I realized that it's probably too complicated.

Recursive matching when doing Union math is not needed, because only one argument can ever be matched as a Union.

Tests remain the same, except for the limitation around recursion levels, which is no longer a limitation. I feel like this could probably be further simplified, but I'm trying to keep this change as small as possible.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks for your work! cc @Michael0x2a who previously worked on this area

**Comment by ilevkivskyi** [comment]
What do you mean only one can be matched as union? What about a case like this:
```python
@overload 
def f(x: int, y: int) -> None: ...
@overload 
def f(x: str, y: int) -> None: ...
@overload 
def f(x: int, y: str) -> None: ...
@overload 
def f(x: str, y: str) -> None: ...

a: Union[int, str]
b: Union[int, str]
f(a, b) # This is valid
```
Btw if we don't have a test like this, we should add one.

**Comment by davidhalter** [comment]
> What do you mean only one can be matched as union? What about a case like this:

Thanks for that piece of code. I couldn't come up with that. I guess in that case my simplification is invalid. Feel free to close the PR.

However, I feel like all union math examples with more than one union will be very weird, because it kind of multiplies the necessary overload definitions (in @ilevkivskyi's case it's already 4 functions). So there could be an argument that this is not used practically anyway and simplifying the code might be worth it.

Consider the current case where the `there are too many unions` error is raised:

```
[case testTooManyUnionsException]
from typing import overload, Union

@overload
def f(*args: int) -> int: ...
@overload
def f(*args: str) -> str: ...
def f(*args):
    pass

x: Union[int, str]
f(x, x, x, x, x, x, x, x)
[out]
main:11: error: Not all union combinations were tried because there are too many unions
```

The algorithm wouldn't even need to try that many union combinations, because it could just reject it after the second union. I at least feel like the algorithm could do that theoretically. Creating an example where we actually have to reject for trying too many cases might result in `2**6` overload members (or if you cleverly use union arguments in some cases you could probably reduce it significantly, but it would probably still be a lot of overload members).

So I feel like @ilevkivskyi is correct mathematically, but I do not think anybody would care about removing union math for more than one union.

**Comment by ilevkivskyi** [comment]
> So there could be an argument that this is not used practically anyway and simplifying the code might be worth it.

As you can see from the `mypy_primer` output above, people do actually use this.

**Comment by davidhalter** [comment]
> As you can see from the mypy_primer output above, people do actually use this.

After checking the mypy_primer cases, this looks more like a buggy implementation on my side and a case where both functions accept `Optional[...]`, which disturbs "my" algorithm. I feel like this could be fixed in theory, but closing this issue is completely fine.

**Pull request closed without merging**
