### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by ilevkivskyi**
In preparation for the release.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
> Did you check if this necessitates any changes to Dropbox code bases?

Testing now, but apparently we have another problem (see test failures). I am looking into it.

**Comment by ilevkivskyi** [comment]
OK, the failures are because of recently added Windows platform checks.

**Comment by gvanrossum** [comment]
Maybe when we run stdlib-samples we should force the platform to linux.

**Comment by ilevkivskyi** [comment]
All checks were added in https://github.com/python/typeshed/commit/1ae2ba0fbe4257397916a4921305d5a69d67df86

> Maybe when we run stdlib-samples we should force the platform to linux.

Self-check also fails. Because daemon is not supported on Windows yet. `testpr` is not done yet, but I remember there were some problems on C when we last attempted using platform checks in typeshed.

**Comment by gvanrossum** [comment]
LMK if you need another approval.

**Comment by ilevkivskyi** [comment]
> LMK if you need another approval.

Are you OK with the change in `dmypy_server.py`? (Other changes are trivial.)

**Pull request merged**
