### PR TITLE
Run more tests in parallel

### PR DESCRIPTION
**Pull request by hauntsaninja**
At some point, Github Actions runners started having more cores: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

### CODE REVIEW

**Comment by manmartgarc** [comment]
Couldn't we use `-n auto`? Here is a GitHub action using that and using 4 workers. https://github.com/manmartgarc/stochatreat/actions/runs/8866655781/job/24344339586

**Comment by hauntsaninja** [comment]
I'm not sure of the history here / I'm not sure what the exact specs of the machines underlying Github runners are.

But reading the xdist code: https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/plugin.py#L32
If you have psutil installed in your env (which mypy does), `psutil.cpu_count()` will give you the incorrect value in containerised environments. We'd want the `sched_getaffinity` number or `len(psutil.Process().cpu_affinity())`. (It is of course also possible that Github is actually running these on 4 core machines, in which case the numbers would be the same)

**Comment by manmartgarc** [comment]
[Seems](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) like it's 4; and using `-n auto` runs 4 workers with `pytest-xdist`. I just think it might be nice not to have to change this again in the future manually; would approve if I could 😄 .

**Comment by JukkaL** [comment]
Faster CI sounds great! What's the impact on the various checks we run?

**Review by JukkaL — APPROVED** [review]
The improvements look good, and in line with what I'd expect, if the underlying hardware can run 2 threads per core.

**Pull request merged**
