### PR TITLE
Release 0.521

### PR DESCRIPTION
**Pull request by gvanrossum**
See #3732.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Ignore the conflicts and test failures, this is a release branch.

**Comment by ilevkivskyi** [comment]
Looks good!

**Comment by ilevkivskyi** [comment]
You mentioned some time ago that @JukkaL has a fix for crashes in recursive ``TypedDict``s https://github.com/python/mypy/issues/3685 and https://github.com/python/mypy/issues/3674. Will it be incorporated?

(FWIW there are similar crashes for ``NamedTuple``s, but IIUC ``TypedDict``s have priority.)

**Comment by gvanrossum** [comment]
No, Jukka told me that fix is more complex than he thought. We'll get it into 0.530.

**Comment by ilevkivskyi** [comment]
I think this can be closed, but maybe we can keep the branch (at least for some time).

**Pull request closed without merging**
