### PR TITLE
Improve suggestion when using `any` as type

### PR DESCRIPTION
**Pull request by siiptuo**
### Description

Using `any` instead of `Any` is an easy mistake to make because "any" has been used as a type in docstrings, editors may highlight it as it's the name for the built-in function and at least TypeScript uses it as a keyword. Here are [some examples](https://grep.app/search?q=%3A%20any%28%5C%5B%7C%2C%7C%20%3D%29&regexp=true&case=true&filter[lang][0]=Python) of this mistake in real-world Python code.

For example, for the following code:

```python
def a(b: any): pass
```

mypy currently outputs:

```
any.py:1: error: Function "builtins.any" is not valid as a type
any.py:1: note: Perhaps you need "Callable[...]" or a callback protocol?
```

I think that the given suggestion is misleading and could be improved. This pull request changes the output to:

```
any.py:1: error: Function "builtins.any" is not valid as a type
any.py:1: note: Perhaps you meant "Any" instead of "any"?
```

## Test Plan

Added a unit test to verify the new output.

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
Thanks, good idea!

**Review by hauntsaninja — COMMENTED** [review]
Thanks, this is great! One nit: maybe the error message should suggest `typing.Any`? I could imagine some new user naively going `any` -> `Any` without the import.

Would you be interested in making a similar PR for `callable`? :-)

**Comment by siiptuo** [comment]
@hauntsaninja 
> Thanks, this is great! One nit: maybe the error message should suggest `typing.Any`? I could imagine some new user naively going `any` -> `Any` without the import.

Good idea! I've updated the output.

> Would you be interested in making a similar PR for `callable`? :-)

I can open a similar PR after this one.

**Comment by hauntsaninja** [comment]
Thank you!

**Pull request merged**
