### PR TITLE
Stop running Python 3.5 in CI

### PR DESCRIPTION
**Pull request by hauntsaninja**
Python 3.5 always fails in CI these days. So a) it's annoying and a bad contributor experience, b) we're effectively not testing against Python 3.5 anyway
Linking https://github.com/python/mypy/issues/9950

### CODE REVIEW

**Review by ethanhs — APPROVED** [review]
I look forward to dropping support so we can use TypeVar without needing to guard it.

**Comment by TH3CHARLie** [comment]
Agreed. Should we keep the number of compiled suites by making 3.6 compiled?

**Comment by hauntsaninja** [comment]
You probably have a better sense of that than I do — how likely is it that 3.6 compiled will catch issues not caught by 3.7 compiled and 3.6?

**Comment by hauntsaninja** [comment]
I do seem to remember we had a CI false negative once because we didn't have a compiled >= 3.8 (due to some typeshed change to ast), so maybe we make Python 3.9 compiled

**Review by TH3CHARLie — APPROVED** [review]
A compiled 3.9 LGTM!

**Comment by JukkaL** [comment]
I think that we should run compiled tests on the earliest supported/working Python version and the latest, so it would be 3.6 and 3.9 after this change.

**Pull request merged**
