### PR TITLE
Process strict flag inside config file

### LINKED ISSUE #2929: No config file option corresponding to --strict
`strict = True` in the config should enable the strict mode, but it doesn't work.

### PR DESCRIPTION
**Pull request by pkch**
Fix #2929 

What's a good way to test it (maybe there's a test file I could use as an example?)

### CODE REVIEW

**Comment by pkch** [comment]
Or should we perhaps refactor the options so that they don't have to be repeated twice (once in `main.process_options`, once in `options.Options.__init__`)?

**Comment by miedzinski** [comment]
This change isn't enough; it does nothing. You can see how `--strict` works here: https://github.com/python/mypy/blob/95fd5fb8ee6712e7af135929a70f0049e924faff/mypy/main.py#L337-L339 and work around it.

**Comment by pkch** [comment]
@miedzinski  oops, the first commit only got rid of the error message `mypy.ini: [mypy]: Unrecognized option: strict = True`; but it didn't actually process the option.

**Comment by JukkaL** [comment]
@pkch Can you fix the merge conflict?

**Comment by ddfisher** [comment]
Also, if we are going to make this change, it doesn't make sense to parse `strict` into `special-opts` anymore -- we should remove that prefix and parse it into the standard namespace instead.

**Comment by gvanrossum** [comment]
In addition, the various options that `--strict` turns on can all be set per-module from the config file. Using `strict` in the config file should likewise allow being specified per-module, otherwise it's not very useful.

**Comment by pkch** [comment]
`strict` now needs to be applied in 3 different places in the code: when parsing config file global section, config file module sections, and command line.  it's not easy to refactor it into one place, and even refactoring it into one function is messy since processing `--strict` relies on a local variable `strict_flag_assignments` created in main

based on the discussion in gitter, I tried this:

1) remove `strict_flag` keyword argument from `add_invertible_flag`, and instead create a class attribute in Options that lists all the flags that should be affected by `--strict`. The default values can be obtained as appropriate either from a fresh `Namespace` instannce or from a fresh `Options` instance. This doesn't seem like it's breaking encapsulation or consistency, since `Options` already has (for example) `PER_MODULE_OPTIONS` attribute.

2) process `strict` immediately when it's seen in the config file, inside the section, rather than propagating it out to the enclosing functions. this way it feels like I'm making a smaller, safer code change.

**Comment by gvanrossum** [comment]
Honestly IMO it's fine not to have a "strict" flag in the config file. The config file is supposed to be lower-level and allow more detail. Just specify the individual options. That way you won't be surprised next time we add a new strict flag and your code breaks.

**Comment by ddfisher** [comment]
I agree -- I think it'd be better for the options to be listed explicitly.  Unless @pkch or @JukkaL want to make a case for it, let's close this and #2929.

**Comment by pkch** [comment]
The only downside of closing this is if someone has super clean code base, and would like to enforce new types of warnings when they become available, they will need to read "what's new" in the docs after `pip install --upgrade` and manually add those options to the config file (potentially to multiple config files if they have multiple projects). I think it's a very minor inconvenience, and I'm *guessing* it's rare in production environment that someone would allow a new type of `mypy` warnings into their build process without first reading about them in the documentation.

So no,  I don't have a case for this feature. (Although, FWIW,  I would personally use it just for convenience.)

**Comment by gvanrossum** [comment]
Well they could still use the command-line flag. :-)

**Comment by gvanrossum** [comment]
OK, let me reopen this and mark it as a low-priority feature. If you or someone comes up with a decent PR for this I'll happily merge it.

**Comment by gvanrossum** [comment]
The existing PR is so out of date that it's probably easier to start a new one, but that's up to whoever takes this on.

**Comment by msullivan** [comment]
I linked to this PR in the bug and am now going to close it

**Pull request closed without merging**
