### PR TITLE
feat: make checklist in PR template interactable

### LINKED ISSUE #15743: make checklist in pull request template interactable
# Current behavior

Contributors can't easily interact with the checklist in the pull request template.

https://github.com/python/mypy/assets/43425812/78d9d115-9828-4252-bd2c-5d1f0d7c5828

# Desired behavior

Checklist in pull request template is interactable

### PR DESCRIPTION
**Pull request by hamirmahal**
closes #15743.

### CODE REVIEW

**Comment by hamirmahal** [comment]
- [ ] I have read the [Contributing Guidelines](https://github.com/python/mypy/blob/master/CONTRIBUTING.md).
- [ ] I have added tests for all changed behavior.
- [ ] If I didn't add a test, I explained why, and how I verified that my changes work.
- [ ] I made sure CI passed.
- [ ] I will not force push to the this pull request once it has been reviewed.

**Comment by hamirmahal** [comment]
- [ ] I have read the [Contributing Guidelines](https://github.com/python/mypy/blob/master/CONTRIBUTING.md).
- [ ] I have added tests for all changed behavior.
- [ ] If I didn't add a test, I explained why, and how I verified that my changes work.
- [ ] I made sure CI passed.
- [ ] I will not force push to the this pull request once it has been reviewed.

**Comment by hamirmahal** [comment]
# Without this change

Contributors can't easily interact with the checklist in the pull request template.

https://github.com/python/mypy/assets/43425812/78d9d115-9828-4252-bd2c-5d1f0d7c5828

# With this change

https://github.com/python/mypy/assets/43425812/79c718c3-d5f2-44ff-8f24-c95eec2575cd

**Comment by hamirmahal** [comment]
@hauntsaninja is there anything you'd like this PR to have?

**Comment by hauntsaninja** [comment]
Thanks, but I find checklists annoying and they don't provide much value

**Comment by hamirmahal** [comment]
You're welcome! Thanks for the rationale.

**Pull request closed without merging**
