### PR TITLE
Fix "Cannot determine type of Any" issue in typeshed

### LINKED ISSUE #12421: mypy fails for a simple `Any` type alias`
I can't reproduce this locally, but please have a look at the CI failures of python/typeshed#7535. The change is a simple type alias `Incomplete = Any`. The `TypeAlias` is optional, mypy fails with or without it. CI runs mypy 0.941 with all Python versions.

### PR DESCRIPTION
**Pull request by JukkaL**
[This was implemented by @sobolevn as part of #12134. Cherry-picking
it to a separate PR since the original PR is still incomplete and the
issue is causing trouble in typeshed.]

Sometimes mypy could generate `Cannot determine type of "Any"` in
`_typeshed/__init__.pyi` when running typeshed tests if there is an alias
to `Any`. This seems to happen only if files are passed in a specific order 
to mypy, and seems related to import cycles. Fix the issue by special 
casing the inference of type of `Any`.

This hopefully fixes #12421.

### CODE REVIEW

**Comment by srittau** [comment]
Looking at the primer output:

* The ibis output is a bit weird. `ibis/expr/operations/__init__.py` star imports from all its sub-modules. Line 1 contains `from .analytic import *`, which imports a class named `Any` from that module, which is unrelated to `typing.Any`. Line 3 contains `from .core import *`. `core.pyi` has `from typing import Any, ...`, but no re-export. So I'm not sure why the star import also imports the conflicting `Any`.
* The `aiohttp` output looks positive:

```python
try:
    from ssl import SSLContext
except ImportError:  # pragma: no cover
    SSLContext = Any  # type: ignore[misc,assignment]
```

The `assignment` override isn't necessary anymore.

**Comment by JukkaL** [comment]
Actually, it looks like #12431 may also fix the same issue. I'm going to postpone this until we've validated #12431.

**Comment by JelleZijlstra** [comment]
> core.pyi has from typing import Any, ..., but no re-export. So I'm not sure why the star import also imports the conflicting Any.

I haven't looked at the ibis code myself, but this is what I'd expect if there's no `__all__` since it matches the runtime behavior. In stubs we can restrict `import *` to only explicitly exported names, but at runtime it imports everything that doesn't start with an underscore, so that's what mypy should do too.

**Comment by srittau** [comment]
Good point. (I wish there was a way to disable that re-export by default behavior in Python, though.)

**Comment by AlexWaygood** [comment]
I can confirm that #12431 has fixed all the known instances of this problem over at typeshed 🎉:

- https://github.com/python/typeshed/pull/7548
- https://github.com/python/typeshed/pull/7535

**Comment by JukkaL** [comment]
Closing this since the issue has now been fixed.

**Pull request closed without merging**
