### PR TITLE
Use type variable bound when it appears as actual during inference

### PR DESCRIPTION
**Pull request by ilevkivskyi**
This should help with re-enabling the use of `ParamSpec` in `functools.wraps` (as it looks like some of the new errors in https://github.com/AlexWaygood/mypy/pull/11 are caused by not handling this).

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
Nice! I think this makes sense, and the primer hits for Argument Clinic and aioredis both look like clear improvements. (Haven't looked too deeply at the hydra-zen hits.)

**Review by hauntsaninja — COMMENTED** [review]
Nice, since you're looking at this, can I also interest you in https://github.com/python/mypy/issues/13220 ? I tried a couple different ways to fix that one and all caused problems.

@AlexWaygood I might be missing something, but aioredis one looks like a regression, no? Repro:
```
from typing import TypeVar, Union, Iterable

KeyT = Union[bytes, str]
_KeyT = TypeVar("_KeyT", bound=KeyT)

def simpler(keys: _KeyT):
    iter(keys)  # now has type error

def lora(keys: Union[_KeyT, Iterable[_KeyT]]) -> _KeyT:
    iter(keys)  # now has type error
    raise
```

**Comment by AlexWaygood** [comment]
> @AlexWaygood I might be missing something, but aioredis one looks like a regression, no?

Oh shoot, I misread the diff — I thought it was saying that the `type: ignore` was now unused, but I guess it's saying that the `type: ignore` is once again used. Yeah, that seems like a regression then :(

**Comment by ilevkivskyi** [comment]
@hauntsaninja That is an unrelated issue. I however already have a fix locally that should likely not cause any adverse side effects. I can make a PR now. Also FWIW I want to focus now on finishing the `TypeVarTuple` stuff, this PR was just a little detour while I am waiting for reviews.

**Review by hauntsaninja — APPROVED** [review]
Thanks, this looks good. I added regression test.

**Pull request merged**
