### PR TITLE
TypedDict: update test for changes to keys, values, items

### PR DESCRIPTION
**Pull request by hauntsaninja**
The signature of TypedDict's keys, values, items will be updated in
typeshed in:
https://github.com/python/typeshed/pull/3529

The relevant issue is:
https://github.com/python/typeshed/issues/3473

That PR fails testTypedDictMappingMethods
https://travis-ci.org/python/typeshed/builds/621439570

Tested by using my patched version of typeshed:
ln -sf ~/typeshed mypy/typeshed
pytest -n0 -k testTypedDictMappingMethods

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Note the CI failure is expected since we'd need python/typeshed#3529 to be merged for tests to successfully run.

**Comment by msullivan** [comment]
@JelleZijlstra do you want to do the typeshed merge stuff?

**Comment by JelleZijlstra** [comment]
Yes, I'll take care of this.

**Comment by msullivan** [comment]
Gentle ping on this, @JelleZijlstra

**Comment by JelleZijlstra** [comment]
Sorry for that! I'm performing all the required merges and syncs now, typeshed and mypy CI should be back to green shortly.

**Comment by msullivan** [comment]
Thanks!

**Pull request merged**
