### PR TITLE
Add `3.11-dev` as `TODO` item says

### PR DESCRIPTION
**Pull request by sobolevn**
Refs https://github.com/python/mypy/issues/11662

### CODE REVIEW

**Comment by sobolevn** [comment]
Looks like some C-API has changed: `#include "longintrepr.h"`, `lxml` does not compile on `3.11-dev`

**Comment by sobolevn** [comment]
I am going to `apt-get install libxml2 libxslt` to see if that works.

**Comment by sobolevn** [comment]
Quoting the changelog for `3.11`: https://github.com/python/cpython/blob/cf7eaa4617295747ee5646c4e2b7e7a16d7c64ab/Doc/whatsnew/3.11.rst

> The non-limited API files cellobject.h, classobject.h, context.h, funcobject.h, genobject.h and longintrepr.h have been moved to the Include/cpython directory. Moreover, the eval.h header file was removed. These files must not be included directly, as they are already included in Python.h

**Comment by sobolevn** [comment]
I've just ignored `lxml` for python 3.11 yet. So, here are the failing tests:

```
 =========================== short test summary info ============================
FAILED mypy/test/testcheck.py::TypeCheckSuite::testReportBasic
FAILED mypy/test/testcmdline.py::PythonCmdlineSuite::testClassDefIsNotTreatedAsEmpty
FAILED mypy/test/testcmdline.py::PythonCmdlineSuite::testTypeVarTreatedAsEmptyLine
FAILED mypy/test/testcmdline.py::PythonCmdlineSuite::testUnreachableCodeMarkedAsAny
FAILED mypy/test/testcmdline.py::PythonCmdlineSuite::testHtmlReportMemberExprNoUnanalyzed
FAILED mypy/test/testcmdline.py::PythonCmdlineSuite::testSpecialAnyHtmlReport
FAILED mypy/test/testcmdline.py::PythonCmdlineSuite::testHtmlReportOnNamespacePackagesWithExplicitBases
FAILED mypy/test/testcmdline.py::PythonCmdlineSuite::testCoberturaParser
FAILED mypy/test/teststubgen.py::StubgenPythonSuite::testCoroutineSpecialCase_import
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::testSimpleCoroutineSleep
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::testCoroutineCallingOtherCoroutine
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::testCoroutineChangingFuture
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::testFunctionAssignedAsCallback
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::testMultipleTasks
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::testConcatenatedCoroutines
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::testConcatenatedCoroutinesReturningFutures
FAILED mypy/test/testpythoneval.py::PythonEvaluationSuite::testCoroutineWithOwnClass
FAILED mypyc/test/test_run.py::TestRun::testCheckVersion
FAILED mypyc/test/test_run.py::TestRun::testForIterable
FAILED mypyc/test/test_run.py::TestRun::testSubclassUninitAttr
FAILED mypyc/test/test_run.py::TestRun::testException
FAILED mypyc/test/test_run.py::TestRun::testTryExcept
FAILED mypyc/test/test_run.py::TestRun::testSubclassPy
FAILED mypyc/test/test_run.py::TestRun::testExceptionAtModuleTopLevel
FAILED mypyc/test/test_run.py::TestRun::testPickling
FAILED mypyc/test/test_run.py::TestRun::testInterpretedParentInit
FAILED mypyc/test/test_run.py::TestRun::testProperty
FAILED mypyc/test/test_run.py::TestRun::testMultiModuleTraceback
FAILED mypyc/test/test_run.py::TestRun::testYieldThrow
FAILED mypyc/test/test_run.py::TestRunMultiFile::testMultiModuleTraceback_multi
FAILED mypyc/test/test_run.py::TestRunSeparate::testMultiModuleTraceback_separate
ERROR mypy/test/testreports.py
= 31 failed, 9622 passed, 370 skipped, 7 xfailed, 2 warnings, 1 error in 552.83s (0:09:12) =
```

**Comment by sobolevn** [comment]
cc @hauntsaninja

**Comment by hauntsaninja** [comment]
Thanks!

**Pull request merged**
