### PR TITLE
no need for windows artifacts, we're universal

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Even if we all end up agreeing this is not needed let's not land it before 0.521 is released.

**Comment by ethanhs** [comment]
I agree with @gvanrossum. Also to be clear about the rational (for now and posterity), even though typed-ast is binary, mypy is pure Python, so platform specific wheels are not needed. It doesn't hurt to have extra wheels, but they just churn extra CI time.

**Comment by graingert** [comment]
> It doesn't hurt to have extra wheels

As you mentioned they add extra CI time, they also:

May cause confusion, people may thing they need to build bdists for linux/mac to install mypy
May cause problems with tooling that make assumptions about universal wheels implying no other wheels.

**Comment by ddfisher** [comment]
@gvanrossum do you remember why we started having platform-specific wheels in the first place?

**Comment by gvanrossum** [comment]
@ddfisher I don't recall, I thought there was some tiny essential difference that *you* once explained to me (maybe it was just the filename itself). I definitely recall being surprised at first but someone (either you or Jukka) convinced me that it was necessary.

**Comment by JukkaL** [comment]
My understanding is that this commit by @ethanhs made it possible to use only a single wheel: 166d54daffb6288958f50146bfc8b35af19a6fbb Previously `setup.py` worked differently on Windows compared to other platforms.

**Comment by ethanhs** [comment]
Ah, I believe that would do it. Before if you built on Linux it wouldn't copy the Windows script into the wheel or visa versa. Now that isnt a problem because setuptools handles the script on install I think.

**Comment by graingert** [comment]
> Now that isnt a problem because setuptools handles the script on install I think.

yup

**Comment by gvanrossum** [comment]
Sorry for the delay! 0.521 has been out of the door for weeks and we haven't heard any complaints so I think we're good here.

**Comment by graingert** [comment]
Wheely great news!

**Pull request merged**
