### PR TITLE
Use variable annotations

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by TH3CHARLie** [comment]
Glad to see we are moving in this direction. It's better if this can be split into several PRs. Did you use scripts to automate this?

**Comment by hauntsaninja** [comment]
Yes, you can see the exact history of what I did in the commit history, the initial heavy lifting is done by com2ann. I'm not sure that breaking this up into multiple PRs would really help. If you want to go over this with a fine toothed comb, the Github "viewed" functionality for each file can be useful. But overall, since this is just changing annotations not code, and type checking and tests pass, I feel pretty confident in this PR.

**Comment by TH3CHARLie** [comment]
Agreed. I'll start to review this and I am also confident this is a No functional change (NFC)

**Review by TH3CHARLie — APPROVED** [review]
Looks good to me! I've noticed several manual fixes, thanks for taking the time to do this!

**Comment by TH3CHARLie** [comment]
I believe changeset at this scale requires at least another approval.

**Review by ilevkivskyi — APPROVED** [review]
Nice!

**Pull request merged**
