### PR TITLE
Enable use-before-def error code by default

### PR DESCRIPTION
**Pull request by ilinum**
This enables the error code added in #14163.

We aren't sure if it will cause too many problems. We can see what the mypy primer outputs as well.

### CODE REVIEW

**Comment by ilinum** [comment]
Looks like a lot of mypy_primer failures are from partially_defined not recognizing imports. I'll try to make it handle imports soon.

**Comment by AlexWaygood** [comment]
It looks like this check is triggering some hits in `.pyi` files. Maybe partially-defined checks should all be skipped for stub files, since they're never actually executed at runtime?

**Comment by AlexWaygood** [comment]
It looks like `sympy` has [a lot of code along the lines of](https://github.com/sympy/sympy/blob/ba5b3310bffc45c24efb6f474fd76693613544fc/sympy/core/kind.py#L314-L321):

```python
for i in range(2):
    if i == 0:
        foo = 1
    else:
        bar = foo
```

The partially-defined check can't understand that `foo` will always be defined here, and I'm not sure it's reasonable to ask it to understand code like that. Seems like `sympy` won't thank us, though :/

**Comment by ilinum** [comment]
> It looks like `sympy` has [a lot of code along the lines of](https://github.com/sympy/sympy/blob/ba5b3310bffc45c24efb6f474fd76693613544fc/sympy/core/kind.py#L314-L321):
> 
> ```python
> for i in range(2):
>     if i == 0:
>         foo = 1
>     else:
>         bar = foo
> ```
> 
> The partially-defined check can't understand that `foo` will always be defined here, and I'm not sure it's reasonable to ask it to understand code like that. Seems like `sympy` won't thank us, though :/

Yep, agreed.

We now have two checks in place: use-before-def and partially-defined. Potentially, we can call the example you listed as partially-defined and accept that it will have a higher false-positive rate. That way use-before-def will have a lower false-positive rate and makes more sense to enable it by default/have users not disable it.

**Comment by AlexWaygood** [comment]
> Potentially, we can call the example you listed as partially-defined and accept that it will have a higher false-positive rate. That way use-before-def will have a lower false-positive rate and makes more sense to enable it by default/have users not disable it.

I think that would be a good idea, if it's not too difficult to do. Just the difference in error message is quite significant imo — `Name "foo" is used before definition` is a _lot_ more sure of itself than `Name "foo" may be undefined`.

(Thanks for all the work you've been doing on this btw — this is a great feature!)

**Comment by ilinum** [comment]
#14175 has the fixes from this PR but doesn't enable use-before-def by default.

**Comment by ilinum** [comment]
After #14175 is merged, we will have the following false-positives causes for `use-before-def` check (roughly in the order of common they are):
1. Issues with try/except (should be fixed by #14114).
2. Loops that execute different code on first iteration ([example](https://github.com/sympy/sympy/blob/ba5b3310bffc45c24efb6f474fd76693613544fc/sympy/core/operations.py#L659)).
3. A version of the loop thing above but the variable is used in else, not in for ([example](https://github.com/sympy/sympy/blob/ba5b3310bffc45c24efb6f474fd76693613544fc/sympy/core/exprtools.py#L1479)).
4. Function uses a global scope variable but function definition comes before the variable definition. ([example](https://github.com/google/jax/blob/ac77286dbf4d3426c9d3ce5304bc18392581736f/jax/_src/config.py#L167))

As Alex and I discussed above, solving (2) and (3) is difficult/not feasible to handle correctly in the near term. I'll probably send a PR to move detection of these to the `partially-defined` check, so that `use-before-def` has fewer false positives.

I'm not sure what we can do for (4). Most of these seem to be when using `global`, so we can try to treat doing `global foo` as a definition of `foo`.

@AlexWaygood @JukkaL @ilevkivskyi do you have thoughts?

**Comment by ilinum** [comment]
#14176 moves the false positives from (2) and (3) to partially defined check.

**Comment by ilevkivskyi** [comment]
I think (4) should be "may be undefined", because if you call function before variable definition, it will be undefined. IMO (2) should be "may be undefined", if we are within a loop, and "use before definition" otherwise. (3) looks like a bug in their code, if the iterable is empty, the `else` branch will raise an `UnboundLocalError`, but in this case "may be undefined" is also better.

**Comment by ilevkivskyi** [comment]
Btw, if we are going to enable this by default, do we still need the `Cannot determine type` error? It looks like it only appears in use before definition scenarios (unless I am missing something). Also it is quite cryptic TBH. @JukkaL what do you think?

**Comment by ilinum** [comment]
I've formatted the primer output, so that it's a bit easier to follow the links [here](https://gist.github.com/ilinum/68ff1592258578e1228a04bb12ac7844?permalink_comment_id=4385380#gistcomment-4385380).

I believe we can't do much about most of the errors reported now.

**Comment by cdce8p** [comment]
> I believe we can't do much about most of the errors reported now.

Just checked the output for Home-Assistant. Almost all errors are because of variables defined in inside a `try` block. For example
```py
class SomeCls:
    def some_unsafe_func(self) -> None: ...

try:
    var = SomeCls()
    var.some_unsafe_func()
except Exception:
    print(var)  # use-before-def
```

True, in most cases `var` could also be defined outside the try-block. However, evident by the number of errors, this rarely happens. I guess one reason might be that keeping it together is a bit easier to read but there might be others, too.

In the [spirit of limiting false-positives](https://github.com/python/mypy/issues/14213#issuecomment-1329804673) for `use-before-def`, I would recommend to change that to `partially-defined`.

--
One other thing, every time I read the error code `use-before-def` something feels strange. Was `used-before-def` (`use` -> `used`) ever considered? That feels more natural to me. Since it hasn't been released yet, we should still be able to change it.

**Comment by ilevkivskyi** [comment]
@ilinum Just wanted to agree with Marc, the only case where it should be `use-before-def` is when definition is the last (or only) statement nested within `try` (like in `tornado` btw, mypy found a real bug there). In other cases it should definitely be `partially-defined`.

**Comment by ilinum** [comment]
Changed that error to report partially-defined. Let's see what mypy-primer says.

> One other thing, every time I read the error code use-before-def something feels strange. Was used-before-def (use -> used) ever considered? That feels more natural to me. Since it hasn't been released yet, we should still be able to change it.
I've been thinking about changing the error codes as well. I opened #14226, we can discuss there.

**Comment by ilevkivskyi** [comment]
@ilinum Great job, this looks almost ready to be merged! I think the error in `pyspark` is false positive (other three are real errors mypy found, which shows the importance of this check). We probably need to special case builtin name when you used at global and class scopes. They should be considered always defined there.

**Comment by ilinum** [comment]
> @ilinum Great job, this looks almost ready to be merged! I think the error in `pyspark` is false positive (other three are real errors mypy found, which shows the importance of this check). We probably need to special case builtin name when you used at global and class scopes. They should be considered always defined there.

Yes, I've been staring at this and I'm not quite sure why the pyspark one is failing. When I try to repro by copying the file from pyspark, it works just fine (no error).
We have logic to handle exactly this (see [refers_to_builtin](https://github.com/python/mypy/blob/d391f108c195533a5800afe73f5b3257babc83a3/mypy/partially_defined.py#L583)). This logic gets triggered on my test case.
Does mypy primer run the actual config of the project? I'm wondering if they have some flags enabled that makes range not resolve to `builtins.range`.

There are also a *ton* of test cases to fix, so I'm working on that :)

**Comment by AlexWaygood** [comment]
> Does mypy primer run the actual config of the project?

The config mypy primer uses when checking pyspark is here: https://github.com/hauntsaninja/mypy_primer/blob/79e975ad5d224ab0259c92dc4c1b7bccc854be68/mypy_primer.py#L1379

**Comment by ilinum** [comment]
Assuming tests pass, all that's remaining should be:
[] fix that `range` false positive in pyspark
[] merge #14351 and #14350 (both are included in the this PRs branch)

**Review by JukkaL — APPROVED** [review]
Looks good to me. It's exciting to have mypy finally detect undefined variables!

**Comment by JukkaL** [comment]
> Is this not a false positive?

Yes. We decided that it is still acceptable to merge PR, since there is only one false positive and this also finds real errors. Created #14476 to track the false positive.

**Pull request merged**
