### PR TITLE
Add console scripts

### PR DESCRIPTION
**Pull request by ethanhs**
This replaces the current scripts installed with setuptool's console_script entry points (this is done for mypy and stubgen). I also wrote a test that checks installing the wheel works.

~~WIP~~

### CODE REVIEW

**Comment by ethanhs** [comment]
Okay, so for Travis/Linux, it seems I need to be more clever in how I run python. For Windows, I have no idea why it won't accept `bdist_wheel`, as `wheel` is installed... I will continue to investigate.

**Comment by gvanrossum** [comment]
@ethanhs Do you still want to work on this? There's a couple of TODOs in previous comments, plus a merge conflict.

**Comment by ethanhs** [comment]
I do want to do this. I haven't have time to work on it, and it is rather complicated, but my semester ends this week so I should have significantly more time to work on it soon.

**Comment by gvanrossum** [comment]
OK then we'll keep it open! I'll mark it blocked until you add a comment that you're ready for a review.

**Comment by ethanhs** [comment]
Well, I think I might have inadvertently broke the CI, so that might need to be re-run. However, I believe this is ready for review.

**Comment by ethanhs** [comment]
I originally was going to also do a wheel install test, but that got overly complicated, so I want to put more thought into it and I'll wait for another PR for that.

**Comment by gvanrossum** [comment]
I wonder if scripts/stubgen and scripts/mypy.bat should be preserved even if they're not installed any more? After all you're still keeping scripts/mypy. These all are super simple script files that perhaps aren't as robust as the setuptools entry points, but they also don't require as much machinery to exist. I sometimes like to run these scripts in an environment where I don't want to install mypy (not even using `pip install -e`).

Other than that this seems to work fine for me (Mac), so I will merge this after you've restored those two scripts (or convinced me that they should really go).

**Comment by ethanhs** [comment]
I deleted them as I thought they were entirely duplicates of the console scripts method. I left scripts/mypy as removing it caused the entire test suite to fail :^)

If you use them for other purposes than I can restore them. I see no issue with that.

**Comment by gvanrossum** [comment]
OK, please restore those two files.

**Comment by ethanhs** [comment]
🖒 will do when I get in front of a computer again.

**Comment by ethanhs** [comment]
Okay, I restored those two scripts. Let me know if there is any other feedback.

**Pull request merged**
