### PR TITLE
Teach mypy about NoReturn

### LINKED ISSUE #2474: Warn no return doesn't understand six.reraise
As far as I can tell, mypy doesn't currently have any special knowledge of `six`, so it doesn't understand that `six.reraise` raises an exception.  If mypy having special understanding of six seems reasonable, we should add this.

### PR DESCRIPTION
**Pull request by ddfisher**
Fixes #2474.

### CODE REVIEW

**Comment by ddfisher** [comment]
One thing this doesn't do is disallow use of `NoReturn` in places other than as a return type, as there didn't seem to be a great way to do that, and it doesn't seem too important (because you'll get a reasonable-looking type error pretty quickly).

**Comment by ddfisher** [comment]
I'm not sure I agree that using `NoReturn` in those places should be an error.  Sure, it's weird, but type-theoretically there's nothing wrong with it.

Added tests for the last two bullets.

**Comment by gvanrossum** [comment]
I'd say that for the first three bullets, the expression *containing* the call itself inherits the "doesn't return" property. So then this should lead to some dead code, depending on the control flow. E.g. here I'd expect the final line of the function to be unreachable (given the above definition of `no_return()`):
```python
def f() -> int:
    no_return()
    does_not_exist()  # Not a NameError because it's unreachable
```
I don't feel to strongly about all this though, so I personally am fine with however you and Jukka decide this.

**Comment by ddfisher** [comment]
Currently we don't check for unreachable code, though.  E.g.
```python
def f() -> None:
  return
  does_not_exist()  # E: Name 'does_not_exist' is not defined
```

**Comment by JukkaL** [comment]
Agreed that some of the cases I listed aren't real type errors, but they are at least pretty questionable and likely signs of code quality issues. I don't expect those cases to be common in the wild, so the current behavior is already okay.

(We already reject arguably similar cases, such as using the return value of a function with a `None` return type, even if `None` would be valid value in some context.)

**Pull request merged**
