### PR TITLE
Do semantic analysis on lambda's bodies

### LINKED ISSUE #4098: Semantic analysis error not reported within lambda
This doesn't generate an error, though it's clearly invalid:

```py
lambda: xyz
```

This generates an error:

```py
lambda: 1 + ''
```

It looks like type checking errors are reported within a lambda but semantic analysis errors are lost. 

This is not a regression -- this bug has been around for a long time.

### PR DESCRIPTION
**Pull request by ethanhs**
Lambdas were seen as dynamic functions when going to report errors. This
changes them to not be dynamic functions and report semantic analysis
errors in their bodies.
Fixes #4098

The relevant check for `is_dynamic()` is here:
https://github.com/python/mypy/blob/b240125f96949b35dc2ad54c3707fd3dca5d170b/mypy/semanal.py#L3790

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
I think it is worth adding few tests for this.

**Comment by ethanhs** [comment]
D'oh it appears I forgot to check in the tests I wrote. Just pushed them.

**Comment by gvanrossum** [comment]
Nice, but it's introducing a new form of error. Here's an example:
```py
from typing import Callable
def f() -> Callable[[], int]:
    a = lambda: b  # error: Name 'b' is not defined
    b = 42
    return a
assert f()() == 42
```
I wouldn't mind so much except I'm seeing this example in a few places in our existing codebase where fixing it would be somewhat awkward (the lambda is passed as a callback to something that must exist before some local variable can be set -- but the callback won't be called until after that's taken care of).

**Comment by ilevkivskyi** [comment]
I think with PEP 526 this can be safely fixed by ``b: int`` somewhere at the right scope. Otherwise ``# type: ignore`` here I think is still better than uncaught errors somewhere else. (There seem to be no middle ground here, either lambdas are considered dynamic and not typechecked, or they are always checked.)

**Comment by gvanrossum** [comment]
Fair enough, I'll try to work around these.

**Pull request merged**
