### PR TITLE
Make reveal_type() a note when --shadow-file is used.

### PR DESCRIPTION
**Pull request by gvanrossum**
@ddfisher -- What do you think of this hack?

### CODE REVIEW

**Comment by ddfisher** [comment]
Is there a compelling reason to do this?  I'd expect `--shadow-file` to only be used by other tools, which are likely to munge the output before presenting it to the user.  Not sure what we'd gain from this special casing.

**Comment by gvanrossum** [comment]
It's been a while since I tried this. I think I wanted the exit status to be 0 if the only output was from reveal_type(), so that the driving script could better determine the difference between success and failure. But I agree it's too minor. Closing.

**Comment by Michael0x2a** [comment]
I'm a little late to this, but I just wanted to add that a possible reason we might have wanted to do this is because incremental mode won't cache a module/will need to recheck the SCC the module belongs to when there's any sort of errors, such as the error created by reveal_type.

I don't quite remember what `--shadow-file` was supposed to do though (something about editor integration?), and how exactly it interacts with incremental, so idk if this is relevant.

**Comment by ddfisher** [comment]
Yeah, it's so editors can run mypy against modified versions of a file without having to change it in-place.  I think we don't want incremental to cache the module when `--shadow-file` is used, actually, so this is a good side-effect!

**Comment by gvanrossum** [comment]
@ddfisher You've convinced me!

**Pull request closed without merging**
