### PR TITLE
Have --package usage respect mypy_path

### PR DESCRIPTION
**Pull request by abatilo**
Addresses:
https://github.com/python/mypy/issues/6595

### CODE REVIEW

**Comment by blueyed** [comment]
Needs a test (https://github.com/python/mypy/issues/6595#issuecomment-477238517), but maybe wait for some other feedback first.

**Comment by ethanhs** [comment]
@abatilo I believe you can make a modified version of [this test case](https://github.com/python/mypy/blob/master/mypy/test/testpep561.py#L208) where you write a `mypy.ini` in `venv_dir` and pass that with `--config-file` to mypy. Leave a message when you are done and I can review this.

**Comment by abatilo** [comment]
@ethanhs After much fighting with the CI checks, I think I finally have a test that I can be proud of, and one that did in fact fail before the accompanying change was made. Please let me know if there's anything I need to change!

**Comment by ethanhs** [comment]
@abatilo sorry for the delay, I will review this tomorrow.

**Comment by abatilo** [comment]
My first OSS contribution!!! :D

**Comment by ethanhs** [comment]
Unless someone else wants to review this/has further feedback I will merge this tomorrow.

**Comment by abatilo** [comment]
@ethanhs Ping on this.

**Comment by ethanhs** [comment]
@abatilo Thank you for your contribution!

**Pull request merged**
