### PR TITLE
Move variance docs to new page

### PR DESCRIPTION
**Pull request by quartox**
Variance is one of the most confusing topics for novice users. We want to link to this page directly in error messages relating to variance and put it in a single page to be easier to find.

### CODE REVIEW

**Comment by quartox** [comment]
@gnprice

**Comment by gnprice** [comment]
Thanks! Looking.

Would you add just a sentence or two to the description explaining the motivation for this? (That'll become the commit message when we "squash and merge" the change in.) Basically that we want a stable, short-named place to link to in error messages, like #3411 .

Also a small comment: I think the `..  invariance-vs-covariance:` bit can be dropped -- it existed to create an anchor for a link like `#invariance-vs-covariance` to point to this section in the middle of the long page.

**Comment by quartox** [comment]
I just edited the top comment with the description, is that the message that will be added when squashing? or do I need to put it somewhere else.

**Comment by quartox** [comment]
If we are fine with this I can update the other PR with the new link.

**Comment by quartox** [comment]
Or make more changes as we started discussing.

**Comment by gvanrossum** [comment]
I'm confused -- I thought we were going to move the text to a new page? Did the plan change? (AFAIK Greg tried to create an alias on RTD and it didn't work.)

**Comment by quartox** [comment]
@gnprice argued for just changing the alias and restructuring the docs but we never finished the conversation. We should mark this WIP, but I am following his recommendation and don't have a clear idea for how to enhance the docs myself.

**Comment by gvanrossum** [comment]
IIUC the most recent conversation I had about this (some time Monday) was that aliases don't even work and even if they did would be too fragile (and depend on RTD hosting). I even recall @gnprice leaving some comments describing the (negative) outcome of his experiments somewhere, but I cannot find them now.

**Comment by quartox** [comment]
The conversation we had was to simply make the alias shorter. I feel like variance might justify its own section since it is such a confusing topic to newcomers. @gnprice was worried about developing a pattern of adding documentation urls to error messages and ending up with too many top level urls. He was thinking of creating a single page with all of the urls in error messages and renaming/refactoring the "common problems" page to serve that purpose. 

The initial part of this process was shortening the anchor for the variance discussion, but it is not a very coherent pull request as is, just a half formed idea.

**Comment by quartox** [comment]
Sadly this was all in person so it is all a second hand discussion right now.

**Comment by gvanrossum** [comment]
IIUC @gnprice will be back at the sprint tomorrow to set us straight.

**Comment by gvanrossum** [comment]
I talked it over with @gnprice off-line and the conclusion was that a separate variance page is *not* needed. (The problem with '#' in error messages was solved separately in #3417.)

However this PR still looks like it needs work, since the revision_history.rst page also references this anchor.

**Comment by gvanrossum** [comment]
I talked it over with @gnprice off-line and the conclusion was that a separate variance page is *not* needed. (The problem with '#' in error messages was solved separately in #3417.)

However this PR still looks like it needs work, since the revision_history.rst page also references this anchor.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
