### PR TITLE
Support ParamSpec variables in type aliases

### LINKED ISSUE #4987: Do not leak UnboundTypes to type checking
Sometimes `UnboundType` leaks to type checking, this is not good because it can lead to crashes like this:
```
File ".../mypy/subtypes.py", line 814, in <listcomp>
if (not (is_proper_subtype(erase_type(item), erased_s) or
File ".../mypy/erasetype.py", line 25, in erase_type
return typ.accept(EraseTypeVisitor())
File ".../mypy/types.py", line 194, in accept
return visitor.visit_unbound_type(self)
File ".../mypy/erasetype.py", line 31, in visit_unbound_type
assert False, 'Not supported'
AssertionError: Not supported
```
It would be better to replace all `UnboundType`s with `Any` (after an error is reported).

### LINKED ISSUE #7084: Ban bogus "existential types"
It is possible to get an unbound type variable in a variable type using a generic alias, for example:
```python
from typing import TypeVar, Dict
  
T = TypeVar('T')
Alias = Dict[str, T]

x: Alias[T]
reveal_type(x)  # Revealed type is 'builtins.dict[builtins.str, T?]'
```
This doesn't makes sense currently and should give an error.

See also https://github.com/python/mypy/issues/6520 (this looks very similar but is actually a different issue specific to type aliases).

### LINKED ISSUE #10445: TypeVar bound is ignored in generic alias
**Bug Report**

A generic alias using a TypeVar with a bound allows type arguments that don't match the bound

**To Reproduce**

```
% cat tvbound.py 
import typing

FooT = typing.TypeVar("FooT", bound=str)
FooIsh = typing.Union[int, FooT]

bat2: FooIsh[float] = 1.0

% mypy tvbound.py
Success: no issues found in 1 source file
% mypy --version
mypy 0.820+dev.e8afde621531880c2b9c51acba8e565a29cde0b1
```

**Expected Behavior**

I would expect an error saying that the value of `FooT` cannot be `float`.

Found this as a result of https://github.com/microsoft/pyright/issues/1839.

### LINKED ISSUE #11855: Type Aliases that are generic over ParamSpec don't work
**Bug Report**

I expect `n = Callable[P, int]` to work, or at least `n: TypeAlias = Callable[P, int]`

**To Reproduce**

```py
from typing import ParamSpec, Callable, TypeAlias

P = ParamSpec("P")

c: TypeAlias = Callable[P, int]

def f(n: c[P]) -> c[P]:
    ...
```

**Expected Behavior**

No errors

**Actual Behavior**

```
main.py:5: error: Variable "typing.TypeAlias" is not valid as a type
main.py:5: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
main.py:7: error: Variable "__main__.c" is not valid as a type
main.py:7: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
main.py:7: error: Invalid location for ParamSpec "P"
main.py:7: note: You can use ParamSpec as the first argument to Callable, e.g., 'Callable[P, int]'
```

**Your Environment**

[mypy playground](https://mypy-play.net/?mypy=latest&python=3.10&gist=37af730199c7e3e4124eb5bedbbe0e42)

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fixes #11855 
Fixes #7084
Fixes #10445
Should fix #4987

After thinking about this for some time, it looks like the best way to implement this is by switching type aliases from unbound to bound type variables. Then I can essentially simply share (or copy in one small place, to avoid cyclic imports) all the logic that currently exists for `ParamSpec` and `Concatenate` in `expand_type()` etc.

This will also address a big piece of tech debt, and will get some benefits (almost) for free, such as checking bounds/values for alias type variables, and much tighter handling of unbound type variables.

Note that in this PR I change logic for emitting some errors, I try to avoid showing multiple errors for the same location/reason. But this is not an essential part of this PR (it is just some test cases would otherwise fail with even more error messages), I can reconsider if there are objections.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
Oh it looks like there is a merge race with one of my other PRs, should be easy to rebase.

**Comment by ilevkivskyi** [comment]
On the `mypy_primer`:
* Some remaining errors in `discord.py` look like mypy is struggling with type inference for unions, doesn't look like a bug in this PR
* `psycopg` is doing `Foo: "TypeAlias" = Bar[T]` in two places, where `TypeAlias` is never imported, so technically the errors are correct
* There are two things in `Expression`. One is exposed existing bug that "skip-level" type variables are not bound correctly in functions nested in generic functions. Second one is less clear, but unlikely to caused by this PR, probably also existing issue.

I will try to see if there are easy fixes to the things in `Expression` to minimize the fallout of this PR.

**Comment by ilevkivskyi** [comment]
@jhance @JukkaL @hauntsaninja Can one of you please take a look at this? It would be great to have a second pair of eyes, maybe I missed something (this PR includes a significant refactoring in how type aliases internals).

**Comment by JukkaL** [comment]
I did some manual testing, and this seems to generate a false positive when defining a type alias:
```py
from typing import ParamSpec, Callable

P = ParamSpec("P")

# Error: The first argument to Callable must be a list of types, parameter specification, or "..."
A = list[Callable[P, None]]

f: A[[int, str]]
reveal_type(f)  # builtins.list[def (builtins.int, builtins.str)] (seems fine)
```

**Comment by gandhis1** [comment]
As @erictraut mentioned [in this comment](https://github.com/python/mypy/issues/14069#issuecomment-1312188384), the tests that he put together for pyright may be useful for PRs like this one to test edge cases of `ParamSpec` and `Concatenate`. Probably only a handful of repos in mypy primer scope have even begun to use this feature. Maybe it makes sense to bring them over, see which ones fail, and then selectively disable test cases that are known to be unsupported?

**Comment by JukkaL** [comment]
We can now leak type lists into inferred types, which could cause problems (e.g. crashes) since type lists are not generally expected as types, I think:
```py
from typing import ParamSpec, Callable, Concatenate, TypeVar

T = TypeVar("T")
P = ParamSpec("P")

A = Callable[Concatenate[T, P], None]

# Type argument "[int, str]" of "A" must be a subtype of "object"
f: A[[int, str], [str, float]]
reveal_type(f)  # def ([builtins.int, builtins.str], builtins.str, builtins.float)
```

**Comment by ilevkivskyi** [comment]
@JukkaL Thanks! I fixed the first one (and also a similar one with `Concatenate`), will push soon. For the second one there should be an easy fix, we just need to replace invalid args with `Any`.

**Comment by ilevkivskyi** [comment]
Btw this second issue affects regular instances as well (I am fixing both anyway)

**Comment by JukkaL** [comment]
> Maybe it makes sense to bring them over, see which ones fail, and then selectively disable test cases that are known to be unsupported?

This could be helpful, since we've had a bunch of ParamSpec edge cases that we've been fixing gradually. We can do it in a separate PR, except maybe for test cases that involve type aliases.

@ilevkivskyi Do you want to have a look if there are any relevant test cases you could include in this PR?

**Comment by ilevkivskyi** [comment]
TBH I don't have desire to go through them, I would rather spend time working on default arguments in generics. I made this PR because I know type aliases, not because I know `ParamSpec` :-)

FWIW I think the best way may be if a volunteer would run that cases (and not just `ParamSpec` ones), and opens issues for failing ones (where it makes sense, e.g. not a duplicate).

**Comment by ilevkivskyi** [comment]
@JukkaL 
> We can now leak type lists into inferred types

Btw those are not type lists they are `Parameters` with a nice repr. Actually it looks like trying to replace them in `semanal_typeargs` conflicts with `TypeVarTuple`s. So since it is not a new bug, I will leave it as is.

Btw @jhance it looks like `semanal_typeargs` is already broken for `TypeVarTuple`s, the loop in `visit_instance` will compare type vars with wrong arguments and vice versa.

**Review by JukkaL — APPROVED** [review]
LGTM now!

**Pull request merged**
