### PR TITLE
Support isinstance with a tuple of types

### LINKED ISSUE #1328: isinstance(x, (t1, t2)) doesn't change mypy's knowledge of x's type.
For example in the following code:
```
def f(x):
  # type: (object) -> list
  if isinstance(x, (list, set)):
    return [g(i) for i in x]
```
mypy will complain that an `Iterable` is expected (it still only sees `x` as an `object`). This can be resolved with e.g. a manual `cast` of `x` to `Union[list, set]`, but this adds a slight overhead and isn't as clean.

### PR DESCRIPTION
**Pull request by kirbyfan64**
Closes #1328.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Are you going to fix the test failures?

**Comment by kirbyfan64** [comment]
@gvanrossum Well, that's weird...all the tests passed when I ran them with `./runtests.py unit-test -a check-isinstance` but fail with `./runtests.py unit-test check-isinstance`. Fixing now...

**Comment by kirbyfan64** [comment]
Huh...I'm not sure what's up with the last test failure. The code is definitely correct (the type of `s` in changed to `Union[str, bytes]`), but I'm not exactly sure why it isn't matching with `AnyStr`.

**Comment by gvanrossum** [comment]
I think the -a optionneeds a pattern staring and ending with *, so e.g.
`./runtests.py unit-test -a '*check-isinstance*'` .

The difference between AnyStr and Union[str, bytes] is that AnyStr is a
type variable. Maybe that helps?

**Comment by kirbyfan64** [comment]
Travis should re-run now.

**Comment by kirbyfan64** [comment]
TESTS ARE FINALLY GREEN!!! :D

**Comment by gvanrossum** [comment]
Thanks so much!

**Pull request merged**
