### PR TITLE
mypy and mypy_extensions aren't posix only

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by ethanhs** [comment]
Alternatively, we can replace it with `platforms=['any'],`. Since we support windows and Mac OS, we probably should indicate in the package metadata that is so.

**Comment by graingert** [comment]
I guess it depends on whether you take the flag to mean platforms required,
or platforms supported

**Comment by ethanhs** [comment]
@graingert If you merge master and update this today, it could probably make it in time for 0.570.

**Comment by gvanrossum** [comment]
I fixed the merge conflict. Once the tests pass it can be merged.

**Pull request merged**
