### PR TITLE
Remove bundled lib-typing

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This gets rid of code duplication and makes sure mypy works with the released version of typing. This doesn't fix any immediate issue, but I saw some comments in the bug tracker saying that we should be able to get rid of lib-typing eventually.

There is a major downside: To run mypy tests locally, you will now have to have a Python 2.7 installed that has `typing` available. If that's not acceptable, we're probably better off just keeping lib-typing as is.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Travis is failing because when running with Python 3, there is a `python2` binary available but we don't have permissions to install new packages for it. I can't currently think of a clean way to fix that. I'll keep this PR open for a few more days in case I think of something and otherwise close this.

**Comment by ethanhs** [comment]
Travis uses virtualenvs for each Python version. Since you call raw `python2` it uses the system install. The simplest fix in my mind is to make a local Python2 install via another virtualenv eg:

```bash
virtualenv -p /usr/bin/python2 py2
alias python2=$PWD"/py2/bin/python2"
python2 -m pip install -U typing
```

I checked this process and I believe it should work if mypy can deal with the slightly strange python2 install. My main concern with this process is that it is a bit of a hack, and the added overhead of starting a new virtualenv. I also have not tested this on travis itself.

**Comment by MasterOdin** [comment]
Another option would be to use the `--user` flag on pip install which does not require sudo access, and will still have typing available on the path. Seems to work fine and leads to a green travis build: https://travis-ci.org/MasterOdin/mypy/builds/231940206

**Comment by ethanhs** [comment]
I just read through everything, LGTM. 👍

**Comment by JelleZijlstra** [comment]
Looks like this change doesn't slow down Travis: run time for this PR is about the same as for other recent PRs.

**Comment by gvanrossum** [comment]
W00t! This has been on my list for a long time. Thanks for figuring out how to make it work and documenting it.

**Pull request merged**
