### PR TITLE
Disable universal newlines when reading TOML

### PR DESCRIPTION
**Pull request by hukkin**
Reading a file with universal newlines is not TOML compatible.

See e.g. https://github.com/toml-lang/toml/issues/837 for context.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
(I believe the current plan for this PR is to follow the lead of https://github.com/pypa/pip/pull/10238#discussion_r680121388 )

**Comment by JelleZijlstra** [comment]
Yes. I assigned myself this PR and the corresponding one to Black and I plan to follow pip's decision.

**Comment by ethanhs** [comment]
It would appear that pip is going to do `tomli.loads(f.read())` while making sure the encoding is utf-8, I suppose we should probably do the same here.

**Comment by ilevkivskyi** [comment]
I am going to apply the changes to unblock the release (also it looks like this is what black is doing).

**Review by ilevkivskyi — APPROVED** [review]

**Pull request merged**
