### PR TITLE
Fix incomplete error codes documentation

### PR DESCRIPTION
**Pull request by revolter**
### Have you read the [Contributing Guidelines](https://github.com/python/mypy/blob/master/CONTRIBUTING.md)?

(Once you have, delete this section. If you leave it in, your PR may be closed without action.)

### Description

(Explain how this PR changes mypy.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

### CODE REVIEW

**Comment by TH3CHARLie** [comment]
This has been covered in https://mypy.readthedocs.io/en/stable/config_file.html?highlight=config%20file

**Comment by revolter** [comment]
Indeed, but after Googling something, I found https://mypy.readthedocs.io/en/stable/error_codes.html instead. And, because there are 2 ways to do 1 thing, it doesn't make sense to mention only one in a generic article like the "Error codes" one.

**Comment by revolter** [comment]
Do you think that this small change has any drawbacks?

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
I don't think a small amount of redundancy in the documentation hurts.

**Pull request merged**
