### PR TITLE
refactor: use contextlib.suppress instead of `except Exception: pass`

### PR DESCRIPTION
**Pull request by kkirsche**
### Description

The Mypy application currently requires Python 3.7+ per https://github.com/python/mypy/blob/master/setup.py#L10

`contextlib.suppress` was added in Python 3.4:
https://docs.python.org/3/library/contextlib.html#contextlib.suppress

The context manager slightly shortens the code and significantly clarifies the author's intention to ignore the specific errors. The standard library feature was introduced following a [discussion](https://bugs.python.org/issue15806), where the consensus was that

> A key benefit here is in the priming effect for readers... The with statement form makes it clear before you start reading the code that certain exceptions won't propagate.

## Test Plan

N/A

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
IMO only 40% of these are improvements.
- The one in checkexpr can be fairly hot. contextlib.suppress is slower
- The ones with comments I find much more readable when the comment is in the except
- Several of these are instances where I feel the priming is distracting / "try" is enough priming.

(Apologies in case that's an annoying review, but bikeshed-y PRs are going to lead to bikeshedding ;-) )

**Comment by kkirsche** [comment]
I trust you on this, but do you happen to have a benchmark that shows contextlib is slower? Generally speaking, Python performs functions faster than straight code which leads to why a main() function called from `if __name__ == “__main__”` can be faster. The exceptions are usually when the piece gets moved into C code rather than Python, such as list comprehensions instead of for loops.

Happy to make the requested changes when I have a chance :)

**Comment by hauntsaninja** [comment]
I get 4x slower with Python 3.11
```
In [1]: import contextlib

In [2]: def f():
   ...:     x = {1: 2}
   ...:     with contextlib.suppress():
   ...:         return x[1]
   ...: 

In [3]: %timeit f()
431 ns ± 0.72 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [4]: def g():
   ...:     x = {1: 2}
   ...:     try:
   ...:         return x[1]
   ...:     except KeyError:
   ...:         pass
   ...: 

In [5]: %timeit g()
103 ns ± 0.103 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

Re: bikeshed, https://en.wikipedia.org/wiki/Law_of_triviality

**Comment by JelleZijlstra** [comment]
> I trust you on this, but do you happen to have a benchmark that shows contextlib is slower? Generally speaking, Python performs functions faster than straight code which leads to why a main() function called from `if __name__ == “__main__”` can be faster. 

This is true when comparing code that executes in the module (or class) scope against code that executes in a function scope. Function scopes indeed execute faster, primarily because local variable access is just an array access instead of going through a hash table. But that's not what you're changing here; all the code is already within a function. `contextlib.suppress` is implemented in Python, so adding usage of it incurs function call overhead (three times: for its `__init__`, `__enter__`, and `__exit__` methods).

**Comment by kkirsche** [comment]
> Several of these are instances where I feel the priming is distracting / "try" is enough priming.

without knowing which you mean, and paired with the bikeshedding comment, it sounds like this change isn't valued. So I'm going to close this since it doesn't sound like it's actually valued here.

**Comment by kkirsche** [comment]
> > I trust you on this, but do you happen to have a benchmark that shows contextlib is slower? Generally speaking, Python performs functions faster than straight code which leads to why a main() function called from `if __name__ == “__main__”` can be faster.
> 
> This is true when comparing code that executes in the module (or class) scope against code that executes in a function scope. Function scopes indeed execute faster, primarily because local variable access is just an array access instead of going through a hash table. But that's not what you're changing here; all the code is already within a function. `contextlib.suppress` is implemented in Python, so adding usage of it incurs function call overhead (three times: for its `__init__`, `__enter__`, and `__exit__` methods).

I appreciate the explanation for why this is. I didn't understand that. Thank you

**Pull request closed without merging**
