### PR TITLE
Fix type inference in pattern matching by positional argument

### PR DESCRIPTION
**Pull request by sobolevn**
Oh, this was very interesting.
During the debug sessions I learned a lot about how pattern matching and its analysis do work.

But, the problem was that `expand_type` did not preserve `.last_known_value` for some reason.
I used `.copy_modified` to preserve everything we know about `Instance`.

However, I expect that some tests might fail now. This code even has something similar in `TODO` some lines above: 

https://github.com/python/mypy/blob/88aed94ae3de2542491f6cd65d1236c4f0cdedb1/mypy/expandtype.py#L144-L148

Let's see what will happen.

Closes https://github.com/python/mypy/issues/13612

### CODE REVIEW

**Comment by ariebovenberg** [comment]
@sobolevn a good surprise indeed! Tests look comprehensive enough. 

I wonder, does it also run correctly with inheritance? (Note `a: Base[str] = ...` alias)

```python
class Base(Generic[T]):
    ...

@dataclass
class A(Base[T]):
    x: T


a: Base[str] = A("foo")
reveal_type(a)  # A[str] (correct)

match a:
    case A(b):
        reveal_type(b)  # Any (incorrect! Should be builtins.str)
```

**Comment by sobolevn** [comment]
I will add a test case for subclasses and dataclasses. Thanks!

**Comment by sobolevn** [comment]
Ok, this indeed does not work for `Generic` subclasses. But, I belive that it is something different.

Let's open a new issue for it. Can you, @ariebovenberg? 🙂

**Review by ilevkivskyi — APPROVED** [review]

**Comment by sobolevn** [comment]
@thomkeh hi, can you please share any context on your commit? Is there something wrong?

**Comment by thomkeh** [comment]
Oh sorry, I clicked the "revert" button accidentally! I didn't know this was possible.

Everything is fine as far as I know.

**Pull request merged**
