### PR TITLE
(🐞) Fix CI python interpreter

### PR DESCRIPTION
**Pull request by KotlinIsland**
image
:trollface: 

This change will mean that `tox -e type` will use your current interpreter instead of 3.7, this could be good or bad depending on how you look at it.

Also added an override in CI to not skip missing interpreters.

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Huh. Thanks for catching this. Any idea why / when it broke? Also why does it work on Windows? https://github.com/python/mypy/runs/7377272863?check_suite_focus=true

Other tox environments look to be affected too, e.g. flake8 (although I feel like I've had flake8 fail on me somewhat recently).

**Comment by hauntsaninja** [comment]
Okay, I see https://github.com/python/mypy/pull/13138

**Comment by KotlinIsland** [comment]
I have no idea why windows passed, probably due to mysterious property/setting that it has and the others don't

**Comment by KotlinIsland** [comment]
@hauntsaninja Do we actually want to run the type check with a 3.10 interpreter?

**Comment by hauntsaninja** [comment]
Running type check with 3.10 should be fine, see https://github.com/python/mypy/pull/13138/files#r922690360

**Comment by hauntsaninja** [comment]
We should also do something like https://github.com/tox-dev/tox/issues/631#issuecomment-329531800

**Comment by KotlinIsland** [comment]
> Running type check with 3.10 interpreter should be fine, see https://github.com/python/mypy/pull/13138/files#r922690360

I don't think that's the best bet: [playground](https://mypy-play.net/?mypy=latest&python=3.4&gist=e7b32d6d852f13e1058f6caa8becceee)

**Comment by hauntsaninja** [comment]
Hmm, fair point. It's on the verge of being too late, but here you go: https://github.com/python/cpython/pull/94948

**Comment by hauntsaninja** [comment]
Also https://github.com/python/cpython/pull/94950. Got any others? :-)

**Review by hauntsaninja — APPROVED** [review]
Thanks, this lgtm!

**Comment by hauntsaninja** [comment]
and `TOX_SKIP_MISSING_INTERPRETERS=False tox -e py33` seems to work great aka fail for me locally :-)

**Comment by KotlinIsland** [comment]
> Also https://github.com/python/cpython/pull/94950. Got any others? :-)


Pep 614
https://mypy-play.net/?mypy=latest&python=3.4&gist=bdeccf8b7851a63d3c42ccfe01d40583

**Comment by KotlinIsland** [comment]
> Also https://github.com/python/cpython/pull/94950. Got any others? :-)

`continue` in `finally`
https://mypy-play.net/?mypy=latest&python=3.4&gist=6fc06fbed1d50d37ed930f17fdb826fa

**Comment by KotlinIsland** [comment]
> Also https://github.com/python/cpython/pull/94950. Got any others? :-)

Unparenthesized unpack on `return`/`yield`
https://mypy-play.net/?mypy=latest&python=3.4&gist=3cc9d9f6a6d407b43d0722d28d33b32c

**Comment by KotlinIsland** [comment]
> Also https://github.com/python/cpython/pull/94950. Got any others? :-)

PEP 461 https://mypy-play.net/?mypy=latest&python=3.4&gist=118df5de911012759ae74530ce3f5cfd

**Comment by KotlinIsland** [comment]
> Also https://github.com/python/cpython/pull/94950. Got any others? :-)

Unparenthesized assignment expression in set literal, set comprehension and sequence index: https://mypy-play.net/?mypy=latest&python=3.9&gist=c344a87c9745e47cd55ef10c71f9e923

**Pull request merged**
