### PR TITLE
Move option processing into mypy/options.py

### PR DESCRIPTION
**Pull request by cpennington**
Per the discussion in #3388, this moves `process_options` into `mypy/options.py`.

### CODE REVIEW

**Comment by gvanrossum** [comment]
And let's hold off on this until we've got agreement on the design in the other PR.

**Comment by cpennington** [comment]
Yup, definitely.

**Comment by gvanrossum** [comment]
We should probably close this -- there's been no activity for 5 months, and the conclusion in #3432 suggests we won't need this specific refactoring. Also I honestly think that the changes here make things worse -- all the `if MYPY` and resulting forward-reference business feels like a code smell.

**Comment by ilevkivskyi** [comment]
Yes, there are also several conflicts, I think it makes sense to close this for now.

**Pull request closed without merging**
