### PR TITLE
Expand misc/fix_annotate.py (stub files, PEP484)

### PR DESCRIPTION
**Pull request by alvarocaceres**
* Added option to get types from .pyi stub file

* Added option to insert annotations in PEP484 style

* Added tests

* Renamed as py_annotate and moved to its own dir

Because of the addition of options and filename change, can no longer be
dropped into 2to3's fixes/ directory. Instead, meant to be used as a
standalone program (added main()).

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks! Given the size of your contribution I think it's better if you create a new toplevel GitHub project for this. That way you can update it without waiting for us for code reviews. We'd be happy to link to such a project.

TBH I don't have time to do this justice in a detailed code review. Question: does this infer types? Or does it just mechanically copy annotations from pyi files into corresponding py files?

**Comment by alvarocaceres** [comment]
That sounds good, just didn't want to branch off your code without checking if you preferred things to stay in your repo.

When there's no pyi file, it falls back to your logic for getting types from default values for ints, strings, etc -- no other inference is going on as our plan is to use it with pytype. This code is mainly about merging .py and .pyi files.

Do you have any use for the case where there's no pyi file and types are derived from default values? I kept it to stay in line with the original functionality, but don't have a need for it and was considering removing it.

**Comment by gvanrossum** [comment]
Actually, my version is intended to bootstrap inline annotations when there's no other source of annotations yet. Note that stubgen is no help because it doesn't know the types either. Go ahead and remove it then -- it seems our use cases are pretty much disjoint, so it makes sense the tools are different. (The offer of linking to your tool stands, of course.)

**Comment by alvarocaceres** [comment]
Created standalone repo at https://github.com/google/merge_pyi -- if you can link to it that'd be great, thanks.

**Pull request closed without merging**
