### PR TITLE
feat: auto-hide instructions when submitting

### LINKED ISSUE #15741: automatically hide issue instructions when submitting a new issue
# Current behavior

Contributors have to manually delete instructions in template.

https://github.com/python/mypy/assets/43425812/49243349-f257-4b87-9571-f6197bfa19cc

# Desired behavior

Instructions are written in Markdown and are hidden when posted.

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #15741.
(Explain how this PR changes mypy.)

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Without this change
https://github.com/python/mypy/assets/43425812/fca2a3d4-8627-4616-b31d-7a4596fbb523
# With this change
https://github.com/python/mypy/assets/43425812/5ecb810c-4c5d-4f7e-b478-2e1c0012dcfc

**Comment by hamirmahal** [comment]
@hauntsaninja let me know if there are any changes you'd like this PR to have.

**Review by hauntsaninja — APPROVED** [review]
Sure, thanks!

**Comment by hamirmahal** [comment]
You're welcome! Thanks for merging this.

**Pull request merged**
