### PR TITLE
Fix: Empty reveal locals ouput

### LINKED ISSUE #12388: (🐞) Empty reveal locals should have a better output
```py
reveal_locals()
```
```
> mypy test.py
test.py:1:1: note: Revealed local types are:
Success: no issues found in 1 source file
```

This looks like a bug, I would expect something like:
```
> mypy test.py
test.py:1:1: note: There are no locals to reveal
Success: no issues found in 1 source file
```

### PR DESCRIPTION
**Pull request by cibinmathew**
Fixes #12388

### CODE REVIEW

**Review by 97littleleaf11 — COMMENTED** [review]
The outer list comprehension could be simplified. Just move the format string to the first arg of self.note.

**Comment by cibinmathew** [comment]
> The outer list comprehension could be simplified. Just move the format string to the first arg of self.note.

@97littleleaf11 not sure if I got it correctly. 

Is it something like converting below 
```
for line in ['    {}: {}'.format(k, v) for k, v in sorted_locals.items()]:
    self.note(line, context)
```
to 
```
for line in sorted_locals.items():
    self.note('    {}: {}'.format(line[0], line[1]), context)
```

**Comment by jhance** [comment]
Flake8 issue is unrelated, FYI.

**Comment by cibinmathew** [comment]
added feedback changes.

**Pull request merged**
