### PR TITLE
Fix subtyping for type variables whose upper bound is a union

### LINKED ISSUE #2314: Bizarre error message when the bound of a typevar is a union
``` python
from typing import *

class X: pass

T = TypeVar('T', bound=Union[X, None])

class Y(Generic[T]):
    def __init__(self) -> None: pass
    attr: T
```

```
x.py: note: In function "__init__":
x.py: error: Type argument "T`1" of "Y" must be a subtype of "Union[x.X, builtins.None]"
```

If this is a user error, the error message should at least be a bit more like a, well, _normal_ error message.

### PR DESCRIPTION
**Pull request by rwbarton**
Fixes #2314.

### CODE REVIEW

**Comment by rwbarton** [comment]
This needs new tests and I have to disappear for a while, but this is the proposed code change.

**Comment by gvanrossum** [comment]
This is WIP right? Do you have time to add a test?

**Comment by rwbarton** [comment]
Yes, I'll add a test later.

**Comment by gvanrossum** [comment]
Hey @rwbarton, are you still interested in working on this? It's been 6 weeks without activity here...

**Comment by gvanrossum** [comment]
@rwbarton Do you have some time to complete this? Or should we try to get someone else to fix this?

**Comment by ilevkivskyi** [comment]
Closing in favor of #3039 that was merged recently.

**Pull request closed without merging**
