### PR TITLE
Enum: deal with subclasses of Enum or IntEnum

### PR DESCRIPTION
**Pull request by wittekm**
I previously committed #1535 so that IntEnums would behave better, but I figured out that it breaks if you subclass the IntEnum (a real use case in the Dropbox codebase). Same with Enum.

That is to say, the allowed sample in [Enum docs 8.3.19](https://docs.python.org/3/library/enum.html#restricted-subclassing-of-enumerations) does not work, because Bar is not a direct subclass of Enum; Bar is-a Foo is-a Enum.

Iterating the MRO isn't the cheapest operation, and I'd be happy to discuss other solutions. Perhaps setting a special flag during the calculate_mro iteration.

### CODE REVIEW

**Comment by wittekm** [comment]
Also, I recognize that most of you are off at PyCon. No rush!

**Comment by rwbarton** [comment]
This looks fine, though if we're traversing mros then it would be a bit simpler to just traverse the mro of the class we're analyzing, i.e. call this function once after setting up the new class's mro.

**Comment by wittekm** [comment]
Agreed; I'll see if I can do it at that level.

**Comment by wittekm** [comment]
Sorry, last commit message is wrong; it's "Calculate is_enum based off MRO per-class instead of per-instance"

**Comment by rwbarton** [comment]
👍, this is even better than what I had in mind since we recompute the MRO later in ThirdPass (to deal with inheritance across cyclic imports) and then `is_enum` will get updated too.

**Comment by gvanrossum** [comment]
I presume we're holding off on this until after the 0.4.2 release right?

**Comment by JukkaL** [comment]
Let's wait until 0.4.2 is released.

**Pull request merged**
