### PR TITLE
sync typeshed

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Want to make sure everything is fine with Windows symlinks.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Looks like I messed up something with the submodule, fixing.

**Comment by JelleZijlstra** [comment]
It's failing again on the symlinks for some reason. It definitely worked before, not sure what is different.

**Comment by JelleZijlstra** [comment]
OK, put another appveyor fix in this PR too.

**Comment by gvanrossum** [comment]
Let me know when this is ready to merge, or what dependencies need to be merged first.

**Comment by JelleZijlstra** [comment]
It should be OK now.

**Pull request merged**
