### PR TITLE
Build with Python 3.8 released

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
@JukkaL it looks like one of the recent stubgen PRs introduced intermittent failures on Windows, it would be great if you can look into it.

**Comment by ilevkivskyi** [comment]
(otherwise I can try fixing in on Monday, my Windows laptop is at work.)

**Comment by gliptak** [comment]
@ilevkivskyi https://ci.appveyor.com/project/gvanrossum/mypy/builds/28900775/job/dh3pf351w75a9tgm shows

```
Cache 'C:\Users\appveyor\AppData\Local\pip\Cache' - Restored
```

Would you be able to clear the cache?

**Comment by JukkaL** [comment]
@ilevkivskyi I'll look at the Windows failures this week.

**Comment by ethanhs** [comment]
I opened https://github.com/python/mypy/pull/7964

**Comment by gliptak** [comment]
@ilevkivskyi PR is green

**Pull request merged**
