### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by jhance**
Source commit:
https://github.com/python/typeshed/commit/a92da58328aa259184ff45bb7408e82426fb563e

### CODE REVIEW

**Comment by AlexWaygood** [comment]
The `psycopg` primer errors are because of https://github.com/python/typeshed/pull/8446 — the maintainer has been warned, and said he was cool with it.

For the other primer errors, I think you need to reapply https://github.com/python/mypy/pull/13093.

**Comment by jhance** [comment]
@sobolevn Do you have any ideas what is going on in stubtest?

**Comment by sobolevn** [comment]
> test_module.pyi:89: error: "Match" expects no type arguments, but 1 given

I suspect that this test fails: https://github.com/python/mypy/blob/487b736743637142a53e49525b935ccad5ccc5fd/mypy/test/teststubtest.py#L846-L856

Why? I have no idea. Probably due to some typeshed changes. I think @AlexWaygood was working with `Match` recently.

**Comment by AlexWaygood** [comment]
> Why? I have no idea. Probably due to some typeshed changes. I think @AlexWaygood was working with `Match` recently.

Yeah, I'm 99% sure this is somehow due to a typeshed change I made recently. I'll try to take a look sometime soon and suggest a fix!

**Comment by AlexWaygood** [comment]
The major change to `re` in this typeshed sync is https://github.com/python/typeshed/commit/ea7bbbdad7abf05a3bd3feb25eef93b53165e2d9. But I can't figure out why this is making `teststubtest` think that `re.Match` expects no type arguments. @hauntsaninja, do you have any ideas? :)

The problematic line in the test is not actually the one @sobolevn suggested; it is this one:
https://github.com/python/mypy/blob/3ec1849528bd9ae8fb744620cfa24705ee7d39b0/mypy/test/teststubtest.py#L903

If you comment out that line, the test passes fine.

**Comment by AlexWaygood** [comment]
> The major change to `re` in this typeshed sync is [python/typeshed@ea7bbbd](https://github.com/python/typeshed/commit/ea7bbbdad7abf05a3bd3feb25eef93b53165e2d9). But I can't figure out why this is making `teststubtest` think that `re.Match` expects no type arguments. @hauntsaninja, do you have any ideas? :)
> 
> The problematic line in the test is not actually the one @sobolevn suggested; it is this one:
> 
> https://github.com/python/mypy/blob/3ec1849528bd9ae8fb744620cfa24705ee7d39b0/mypy/test/teststubtest.py#L903
> 
> If you comment out that line, the test passes fine.

I figured it out. `re` now imports `AnyStr` from `typing`, but `AnyStr` wasn't defined in `teststubtest`'s typing fixture. If you merge #13447 into this branch, the CI should go green :)

**Comment by hauntsaninja** [comment]
Thanks for figuring it out! In general, weird errors in mypy tests are 90% fixture related issues

**Review by hauntsaninja — APPROVED** [review]

**Pull request merged**
