### PR TITLE
Support `enum.nonmember` for python3.11+

### PR DESCRIPTION
**Pull request by sobolevn**
This PR adds support for https://docs.python.org/3.11/library/enum.html#enum.nonmember

Refs https://github.com/python/mypy/issues/12841

### CODE REVIEW

**Review by JukkaL — APPROVED** [review]
It's good to have support for additional enum features.

**Comment by sobolevn** [comment]
I will this open for a day, so other can comment.

**Review by AlexWaygood — APPROVED** [review]
LGTM. We could also add some similar special casing for `enum.member` -- currently mypy just follows the typeshed stubs, which leads to incorrect results: https://mypy-play.net/?mypy=latest&python=3.12&gist=1f3799c9117af6d8a55552e4018f526d

I'm also fine with that being done as a followup, if you prefer, though!

**Comment by sobolevn** [comment]
Thanks! `member` will be my next PR, so merging this one.

**Pull request merged**
