### PR TITLE
Fix support for async for comprehensions

### LINKED ISSUE #2924: Support for async comprehensions is broken
Here's a simple example:
```python
from typing import AsyncIterable

class bar(AsyncIterable[int]):
    def __aiter__(self):
        self.count = 3
        return self
    async def __anext__(self):
        self.count -= 1
        if self.count >= 0:
            return self.count
        raise StopAsyncIteration

async def foo() -> None:
    x = [i async for i in bar()]
    for i in x:
        print(i)

def main():
    a = foo()
    try:
        print(a.__await__().send(None))
    except StopIteration as e:
        print("stop with value =", e.value)

main()
```
When run with Python 3 this prints
```
2
1
0
stop with value = None
```
However when type-checked with mypy we get an error on the async comprehension in `foo()`:
```
__tmp__.py:14: error: Iterable expected
__tmp__.py:14: error: "bar" has no attribute "__iter__"; maybe "__aiter__"?
```
(Note the irony in the error message. :-)

This makes me think that mypy doesn't check the async flag on the comprehension's AST node. If we replace `foo()` with
```python
async def foo() -> None:
    async for i in bar():
        print(i)
```
the output is the same and mypy accepts it, strengthening my diagnosis.

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Fixes #2924

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks!

**Comment by gvanrossum** [comment]
So I have some bad news.

Running mypy's own tests with these I see two new errors, one in crawl.py and on in crawl2.py. The offending line is
```
ipaddrs = yield from self.loop.getaddrinfo(host, port)
```
In the latter it uses `await` instead.

It's easy to repro manually:
```
$ mypy test-data/samples/crawl.py
test-data/samples/crawl.py:147: error: 'Union[Tuple[builtins.str, builtins.int], Tuple[builtins.str, builtins.int, builtins.int, builtins.int]]' object is not iterable
```

**Comment by JelleZijlstra** [comment]
Oops, I'll look into that tonight.

**Comment by JelleZijlstra** [comment]
Are you sure the errors are due to this change? I can't currently reproduce it (maybe I'm installing mypy master wrong), but I suspect it's due to https://github.com/python/typeshed/pull/958, which among other things made the return type of `loop.getaddrinfo` more precise. It was just `tuple`, but I changed it to a union of the two kinds of tuple it can actually return (for IPv4 and IPv6 addresses I think).

**Comment by gvanrossum** [comment]
Yes, sorry. I was confused about which tracker/PR to blame it to.

**Pull request merged**
