### PR TITLE
Don't check stubs of typeshed that are blacklisted in typeshed

### PR DESCRIPTION
**Pull request by TrueBrain**
Recently typeshed has blacklisted a module for MyPy. In result, updating the typeshed in MyPy itself causes `runtests` to fail, because it doesn't read the blacklist in `runtests`.

Code is a (for readability altered) copy of how the blacklist is processed in `typeshed`.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Can't you reuse the blacklist reading code from the typeshed test script? Now we have two places that need to be kept in sync. (I also regret that boto was blacklisted, but I'll comment on the diff directly.)

**Comment by TrueBrain** [comment]
Not without making changes in typeshed too. Sadly, the blacklist read part is directly in the `main()` function.

Would you prefer a refactoring of typeshed so they can share the code?

For reference: https://github.com/python/typeshed/commit/c46993aa8eb1e049ad57d08e0d675357e6c203bc

**Comment by gvanrossum** [comment]
Hm, maybe mypy's `runtests.py` should actually just invoke typeshed's `tests/mypy_test.py` script? There are other things that are duplicated that have already skewed a bit, e.g. the latter tests the 3.6-only stubs but the former doesn't (and it doesn't test the Python 2 stubs at all).

Off-topic: I wish we could get rid of `runtests.py` completely in favor of `py.test`. I can never figure out how to correlate the various bits of code and strings I see in `runtests.py` with its command-line arguments, so I end up wasting time running too many (or too few!) tests when iterating on a particular piece of code.

**Comment by gvanrossum** [comment]
Are you still interested in solving this in a better way? The blacklist is empty again (and I hope to keep it empty) so it doesn't sound urgent, and we could just close this PR.

**Comment by TrueBrain** [comment]
I really like your solution more, to not have a blacklist. Will close the PR for now. Thank you!

**Pull request closed without merging**
