### PR TITLE
[mypyc] Implement new-style builtins.len for all supported type

### PR DESCRIPTION
**Pull request by TH3CHARLie**
This PR completes the support of the new style `builtins.len` for dict, set, tuple and generic cases.

### CODE REVIEW

**Comment by TH3CHARLie** [comment]
@JukkaL I saw your comment in #9290. There is one thing suspicious that originally the return type for dict, set and tuple are `int`:
```python
func_op(name='builtins.len',
        arg_types=[dict_rprimitive],
        result_type=int_rprimitive,
        error_kind=ERR_NEVER,
        emit=emit_len)
```

With this PR, this code snippet makes them `short_int`:
```python
            return self.binary_int_op(short_int_rprimitive, size_value, offset,
                                      BinaryIntOp.LEFT_SHIFT, line)
```

Could this be the root cause? However, please note that len for list is of `short_int` return type.

**Comment by JukkaL** [comment]
@TH3CHARLie I narrowed the issue down to https://github.com/mypyc/mypyc/issues/756.

**Comment by TH3CHARLie** [comment]
> @TH3CHARLie I narrowed the issue down to [mypyc/mypyc#756](https://github.com/mypyc/mypyc/issues/756).

cool! I just checked the issue, though I haven't come up any quick fix yet.

**Comment by JukkaL** [comment]
> cool! I just checked the issue, though I haven't come up any quick fix yet.

I can also help with this, since I'd like to get fix out soon.

**Pull request merged**
