### PR TITLE
Fix CI by allowing it to fail on `3.11`

### PR DESCRIPTION
**Pull request by sobolevn**
Closes https://github.com/python/mypy/pull/12002
Refs https://github.com/python/mypy/pull/11984

### CODE REVIEW

**Comment by sobolevn** [comment]
It does not fail anymore, but is still broken: https://github.com/python/mypy/runs/4844006633?check_suite_focus=true

**Comment by sobolevn** [comment]
CC other CI committers: @hauntsaninja @97littleleaf11 @ethanhs 

This problem blocks other PRs to be merged. We have several options:
1. This
2. Remove 3.11 (I don't want to do that, because of how radical it is)
3. Try to fix `cpython` / `typed-ast` (might be a long process)

**Comment by 97littleleaf11** [comment]
The first two options are the same - they skip all the tests on Python 3.11. I prefer droping python nightly test for a while and just wait for fix on typed-ast.

**Comment by JukkaL** [comment]
I agree with @97littleleaf11. I think that it's best to disable Python nightly temporarily while typed-ast is broken.

**Comment by sobolevn** [comment]
Done! Thanks everyone! 👍

**Review by JukkaL — APPROVED** [review]
Thanks!

**Pull request merged**
