### PR TITLE
Add Final annotations to mypy code itself

### PR DESCRIPTION
**Pull request by ilevkivskyi**
This adds `Final` annotations to most module-level and class-level names I have found. Some of these are important to get performance boost after compiling with mypyc, other are just added for completeness. This PR also makes two runtime changes:
* `TypeOfAny` switched from an enum to using small integer constants, this is important for performance
* `binder.BindableTypes` is now inlined in two `isinstance()` checks. I first made it `Final`, but then realised that it will be much more efficient to just inline it, since these `isinstance()` checks are in a hot code path.

Note: after a new version of `typing_extensions` is released on PyPI we can skip all the `if MYPY: ...` checks.

The corresponding mypyc PR is https://github.com/JukkaL/mypyc/pull/439

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
> Could you try adding `Final` to `_dummy` in `types.py` also? I think that could give a solid win

Oh yes, thanks, I completely forgot about this one.

Also everyone please suggest anything here if you see some of your favorite class and module final names are missing.

**Comment by ilevkivskyi** [comment]
> I think that could give a solid win

Oh yes, another 50ms, which is amazing for a single constant.

**Comment by JukkaL** [comment]
What about `mypy.nodes.op_methods` (and the various things that immediately follow)?

**Comment by msullivan** [comment]
> Oh yes, another 50ms, which is amazing for a single constant.

In my profiling, the hottest compiled function was `CallableType.copy_modified`, which references `_dummy` *32* times.

**Pull request merged**
