### PR TITLE
Do not import List, Dict, and Set by default

### LINKED ISSUE #999: Dict, List and Set are imported by default
This code (no import from typing) complains, as expected:

```
a = None  # type: Any
```

However, this code passes:

```
a = None  # type: Dict
```

Similar with List, Set.

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fix #999 

This is a straightforward fix: ``List``, ``Set``, and ``Dict`` are treated as aliases to their ``builtins`` counterparts, therefore they are ignored by ``remove_imported_names_from_symtable``, I fix this by also removing the alias names.

This depends on https://github.com/python/typeshed/pull/933 + sync typeshed

The fix also revealed few places in mypy where imports were missing.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks! You can add the typeshed sync to this PR yourself.

**Comment by gvanrossum** [comment]
I need to test this carefully against our internal codebases and I'm having some problems with that due to the typed-ast change. Bear with me.

**Comment by ilevkivskyi** [comment]
I also see this strange typed_ast error, it didn't appear before I (finally) synced typeshed.

**Comment by ilevkivskyi** [comment]
I fixed the ``typed_ast`` issue (looks like a simple oversight) in a new commit I pushed here.

**Comment by gvanrossum** [comment]
Thanks! Now I need to focus on other stuff.

**Comment by ilevkivskyi** [comment]
Thank you!
> Now I need to focus on other stuff.

Sure, no problem, take your time!
(I will make few more PRs soon,  maybe others will have time to take a look)

**Pull request merged**
