### PR TITLE
Document empty tuple syntax

### LINKED ISSUE #4211: Is there a way to represent an empty tuple type?
`logging.handlers.SMTPHandler` arg `secure` accepts something like this:

    Union[EmptyTuple, Tuple[str], Tuple[str, str]]

Is there a way to define the `EmptyTuple` part?

### PR DESCRIPTION
**Pull request by ethanhs**
Fixes #4211.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I'm not sure this belongs in the cheatsheet, since the cheatsheet is meant to be a quick reference for common types, and the type of an empty tuple is definitely not a common need. Maybe there isn't a better place for it though.

**Comment by ilevkivskyi** [comment]
> Maybe there isn't a better place for it though.

There is "Common issues" section. Maybe this discussion can be put there?

**Comment by JelleZijlstra** [comment]
I doubt it's a common issue either. :)

Maybe it should be in https://mypy.readthedocs.io/en/latest/builtin_types.html, which is currently missing `Tuple`.

**Comment by gvanrossum** [comment]
I think adding various forms of tuples to https://mypy.readthedocs.io/en/latest/builtin_types.html is a good idea, but I like adding this to the cheat sheets too (many people use *just* the cheat sheet for reference, and this is definitely an issue where everyone needs help).

**Pull request merged**
