### PR TITLE
Allow tuples as second argument to namedtuple

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Thanks to @rwbarton on IRC for pointers

### CODE REVIEW

**Comment by gvanrossum** [comment]
Do you need help debugging the CI failure?

**Comment by alexjurkiewicz** [comment]
All good, I got there eventually!

**Comment by gvanrossum** [comment]
Victory! Can you also add a test or tests to check-namedtuple.test? I'd also check that this works for typing.NamedTuple as well as for collections.namedtuple.

**Comment by alexjurkiewicz** [comment]
Added three extra tests -- do these cover what you want?

**Comment by gvanrossum** [comment]
Thanks again!

**Pull request merged**
