### PR TITLE
Sync pythoncapi_compat

### PR DESCRIPTION
**Pull request by 97littleleaf11**
Related https://github.com/mypyc/mypyc/issues/889

### CODE REVIEW

**Comment by 97littleleaf11** [comment]
cc @vstinner @JelleZijlstra Am I doing the right way to update the LICENSE?

**Review by JelleZijlstra — APPROVED** [review]
I assume you just copied the file over? This makes sense to me but I don't know much about the C API, so let's also give Victor some time to confirm.

**Comment by vstinner** [comment]
> cc @vstinner @JelleZijlstra Am I doing the right way to update the LICENSE?

I changed pythoncapi_compat license so you **don't** have to mention pythoncapi_compat license to use it.

Previously, the MIT license **required** you to mention it. I made a mistake when I copied pythoncapi_compat in mypy, I wasn't aware of the "advertizing" part of the MIT license.

I suggest to leave the LICENSE file unchanged: don't mention pythoncapi_compat license. But you **can** mention the license if you want :-)

**Comment by vstinner** [comment]
What is the purpose of this change? To use the 0BSD license instead of the MIT license? If yes, it's a good thing :-) The MIT license must be mentioned in the projects using the old version of pythoncapi_compat (the old version using the MIT license).

**Comment by vstinner** [comment]
> Related https://github.com/mypyc/mypyc/issues/889

This issue was just closed.

**Review by vstinner — APPROVED** [review]
LGTM.

**Pull request merged**
