### PR TITLE
stubtest: fix false-positive error for Protocol `__init__`s and Protocol `__annotations__`

### LINKED ISSUE #12820: stubtest false positive for Protocol `__init__`
From `python -m mypy.stubtest --custom-typeshed-dir . wsgiref`:

```
error: wsgiref.types._Readable.__init__ is inconsistent, stub does not have *args argument "args"
Stub: at line 87
def (self: builtins.object)
Runtime: at line 1912 in file /Users/jelle/py/cpython/Lib/typing.py
def (self, *args, **kwargs)
```

The stub and implementation are exactly the same.

Stubtest picks up the `__init__` method the runtime injects for Protocols, but it's not useful.

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #12820

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Should this check whether `runtime.__init__ is Protocol.__init__`? E.g., given https://github.com/python/cpython/pull/31628

**Comment by AlexWaygood** [comment]
> Should this check whether `runtime.__init__ is Protocol.__init__`? E.g., given [python/cpython#31628](https://github.com/python/cpython/pull/31628)

I sank some time into this, but I think it might be more trouble than it's worth. The check would be much more complicated than a simple `runtime.__init__ is Protocol.__init__` check, due to the fact that there's some pretty cursed stuff going on at runtime with `Protocol` `__init__` methods: https://github.com/python/cpython/blob/3f738600f623b88bc90ec12587f75babb6f1025e/Lib/typing.py#L2086-L2087. The fact that this logic changed in 3.11 to mean that now `Protocol` `__init__`s are only sometimes replaced (rather than being replaced all the time) makes it even more complicated.

It's probably doable, but would you accept this patch as-is for now, with a TODO comment saying that we should probably check `__init__` in some situations on 3.11+?

**Comment by hauntsaninja** [comment]
Yup, I'd accept a TODO!

**Comment by AlexWaygood** [comment]
Output if I run typeshed's `stubtest_stdlib.py` with this patch applied:

```diff
+note: unused allowlist entry importlib.abc.Traversable.__init__
+note: unused allowlist entry importlib.metadata.PackageMetadata.__init__
+note: unused allowlist entry importlib.metadata._meta.PackageMetadata.__init__
+note: unused allowlist entry importlib.metadata._meta.SimplePath.__init__
+note: unused allowlist entry typing.SupportsAbs.__init__
+note: unused allowlist entry typing.SupportsBytes.__init__
+note: unused allowlist entry typing.SupportsComplex.__init__
+note: unused allowlist entry typing.SupportsFloat.__init__
+note: unused allowlist entry typing.SupportsIndex.__init__
+note: unused allowlist entry typing.SupportsInt.__init__
+note: unused allowlist entry typing.SupportsRound.__init__
```

**Review by hauntsaninja — APPROVED** [review]

**Pull request merged**
