### PR TITLE
Improve error message for incompatible TypeVar value

### LINKED ISSUE #3341: Suggested improvement for wording of an error
I recently had trouble understanding an error output along the lines of:

```
Type argument 1 of "<function name>" has incompatible value "<a type that doesn't fit the TypeVar>"
```

Would it be possible to output something more along the lines of:

```
TypeVar "T" cannot be a "<wrong type>" (from first argument to "<function name>")
```

### PR DESCRIPTION
**Pull request by ilinum**
Fixes #3341

### CODE REVIEW

**Comment by ddfisher** [comment]
@JukkaL what do you think of the updated error message?

**Comment by JukkaL** [comment]
Looks reasonable! Here's another alternative that would make the error message perhaps even clearer:

```
Current:     Type argument 1 of "f" (TypeVar "AnyStr") cannot be "object"
Alternative: Value of type variable "AnyStr" of "f" cannot be "object"
```

It may also may sense to special case `typing.AnyStr` since it's so common. Here's an idea:

```
t.py:1: error: Value of type variable "AnyStr" of "f" cannot be "object"
t.py:1: note: Maybe you are mixing "str" and "bytes" values, which is not supported with "AnyStr"?
```

**Comment by ilinum** [comment]
Both sounds good!

Regarding the first suggestion though, I think there might be a case where specifying type argument number is useful (when names of two type args are the same).

**Comment by ilevkivskyi** [comment]
Note that there is PR https://github.com/python/mypy/pull/3433 that takes a more "global" approach to the ``AnyStr`` error message. @quartox are you still working on it?

**Comment by quartox** [comment]
@ilevkivskyi I will get back to it this weekend.

**Comment by ilinum** [comment]
I updated the error message as per Jukka's suggestion.

However, I think the additional error message for `AnyStr` should be handled in #3433 since @quartox is already working on it.

**Comment by ddfisher** [comment]
And agreed -- the `AnyStr` change can happen in #3433.

**Pull request merged**
