### PR TITLE
Remove unused methods (errors.py)

### PR DESCRIPTION
**Pull request by elazarg**
See #2279.

### CODE REVIEW

**Comment by gvanrossum** [comment]
In a follow-up, maybe get rid if import_ctx altogether?

**Comment by elazarg** [comment]
Are you sure it can be done? It seems to be needed to for the `In module imported here:`.

**Comment by gvanrossum** [comment]
Since there were no calls to push/pop_import_context, it's always empty? (Easy to verify by adding an assert and running the full tests.)

**Comment by gvanrossum** [comment]
Never mind, this is now all done via set_import_context().

**Pull request merged**
