### PR TITLE
Make None compatible with Hashable

### LINKED ISSUE #8768: None is not considered Hashable
```python
from typing import Hashable


def f() -> Hashable:
    return None


print(isinstance(None, Hashable))
```
The print returns True, so Python understands that None is hashable, but MyPy complains about incompatible return types:
```
error: Incompatible return value type (got "None", expected "Hashable")
```

### PR DESCRIPTION
**Pull request by JukkaL**
Fixes #8768.

### CODE REVIEW

**Review by ilevkivskyi — APPROVED** [review]

**Comment by erictraut** [comment]
We received a similar [feature request for pyright](https://github.com/microsoft/pyright/issues/985). I considered doing a spot fix specifically for `__hash__`, but this struck me as a bit hacky and not very generalizable, since there are other valid protocols that could also apply to None.

I thought of another approach that might work better. Could we define a `NoneType` in `typing.pyi` that defines the methods supported by `None`? Type checkers could then use this class definition when doing protocol validation. Interested in your thoughts.

If you're open to that approach, I'd be happy to submit a PR to typeshed that defines `NoneType`.

**Comment by erictraut** [comment]
@JukkaL do you have any thoughts on my proposal above?

**Comment by JukkaL** [comment]
It sounds reasonable, since the type of `None` is not available in the builtins or `types` in Python 3. I don't see a use case for making it available at runtime, however. It was removed from `types` in Python 3 (`types.NoneType` exists in Python 2.7), and I'd assume this happened for a reason. So maybe we should be name it `_NoneType` to make it more clear that it's an internal definition that's only supposed to be used by tools?

**Comment by erictraut** [comment]
Thanks, naming it `_NoneType` is a great suggestion. I'll submit a PR to typeshed.

**Pull request merged**
