### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by hauntsaninja**
Source commit:
https://github.com/python/typeshed/commit/a27f15ef0eb12b961d0fb58f8615a3df901a9176

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Note the paroxython change is a true positive. But a tonne of test failures, let's see what's gone wrong.

**Comment by AlexWaygood** [comment]
For reference, we discussed the new homeassistant hit in depth over in https://github.com/python/typeshed/pull/7737

**Comment by JelleZijlstra** [comment]
The errors are on code that looks like this:

```python
        return re.sub('[^\\x20-\\x7e]',
                      lambda m: r'\u%.4x' % ord(m.group(0)), s)
```
https://github.com/python/mypy/blob/03901ef657daf6f477e6fe933c42ac270cf5034b/mypy/strconv.py#L345

I suspect mypyc miscompiles this into something involving bytes.

**Comment by JukkaL** [comment]
> I suspect mypyc miscompiles this into something involving bytes.

Mypyc probably somehow believes that the call returns `bytes` and raises an exception when it actually returns a `str`. I can investigate this tomorrow.

**Comment by JukkaL** [comment]
Hopefully #12780 fixes the test failures if you merge master.

**Comment by JelleZijlstra** [comment]
Thanks @JukkaL for the fix!

**Pull request merged**
