### PR TITLE
include test data in source distribution

### PR DESCRIPTION
**Pull request by mr-c**
Closes: #2784.

### CODE REVIEW

**Comment by gvanrossum** [comment]
IMO a source disto should contain everything from the repo. So including docs.

How did you test this?

**Comment by mr-c** [comment]
```
python3.6 setup.py sdist
mkdir t
cd t
tar xzf ../dist/*
cd mypy*
./run-tests.py
```

**Comment by gvanrossum** [comment]
I still prefer that the docs are included in the source tarball as well. And there's still the mystery that when *I* run `python3.6 setup.py sdist` the created tarball contains the docs. Why would that be? (And what does @JukkaL's misc/upload-pypi.py script do differently, since the tarball it creates does not contain the docs?)

**Comment by gvanrossum** [comment]
I still can't test this reliably, since for me, `python3 setup.py sdist` somehow always includes nearly everything, and I don't know how to debug that. However I think this is on the right track, and after the tests pass with the small changes I added, I'll just merge it.

**Comment by gvanrossum** [comment]
Let's hope this settles it! Can you test this in your environment?

**Comment by mr-c** [comment]
Pardon the late follow-up, this does work and as of mypy-0.660 Debian is running the tests both at packaging time and as part of the Debian CI system of post-install testing.

Thanks!

**Pull request merged**
