### PR TITLE
Use `strict = True` for `mypy_bootstrap.ini`

### PR DESCRIPTION
**Pull request by sobolevn**
We almost had all strict flags set anyway, so many it will just work.
If not, it would be easier to turn something off.

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks for the quick review!

**Comment by davidhalter** [comment]
On a related note: Is it intentional that `warn_unreachable` is not used? I have recently realized that this is not turned on and it feels a bit strange. There are about 39 errors when running with `--warn-unreachable` (on `mypy_self_check.ini`) and it brings up a few questionable things like https://github.com/python/mypy/blob/master/mypy/test/testpep561.py#L180.

It is also questionable why `--strict` does not just enable `--warn-unreachable`. A lot of people probably think "I'm running --strict, there's nothing else important to enable". However that's an entirely different topic.

**Comment by sobolevn** [comment]
We should add `--warn-unereachable` to `--strict` in 2.0
@davidhalter can you please open two new issues about these two topics?

**Comment by davidhalter** [comment]
@sobolevn Done, see the issues above.

**Pull request merged**
