### PR TITLE
Make TypeIndirectionVisitor depend on all classes in MROs

### LINKED ISSUE #4562: False negative in incremental mode
We don't yet fully understood this, but @msullivan and I observed the following:

- the code was of the form `assert x.y.z == <constant>`
- the expected error was of the form `Item "None" of "Optional[Y]" has no attribute "z"`
- the type of `x.y` was inferred from a method `f() -> Optional[Y]`
- previously, `f` (defined in a different file) did not have an annotation
- the file with the error was not modified

Apparently the cache for the file with the error was considered up-to-date, and not dependent on the file where `f` was defined. It's possible that interface hash calculation is at fault.

### PR DESCRIPTION
**Pull request by msullivan**
This fixes some nasty incremental mode bugs.
Fixes #4562.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Can you understand why the tests fail on all builds except 3.6?

**Comment by gvanrossum** [comment]
I've restarted the build, but it doesn't *feel* like a glitch. (There have been some glitches related to Trusty.)

**Comment by gvanrossum** [comment]
After re-running the failing build, it still fails, but now with 3 out of 4 jobs passing (previously only 3.6 passed). But 3.4 still fails, even after re-running that one. Flake? Or something else?

**Comment by gvanrossum** [comment]
After re-running the failing build, it still fails, but now with 3 out of 4 jobs passing (previously only 3.6 passed). But 3.4 still fails, even after re-running that one. Flake? Or something else?

**Comment by msullivan** [comment]
I am deeply confused by this.

**Comment by msullivan** [comment]
I can intermittently reproduce the failure locally---it seems to genuinely be a nondeterministic failure. I am investigating.

**Comment by msullivan** [comment]
The test failures were caused by `STRICT_OPTIONAL` leaking out and being true for unit tests. This would happen if a test run under dmypy had strict optional on (and I added a test that did). It was nondeterministic because it only came up if the same runner that ran that test then ran the typing unit tests.

#4568 is up to fix that. I'm rebasing this diff but it needs to not land until the other has.

**Pull request merged**
