### PR TITLE
Update test_commandline.py

### PR DESCRIPTION
**Pull request by dubesar**
1. Made changes to test_commandline.py to make it faster using regex
2. Used iter_replace method of regex to make the replace faster.

### CODE REVIEW

**Comment by dubesar** [comment]
@JukkaL please review the pull request and I am not able to understand why is it failing CI travis.

**Comment by JelleZijlstra** [comment]
Why would this be faster? I haven't timed it but I'm pretty sure calling `.replace` directly is going to be faster than a bunch of hand-rolled Python code and regex execution.

**Comment by dubesar** [comment]
@JelleZijlstra  Sorry I didn't time it but it approximately the same and doesn't have any much effect. 

For above regex is  0.0001814s
and .replace is 0.000141s

**Comment by JelleZijlstra** [comment]
I timed it too (using `%timeit` in IPython, which runs the code many times to get more reliable numbers) and found that the new code was more than 10x slower.

**Pull request closed without merging**
