### PR TITLE
use base type as hint when inferring

### PR DESCRIPTION
**Pull request by Riolku**
Would help with #12268. Modified a test because the two behaviours conflict right now.

### CODE REVIEW

**Comment by Riolku** [comment]
To motivate this PR, consider the following code (which is also a test case):

```py
from typing import Union, List

class A: pass
class B: pass

U = Union[A, B]

class Base:
    variable1 : List[U] = []
    variable2 : List[U] = []

class Derived(Base):
    variable1 = [A()]
    variable2 = variable1
```

before this PR, although `variable1` is type-checked against `List[U]`, it is inferred as `List[A]`, which makes the last line an error. This PR instead uses the base type as a hint for the inference, if possible.

**Comment by Riolku** [comment]
Note that this hinting is already done, in order to infer `[A()]` as `List[U]`, so that _that_ line doesn't throw.

**Comment by Riolku** [comment]
Since the issue is open, I think it's fair to say that this would fix #12268

**Comment by Riolku** [comment]
I give up. Maybe a maintainer can help.

**Comment by Riolku** [comment]
Hey, I think this PR is ready for someone to look over. It's been around two weeks, and I don't want it to get lost in the sea of PRs. Does anyone mind taking a look?

**Review by hauntsaninja — COMMENTED** [review]
Thank you for the PR! I believe this was fixed in https://github.com/python/mypy/issues/13494

**Pull request closed without merging**
