### PR TITLE
[waiting for typed_ast PR] allow to write both "type: ignore" and "mypy: ignore"

### PR DESCRIPTION
**Pull request by matthiaskramm**
This is useful for adding mypy-specific ignores to typeshed.

### CODE REVIEW

**Comment by gvanrossum** [comment]
@JukkaL what do you think of the idea?
@matthiaskramm I think this should also be done in the new/fast parser.

**Comment by JukkaL** [comment]
This looks reasonable -- I've thought about other mypy-specific directives, and `# mypy: <something>` was what I was thinking about using for them, so this would work together with those other (still hypothetical) extensions.

**Comment by gvanrossum** [comment]
@ddfisher Can you comment on the need to also support this (`# mypy: ignore` comments) in typed_ast and/or mypy/fastparse.py?

**Comment by JukkaL** [comment]
If we are going to eventually migrate to only `typed_ast` / `fastparse.py`, this would have to be supported, right?

**Comment by ddfisher** [comment]
Yes, this will need to be added to typed-ast, and I don't think we
should merge this without typed-ast support, because otherwise use of it
would break the fast parser.

**Comment by ddfisher** [comment]
Is there an example use-case for this?  typed-ast support aside, I feel a bit concerned about the need for this.

**Comment by matthiaskramm** [comment]
There isn't a strong use case, but it would be convenient to have a mypy-specific "ignore", especially for typeshed.
For example, https://github.com/python/typeshed/pull/464 has to, in its current version, prevent either mypy or pytype from parsing the file, since pytype doesn't allow you to write `# type: ignore` into a stub, and mypy needs it, for the odd `Complex` return.

**Comment by ddfisher** [comment]
Ah.  FWIW, you currently cannot prevent mypy from parsing a file with a `# type: ignore`.  See #626.

**Comment by gvanrossum** [comment]
Isn't the whole-file # type: ignore a separate issue from this?

**Comment by matthiaskramm** [comment]
It is. What I mean by "prevent mypy from parsing a file" is:
Files in typeshed are tested with both mypy and pytype.
We have a blacklist for files that don't yet work with the pytype. We could have the same thing for mypy. But I'd greatly prefer just having a mypy-specific `ignore`, since that way, we don't have to skip the entire file.

**Comment by gvanrossum** [comment]
FWIW if you need to skip a file completely with mypy, the mypy_test.py
script has a -x option. (It was used extensively in the early days, e.g.
for the horribly broken mysql stubs. Now those are merely horribly
incomplete. :-)

**Comment by gvanrossum** [comment]
It looks like this PR is pretty much stuck. I'm trying to clean up stuck PRs so that the list of PRs is not too long. If you feel like working on this some more, just go ahead and reopen it, or open a new PR -- the corresponding issue will remain open with a reference to this (closed) PR in it, so if someone else feels like tackling this problem they still have this PR as a starting point.

(In particular, we're waiting for a change in typed-ast first. Once that has landed I expect that adding the new functionality to mypy would require a different PR anyways.)

**Comment by oakkitten** [comment]
if you are here looking for a remedy for PyCharm's going crazy when it sees comments like `# type: ignore[attr-defined]`, you can try putting a tab character, not a space, between `#` and `type:`. mypy will still recognize this as type comment while PyCharm won't. As PyCharm normally converts tabs to spaces, you will have to copy it in from somewhere.

still, it would be nice to have `# mypy: ignore[...]` as error codes seem to be mypy-specific and not a part of PEP. this syntax might be actually breaking the rules of PEP...

**Pull request closed without merging**
