### PR TITLE
Add -q/--quieter flag to suppress notes about class/function

### LINKED ISSUE #1821: Proposal: get rid of notes like "note: In member "blah" of class "Blah":"
When there's an error on a line it's pretty clear what function that is in, and the note clarifying that is not very useful. Let's get rid of such notes.

This would also make the unit tests a bit simpler -- we could use the `# E: ...` idiom more often.

### PR DESCRIPTION
**Pull request by gvanrossum**
Fixes #1821 (well enough for me to close it).

### CODE REVIEW

**Comment by gvanrossum** [comment]
I made this an option so that we can experiment with it.

But my main reason for wanting it now is that I have a [rather large test](https://github.com/python/mypy/blob/add-crawl2/test-data/unit/check-async-await.test#L315) with a bunch of errors aimed at specific lines, and I really want to use the `# E: ...` notation. The test (by its nature) contains several functions, so there would be several "In function ..." notes interspersed with the interesting errors. Using this diff I can add "quieter" to the `# options:` section of the test to suppress those notes. By leaving the default unchanged I won't have to clean up the zillions of other tests expecting these notes.

**Comment by ddfisher** [comment]
I worry that this PR will lead to us never fixing the user-facing aspects of #1821.  I'd much rather see us do that all in one fell swoop.

Don't we have a flag for automatically fixing up test files?

**Comment by ddfisher** [comment]
Aside from that, it would be nice for this to have a more specific name.

**Comment by ddfisher** [comment]
I missed that this PR added a user-facing flag.  With that in mind, this seems like a reasonable first step.

**Pull request merged**
