### PR TITLE
Remove `str-bytes-safe` check

### PR DESCRIPTION
**Pull request by sobolevn**
This is a draft PR, I invite everyone to vote / discuss: do we need this feature? 
Or does it do more harm than good?

In my opinion, it is very cryptic, very specific, solves a problem that does not exist for quite some time.

Other opinions are more than welcome! :) 

Closes https://github.com/python/mypy/issues/11806

### CODE REVIEW

**Comment by beauxq** [comment]
Rather than say the problem "does not exist for quite some time", I would say the problem is becoming more and more rare as we move further away from Python 2.

**Comment by JukkaL** [comment]
I agree that this still seems helpful, even if it was originally implemented to help with the Python 3 migration. However, it would be nice to document this error code and explain the motivation. It should already be possible to disable the error code globally in case some users don't think this is useful.

**Comment by hauntsaninja** [comment]
This check is still very useful in my opinion (I think mypy caught this for me sometime recently too, I'd forgotten to decode subprocess output)

**Comment by ilevkivskyi** [comment]
FWIW if many people think it is too annoying, you can make the error code off by default, but also people can use `--disable-error-code` flag (or corresponding config option, or inline `# mypy:` comment).

**Pull request closed without merging**
