### PR TITLE
Make TryStar not crash

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by hauntsaninja** [comment]
cc @svalentin

**Comment by svalentin** [comment]
I think as long as it's not crashing it should be fine. But will let @JukkaL take a closer look.

That said, a test is failing. I think we have some an incorrect py311 check.

**Comment by hauntsaninja** [comment]
Found something that needed to be changed, but weird that it worked locally for me

**Comment by hauntsaninja** [comment]
Going to go ahead and merge + backport since it fixes the crash and doesn't behave entirely terribly. Ivan said he would look into actual support.

**Pull request merged**
