### PR TITLE
Display full type of left operand in error messages

### PR DESCRIPTION
**Pull request by elazarg**
Remember the bound type of the self argument, allowing more consistent error messages.
For example, currently left and right operands are displayed differntly:
```python
$ cat tmp.py
class A:
    def __add__(self, other: A): return self
a = A()
(a, a) + a
a + (a, a)
$ mypy tmp.py
tmp.py:3: error: Unsupported operand types for + ("tuple" and "A")
tmp.py:5: error: Unsupported operand types for + ("A" and "Tuple[A, A]")
```
Left and right operands are not treated the same way.

### CODE REVIEW

**Comment by gvanrossum** [comment]
The new errors look like this:
```
__tmp__.py:4: error: Unsupported operand types for + ("Tuple[A, A]" and "A")
__tmp__.py:5: error: Unsupported operand types for + ("A" and "Tuple[A, A]")
```
Thanks! Reviewing now.

**Comment by gvanrossum** [comment]
Whoops, does the new attribute need to be serialized?

**Comment by elazarg** [comment]
I guess it does

**Comment by elazarg** [comment]
Why not?

**Comment by gvanrossum** [comment]
Sorry, never mind.

**Pull request merged**
