### PR TITLE
Correcting the pyinfo.py file

### PR DESCRIPTION
**Pull request by soma2000-lang**
### Description
Made some change in the code

https://github.com/python/mypy/blob/master/mypy/pyinfo.py#L22

## Test Plan

fixes issue #12202

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@hauntsaninja  Please look into this

**Review by ethanhs — COMMENTED** [review]
Hi, thank you for your PR. Unfortunately, these changes are not correct. The file does have to run under Python 2 (at least for now) since mypy can still type check Python 2 code. In addition, your change to the return of the `getprefixes()` function is not correct, instead of returning *both* the base_prefix and prefix (note the return type is a tuple of str), it will only return the prefix if the base prefix is None or the empty string.

**Comment by ethanhs** [comment]
Oh I see you are trying to fix https://github.com/python/mypy/issues/12202. In that case I would change the check to be `hasattr(sys, "base_prefix")`.

**Comment by hauntsaninja** [comment]
Superseded by https://github.com/python/mypy/pull/12244
Closing since this isn't a correct fix, it's been a couple days, and I want to make sure this gets in the next release.

**Pull request closed without merging**
