### PR TITLE
Revert "Better support for converter in attrs plugin."

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Reverts python/mypy#4607

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
@euresti If you can fix my comments before the release, this can stay in, otherwise I would revert it (see comments on your original PR).

**Comment by euresti** [comment]
I'll work on the fixes you want today.

**Comment by euresti** [comment]
Ok my change is here: https://github.com/python/mypy/pull/4628

**Comment by ilevkivskyi** [comment]
Closing in favour of #4628

**Pull request closed without merging**
