### PR TITLE
Document support for underscores in numeric literals

### PR DESCRIPTION
**Pull request by ilevkivskyi**

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
This probably should wait until @ddfisher takes care of https://github.com/dropbox/typed_ast/pull/21

**Comment by ilevkivskyi** [comment]
@ddfisher I mention version 0.6.1 of ``typed_ast`` here. But this is probably not right. What is the right version where underscores will be supported?

**Comment by gvanrossum** [comment]
This is still waiting -- PR dropbox/typed_ast#21 got merged but no new typed_ast version was created. The last version was 0.6.1 but that doesn't have this. It's up to @ddfisher to make progress here.

**Comment by ddfisher** [comment]
This is now true as of `0.6.2`.

**Comment by ddfisher** [comment]
Thanks!

**Pull request merged**
