### PR TITLE
Extract typeddict semantic analysis from to a separate class

### PR DESCRIPTION
**Pull request by elazarg**
Related to #4083.

The intention is to do the same thing to namedtuple and enum, then move them to a separate module, refactor common work to helper functions, and hopefully find the right abstraction so it will be easy to add plugins of this kind.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
I think this should happen after last strict-optional PR is merged.

**Comment by elazarg** [comment]
Makes sense.

**Comment by JukkaL** [comment]
Note that I'm working on doing a similar extraction for named tuple. Mine is a little different -- it moves the new class into a new module in a way that there is no import cycle.

**Comment by elazarg** [comment]
This PR can't be maintained.

**Pull request closed without merging**
