### PR TITLE
Support namedtuple as one of multiple superclasses

### PR DESCRIPTION
**Pull request by elazarg**
Solve issue #1558 by delegate subtype checks on TupleType to fallback.

This does _not_ solve #1485. I don't know why.

### CODE REVIEW

**Comment by JukkaL** [comment]
Looks good to me, though there is one potential simplification. The `if is_named_instance(right, 'builtins.object')` check above your change now seems unnecessary, and maybe also the `Sized` check. Can you see if you can remove them to simplify the code a bit?

**Comment by elazarg** [comment]
`builtins.object` can be omitted. `Sized` cannot.

**Comment by elazarg** [comment]
Yes - more refactoring. It helped me understand what happens, and I believe it makes the logic clearer.

I can revert back to the minimal change if necessary.

**Comment by elazarg** [comment]
In the experimental refactor_to_enum branch I encountered what seems like another case of "Instance leak" we've discussed some time ago. I will try to investigate it; should I add the fix here or in a different PR?

**Comment by JukkaL** [comment]
If it seems unrelated to this change, it's probably better create a new PR.

**Comment by JukkaL** [comment]
The new methods don't really make the code easier for me to read. I'd suggest reverting to having them inline instead, as they are sufficiently simple.

**Comment by elazarg** [comment]
I would have opened an issue for the error, but it's hard to reproduce; in that branch there are many occurrences of the type, with similar context, and the error only occur in one of them.

**Comment by JukkaL** [comment]
Okay if it's hard to isolate then no problem.

**Comment by JukkaL** [comment]
Thanks!

**Pull request merged**
