### PR TITLE
Inform about no explicit export instead of attribute suggestions

### LINKED ISSUE #9084: "has no attribute" then suggests another missing attribute
Output in a mypy run:
```
vaults.py:14: error: Module 'datatypes' has no attribute 'VaultDataResponse'; maybe "VaultSummaryResponse"?  [attr-defined]
vaults.py:14: error: Module 'datatypes' has no attribute 'VaultSummaryResponse'; maybe "VaultDataResponse"?  [attr-defined]
```

Hopefully the error in the above output is self explanatory, it's contradicting itself.

### PR DESCRIPTION
**Pull request by kamilturek**
Fixes #9084

### CODE REVIEW

**Comment by bluetech** [comment]
This is a helpful improvement.

The message in your first version of the patch is a bit more understandable than the second IMO (the "Append to message instead of overwriting" commit). Interested why you changed it.

**Comment by kamilturek** [comment]
> This is a helpful improvement.
> 
> The message in your first version of the patch is a bit more understandable than the second IMO (the "Append to message instead of overwriting" commit). Interested why you changed it.

I didn't want to so radically change the message, but I may bring it back as it is more understable.

**Comment by bluetech** [comment]
Yes, I can see this.

Perhaps the right thing to do it give it an entirely new error code, like `attr-exported`, instead of `attr-defined`. Not sure what is the policy regarding the granularity of these though.

**Comment by JukkaL** [comment]
> Not sure what is the policy regarding the granularity of these though.

The policy on error codes is that if there's a realistic use case where having a separate error code would help, or if some error message can be confusing and providing more context via an error code (which can be looked up from the docs) can be helpful, splitting an error code may be reasonable.

**Comment by kamilturek** [comment]
I have changed back the message and appended "implicit reexport disabled".

**Comment by hauntsaninja** [comment]
Thanks!

**Pull request merged**
