### PR TITLE
TestItem: convert to dataclass, remove class vars

### PR DESCRIPTION
**Pull request by ikonst**
`TestItem` has instance attributes, so it doesn't need the class vars.

### CODE REVIEW

**Comment by ikonst** [comment]
👋 @hauntsaninja

**Comment by ikonst** [comment]
@JelleZijlstra while I have your attention :)

**Comment by JelleZijlstra** [comment]
Would it be better to make this class into a dataclass?

**Comment by ikonst** [comment]
It would, once we drop Python 3.7.

**Comment by ikonst** [comment]
Oh, wait, it's new in _3.7_.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by ikonst** [comment]
merge?

**Pull request merged**
