### PR TITLE
Narrow types for walrus assignment in if statements

### LINKED ISSUE #7313: PEP 572: Assignments not narrowed in right-hand side of and
The binder interaction doesn't work properly for assignments in the right-hand side of an `and` (after `if x and (y := 1):`, the type of `y` isn't narrowed to `int`).

Test case:
```

[case testAndRHS]
from typing import Optional

def f(x: Optional[int], y: Optional[int]) -> None:
    if x and (y := 1):
        reveal_type(y)  # N: Revealed type is 'builtins.int'
```
(Currently it produces `Revealed type is 'Union[builtins.int, None]'` instead.)

Followup from #6899

### LINKED ISSUE #7316: PEP 572: Type not narrowed correctly in assignment
Example from @gvanrossum in #6899:
```
from typing import Optional

class C:
    def foo(self):
        pass

def good(b: Optional[C]) -> None:
    a = b
    if a:
        a.foo()

def bad(b: Optional[C]) -> None:
    if a := b:
        a.foo()  # E:  Item "None" of "Optional[C]" has no attribute "foo"
```

### PR DESCRIPTION
**Pull request by hauntsaninja**
Fixes #7313
Fixes #7316

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Let me know if there's a better way to handle the partial types that can result! Or if there are more tests I should be adding. There's a lot that I don't know :-)

I guess one thing I was wondering if there's a way to improve the hint resulting from the partial type (see line 296 on `test-data/unit/check-python38.test`). Worried that it might be hard for users to realise that you would have to put the annotation on another line.

**Comment by JelleZijlstra** [comment]
I doubt that a lot of users are going to write `if (x := []):` (why would you do that except to confuse a typechecker?), so I don't think it's worth it to invest too much in improving the error message. We can revisit that if we get user complaints.

**Comment by TH3CHARLie** [comment]
Will you have an interest in testing against #7313 to see if the PR also happens to fix that issue?

**Comment by hauntsaninja** [comment]
Yes, it fixes #7313 too (updated the PR to mention that). A test exists for that issue on line 269 of `test-data/unit/check-python38.test`.

Looking through other issues, it does not fix #8236, but I can maybe work on that (in a separate PR).

**Pull request merged**
