### PR TITLE
Revisit the body of a loop if the number of partial types has changed.

### LINKED ISSUE #5423: False negative involving null checks on optional types
Here is a minimal program demonstrating the problem:
```
foo = None
for _ in range(2):
  if foo is not None:
    print(1[2])
  foo = 1

```
Expected behavior:
error: Value of type "int" is not indexable

Actual behavior:
mypy accepts the program as valid, when run with the --strict flag

This issue seems to be a problem with how mypy handles reassignment to None type variables, and static evaluation of conditionals.  After line 1, `foo` has the type None according to mypy.  Thus, mypy determines that the condition on line 3 will never hold, and thus doesn't do type checking for the body of the if statement.  On line 5, foo's type changes to `Optional[int]`. This, however, will only be reflected in code that follows line 5.

### PR DESCRIPTION
**Pull request by tyralla**
Fixes #5423

### CODE REVIEW

**Comment by hauntsaninja** [comment]
I went through the primer and this is looking great. 3-5 cases where ideally mypy would do something different, but may be technically unrelated to this PR (didn't look).

operator: true positive
prefect: false positive, seems like we should narrow from tuple to str on line 220
manticore: true positive
pylint: false positive, can't tell why mypy wants an explicit annotation
xarray: true positive from typing perspective (typeguard guarantee isn't encoded in signature)
sympy: true positive, should assert
comtypes: true positive, heterogeneous list that is mutated so can't be a tuple[int, x, y, z]
aiortc: true positive, not sure where _data comes from, is maybe patched on
httpx-caching: false positive, should infer int | None or require explicit annotation
jax: true positive, true positive
flake8: true positive, should assert
poetry: probably should infer Term | None or require an explicit annotation
dulwich: true positive, should assert
pyodide: false positive, not sure what's going on there

**Comment by tyralla** [comment]
@hauntsaninja: Thank you very much for looking so thoroughly through the primer!

**Comment by tyralla** [comment]
I had a look at the false positive for `prefect`.  It seems in fact unrelated to this PR, as it is reproducible without involving loops:

```python
from typing import Union, Tuple

def f() -> bool: ...

u: Union[int, Tuple[int]]
x = None
if f():
    x = u
    if isinstance(x, tuple):
        x = x[0]
reveal_type(x)  # N: Revealed type is "Union[builtins.int, Tuple[builtins.int], None]" 
```

(Tuple[builtins.int] should be narrowed away.)

**Review by ilevkivskyi — APPROVED** [review]
The fix makes sense to me. I will merge soon unless there are objections. (Please ping me if I forget about this PR)

**Review by hauntsaninja — APPROVED** [review]

**Pull request merged**
