### PR TITLE
Make fast parser checks for duplicate names in function definitions

### LINKED ISSUE #2732: Fast parser does not produce warnings about tuple argument names
Python 2 tuple arguments may have names which conflict with other arguments.  These are not caught with the fast parser.
For example, this function produces no errors:
```
def f(x, (x, y)):
  # type: (...) -> None
  pass
```

### PR DESCRIPTION
**Pull request by afrieder**
Fixes #2732 
Waiting on #2735 (new commits start at 874153fd1aa5411c19bf51390168138c915d45ea)

This also checks for the general case (as I described in my comment on #2732).

### CODE REVIEW

**Comment by gvanrossum** [comment]
Can you please change the topic to describe what changes rather than the
end result? E.g. "Make the fast parser check..." The plain present tense in
commit messages often confused me.

--Guido (mobile)

**Comment by afrieder** [comment]
Done. Sorry about that.

**Comment by ddfisher** [comment]
This looks good to me, thanks!  I added a couple more test cases that I thought were worthwhile.  Will merge this once #2735 lands.

**Comment by ddfisher** [comment]
You'll need to rebase again now that #2735 has been squashed onto master.

**Comment by afrieder** [comment]
Rebased.

**Comment by ddfisher** [comment]
Thanks!

**Pull request merged**
